// Homebrew - The missing package manager for macOS
import { CompletionSpec, Subcommand, Option, Suggestion } from '../types.js';

const formulaSuggestion: Suggestion = { name: 'formula', description: 'Package name' };
const caskSuggestion: Suggestion = { name: 'cask', description: 'Cask name' };

export const brewSpec: CompletionSpec = {
  name: 'brew',
  description: 'The Missing Package Manager for macOS (or Linux)',
  subcommands: [
    // Core commands
    {
      name: 'install',
      description: 'Install a formula or cask',
      options: [
        { name: '--cask', description: 'Install a cask' },
        { name: '--formula', description: 'Install a formula' },
        { name: '--HEAD', description: 'Install the HEAD version' },
        { name: '--fetch-HEAD', description: 'Fetch the HEAD version' },
        { name: '--only-dependencies', description: 'Install only dependencies' },
        { name: '--build-from-source', description: 'Build from source' },
        { name: '-s', description: 'Build from source' },
        { name: '--force-bottle', description: 'Install from bottle if available' },
        { name: '--include-test', description: 'Install test dependencies' },
        { name: '--interactive', description: 'Interactive install' },
        { name: '-i', description: 'Interactive install' },
        { name: '-g', description: 'Install globally' },
        { name: '--verbose', description: 'Verbose output' },
        { name: '-v', description: 'Verbose output' },
        { name: '--debug', description: 'Debug mode' },
        { name: '-d', description: 'Debug mode' },
        { name: '--quiet', description: 'Quiet output' },
        { name: '-q', description: 'Quiet output' },
        { name: '--force', description: 'Force install' },
        { name: '-f', description: 'Force install' },
        { name: '--overwrite', description: 'Overwrite existing files' },
        { name: '--dry-run', description: 'Show what would be done' },
        { name: '-n', description: 'Dry run' },
        { name: '--ignore-dependencies', description: 'Skip dependencies' },
        { name: '--display-times', description: 'Show install times' },
        { name: '--adopt', description: 'Adopt existing artifacts' },
        { name: '--skip-cask-deps', description: 'Skip cask dependencies' },
        { name: '--zap', description: 'Remove all files associated with cask' },
        { name: '--appdir', description: 'Target Application directory', args: { name: 'dir', template: 'folders' } },
        { name: '--language', description: 'Preferred language', args: { name: 'lang' } },
        { name: '--require-sha', description: 'Require SHA verification' },
        { name: '--no-binaries', description: 'Disable binary linking' },
        { name: '--no-quarantine', description: 'Disable quarantine' },
      ],
      args: { name: 'formula/cask', description: 'Package to install', isVariadic: true },
    },
    {
      name: 'uninstall',
      description: 'Uninstall a formula or cask',
      options: [
        { name: '--cask', description: 'Uninstall a cask' },
        { name: '--formula', description: 'Uninstall a formula' },
        { name: '--force', description: 'Force uninstall' },
        { name: '-f', description: 'Force uninstall' },
        { name: '--zap', description: 'Remove all files' },
        { name: '--ignore-dependencies', description: 'Ignore dependencies' },
      ],
      args: { name: 'formula/cask', description: 'Package to uninstall', isVariadic: true },
    },
    {
      name: 'upgrade',
      description: 'Upgrade outdated formulae and casks',
      options: [
        { name: '--cask', description: 'Upgrade casks only' },
        { name: '--formula', description: 'Upgrade formulae only' },
        { name: '--greedy', description: 'Also upgrade casks with auto_updates' },
        { name: '--greedy-latest', description: 'Upgrade casks that specify latest' },
        { name: '--greedy-auto-updates', description: 'Upgrade casks with auto_updates' },
        { name: '--force', description: 'Force upgrade' },
        { name: '-f', description: 'Force upgrade' },
        { name: '--verbose', description: 'Verbose output' },
        { name: '-v', description: 'Verbose output' },
        { name: '--dry-run', description: 'Show what would be upgraded' },
        { name: '-n', description: 'Dry run' },
        { name: '--interactive', description: 'Interactive upgrade' },
        { name: '-i', description: 'Interactive upgrade' },
        { name: '--fetch-HEAD', description: 'Fetch HEAD version' },
        { name: '--ignore-pinned', description: 'Ignore pinned formulae' },
        { name: '--display-times', description: 'Show upgrade times' },
      ],
      args: { name: 'formula/cask', description: 'Package to upgrade', isOptional: true, isVariadic: true },
    },
    {
      name: 'update',
      description: 'Fetch the newest version of Homebrew from GitHub',
      options: [
        { name: '--merge', description: 'Use git merge instead of rebase' },
        { name: '--auto-update', description: 'Auto-update' },
        { name: '--force', description: 'Force update' },
        { name: '-f', description: 'Force update' },
        { name: '--verbose', description: 'Verbose output' },
        { name: '-v', description: 'Verbose output' },
      ],
    },
    {
      name: 'search',
      description: 'Search for formulae and casks',
      options: [
        { name: '--cask', description: 'Search casks only' },
        { name: '--formula', description: 'Search formulae only' },
        { name: '--desc', description: 'Search descriptions too' },
        { name: '--pull-request', description: 'Search open PRs' },
        { name: '--open', description: 'Search open items' },
        { name: '--closed', description: 'Search closed items' },
        { name: '--macports', description: 'Search MacPorts' },
        { name: '--fink', description: 'Search Fink' },
        { name: '--opensuse', description: 'Search openSUSE' },
        { name: '--fedora', description: 'Search Fedora' },
        { name: '--debian', description: 'Search Debian' },
        { name: '--ubuntu', description: 'Search Ubuntu' },
      ],
      args: { name: 'text', description: 'Search term', isOptional: true },
    },
    {
      name: 'info',
      description: 'Display information about a formula or cask',
      options: [
        { name: '--cask', description: 'Show cask info' },
        { name: '--formula', description: 'Show formula info' },
        { name: '--json', description: 'Output as JSON' },
        { name: '--installed', description: 'Show info for installed packages' },
        { name: '--github', description: 'Open GitHub page' },
        { name: '--analytics', description: 'Show analytics' },
        { name: '--days', description: 'Analytics days', args: { name: 'days' } },
        { name: '--category', description: 'Analytics category', args: { name: 'category' } },
        { name: '--verbose', description: 'Verbose output' },
        { name: '-v', description: 'Verbose output' },
      ],
      args: { name: 'formula/cask', description: 'Package to show info for', isOptional: true, isVariadic: true },
    },
    {
      name: 'list',
      description: 'List all installed formulae and casks',
      options: [
        { name: '--cask', description: 'List casks only' },
        { name: '--formula', description: 'List formulae only' },
        { name: '--full-name', description: 'Show full names' },
        { name: '--versions', description: 'Show versions' },
        { name: '--multiple', description: 'Show packages with multiple versions' },
        { name: '--pinned', description: 'Show pinned packages' },
        { name: '-1', description: 'One entry per line' },
        { name: '-l', description: 'Long format' },
        { name: '-r', description: 'Reverse sort' },
        { name: '-t', description: 'Sort by modification time' },
      ],
      args: { name: 'formula/cask', description: 'Package to list', isOptional: true, isVariadic: true },
    },
    {
      name: 'outdated',
      description: 'List installed formulae and casks with newer versions',
      options: [
        { name: '--cask', description: 'List outdated casks only' },
        { name: '--formula', description: 'List outdated formulae only' },
        { name: '--json', description: 'Output as JSON' },
        { name: '--verbose', description: 'Verbose output' },
        { name: '-v', description: 'Verbose output' },
        { name: '--greedy', description: 'Include auto-update casks' },
        { name: '--fetch-HEAD', description: 'Fetch HEAD versions' },
      ],
      args: { name: 'formula/cask', description: 'Package to check', isOptional: true, isVariadic: true },
    },
    {
      name: 'deps',
      description: 'Show dependencies for formulae',
      options: [
        { name: '--tree', description: 'Show as tree' },
        { name: '--graph', description: 'Show as graph' },
        { name: '--installed', description: 'Show for installed packages' },
        { name: '-n', description: 'Show in topological order' },
        { name: '--include-build', description: 'Include build dependencies' },
        { name: '--include-test', description: 'Include test dependencies' },
        { name: '--include-optional', description: 'Include optional dependencies' },
        { name: '--skip-recommended', description: 'Skip recommended dependencies' },
        { name: '--for-each', description: 'Show for each formula' },
        { name: '--full-name', description: 'Show full names' },
        { name: '--1', description: 'One per line' },
        { name: '--union', description: 'Show union of dependencies' },
      ],
      args: { name: 'formula', description: 'Formula to show deps for', isOptional: true, isVariadic: true },
    },
    {
      name: 'uses',
      description: 'Show formulae that depend on the given formula',
      options: [
        { name: '--installed', description: 'Only installed packages' },
        { name: '--recursive', description: 'Recursive check' },
        { name: '--include-build', description: 'Include build deps' },
        { name: '--include-test', description: 'Include test deps' },
        { name: '--include-optional', description: 'Include optional deps' },
        { name: '--skip-recommended', description: 'Skip recommended deps' },
        { name: '--formula', description: 'Treat as formula' },
        { name: '--cask', description: 'Treat as cask' },
      ],
      args: { name: 'formula', description: 'Formula to check', isVariadic: true },
    },
    {
      name: 'cleanup',
      description: 'Remove stale lock files and outdated downloads',
      options: [
        { name: '--prune', description: 'Remove all cache files older than specified days', args: { name: 'days' } },
        { name: '-n', description: 'Dry run' },
        { name: '--dry-run', description: 'Dry run' },
        { name: '-s', description: 'Scrub cache' },
        { name: '--prune-prefix', description: 'Only prune symlinks and directories' },
      ],
      args: { name: 'formula/cask', description: 'Package to clean', isOptional: true, isVariadic: true },
    },
    {
      name: 'doctor',
      description: 'Check your system for potential problems',
      options: [
        { name: '--list-checks', description: 'List available checks' },
        { name: '-D', description: 'Debug mode' },
        { name: '--audit-debug', description: 'Audit debug' },
      ],
    },
    {
      name: 'config',
      description: 'Show Homebrew and system configuration',
    },
    {
      name: 'pin',
      description: 'Pin a formula to prevent upgrades',
      args: { name: 'formula', description: 'Formula to pin', isVariadic: true },
    },
    {
      name: 'unpin',
      description: 'Unpin a formula to allow upgrades',
      args: { name: 'formula', description: 'Formula to unpin', isVariadic: true },
    },
    {
      name: 'tap',
      description: 'Tap a formula repository',
      options: [
        { name: '--full', description: 'Clone full repo' },
        { name: '--shallow', description: 'Shallow clone' },
        { name: '--force-auto-update', description: 'Force auto-update' },
        { name: '--repair', description: 'Repair taps' },
        { name: '--list-pinned', description: 'List pinned taps' },
      ],
      args: [
        { name: 'user/repo', description: 'Tap to add', isOptional: true },
        { name: 'url', description: 'URL of the tap', isOptional: true },
      ],
    },
    {
      name: 'untap',
      description: 'Remove a tapped repository',
      options: [
        { name: '--force', description: 'Force removal' },
        { name: '-f', description: 'Force removal' },
      ],
      args: { name: 'tap', description: 'Tap to remove', isVariadic: true },
    },
    {
      name: 'link',
      description: 'Symlink a formula into the Homebrew prefix',
      options: [
        { name: '--overwrite', description: 'Overwrite existing files' },
        { name: '--force', description: 'Force linking' },
        { name: '-f', description: 'Force linking' },
        { name: '--dry-run', description: 'Show what would be done' },
        { name: '-n', description: 'Dry run' },
        { name: '--HEAD', description: 'Link HEAD version' },
      ],
      args: { name: 'formula', description: 'Formula to link', isVariadic: true },
    },
    {
      name: 'unlink',
      description: 'Unlink a formula from the Homebrew prefix',
      options: [
        { name: '--dry-run', description: 'Show what would be done' },
        { name: '-n', description: 'Dry run' },
      ],
      args: { name: 'formula', description: 'Formula to unlink', isVariadic: true },
    },
    {
      name: 'services',
      description: 'Manage background services',
      subcommands: [
        {
          name: 'list',
          description: 'List all services',
          options: [
            { name: '--json', description: 'Output as JSON' },
          ],
        },
        {
          name: 'start',
          description: 'Start a service',
          options: [
            { name: '--all', description: 'Start all services' },
          ],
          args: { name: 'formula', description: 'Service to start', isOptional: true, isVariadic: true },
        },
        {
          name: 'stop',
          description: 'Stop a service',
          options: [
            { name: '--all', description: 'Stop all services' },
          ],
          args: { name: 'formula', description: 'Service to stop', isOptional: true, isVariadic: true },
        },
        {
          name: 'restart',
          description: 'Restart a service',
          options: [
            { name: '--all', description: 'Restart all services' },
          ],
          args: { name: 'formula', description: 'Service to restart', isOptional: true, isVariadic: true },
        },
        {
          name: 'run',
          description: 'Run a service (without registering it)',
          args: { name: 'formula', description: 'Service to run', isVariadic: true },
        },
        { name: 'cleanup', description: 'Remove unused service files' },
      ],
    },
    {
      name: 'cask',
      description: 'Install macOS applications',
      subcommands: [
        { name: 'install', description: 'Install a cask', args: { name: 'cask', isVariadic: true } },
        { name: 'uninstall', description: 'Uninstall a cask', args: { name: 'cask', isVariadic: true } },
        { name: 'reinstall', description: 'Reinstall a cask', args: { name: 'cask', isVariadic: true } },
        { name: 'upgrade', description: 'Upgrade casks', args: { name: 'cask', isOptional: true, isVariadic: true } },
        { name: 'list', description: 'List installed casks' },
        { name: 'info', description: 'Show cask info', args: { name: 'cask', isVariadic: true } },
        { name: 'zap', description: 'Zap a cask', args: { name: 'cask', isVariadic: true } },
      ],
    },
    {
      name: 'reinstall',
      description: 'Reinstall a formula or cask',
      options: [
        { name: '--cask', description: 'Reinstall a cask' },
        { name: '--formula', description: 'Reinstall a formula' },
        { name: '--force', description: 'Force reinstall' },
        { name: '-f', description: 'Force reinstall' },
        { name: '--verbose', description: 'Verbose output' },
        { name: '-v', description: 'Verbose output' },
        { name: '--debug', description: 'Debug mode' },
        { name: '-d', description: 'Debug mode' },
      ],
      args: { name: 'formula/cask', description: 'Package to reinstall', isVariadic: true },
    },
    {
      name: 'leaves',
      description: 'List installed formulae that are not dependencies',
      options: [
        { name: '--installed-on-request', description: 'Show only requested installs' },
        { name: '--installed-as-dependency', description: 'Show only dependency installs' },
      ],
    },
    {
      name: 'autoremove',
      description: 'Remove formulae that are no longer needed',
      options: [
        { name: '--dry-run', description: 'Show what would be removed' },
        { name: '-n', description: 'Dry run' },
      ],
    },
    {
      name: 'edit',
      description: 'Edit a formula or cask',
      options: [
        { name: '--cask', description: 'Edit a cask' },
        { name: '--formula', description: 'Edit a formula' },
        { name: '--print-path', description: 'Print path only' },
      ],
      args: { name: 'formula/cask', description: 'Package to edit', isOptional: true },
    },
    {
      name: 'home',
      description: 'Open a formula or casks homepage in a browser',
      options: [
        { name: '--cask', description: 'Open cask homepage' },
        { name: '--formula', description: 'Open formula homepage' },
      ],
      args: { name: 'formula/cask', description: 'Package homepage to open', isOptional: true },
    },
    {
      name: 'log',
      description: 'Show git log for a formula or the Homebrew repository',
      options: [
        { name: '--max-count', description: 'Max entries', args: { name: 'number' } },
        { name: '-n', description: 'Max entries', args: { name: 'number' } },
        { name: '--oneline', description: 'One line per entry' },
        { name: '-1', description: 'Show only one entry' },
        { name: '-p', description: 'Show patch' },
        { name: '--stat', description: 'Show stats' },
      ],
      args: { name: 'formula', description: 'Formula to show log for', isOptional: true },
    },
    {
      name: 'fetch',
      description: 'Download source packages without installing',
      options: [
        { name: '--HEAD', description: 'Fetch HEAD version' },
        { name: '--force', description: 'Force fetch' },
        { name: '-f', description: 'Force fetch' },
        { name: '--retry', description: 'Retry on failure' },
        { name: '--deps', description: 'Also fetch dependencies' },
        { name: '--build-from-source', description: 'Fetch source' },
        { name: '-s', description: 'Fetch source' },
        { name: '--cask', description: 'Fetch a cask' },
        { name: '--formula', description: 'Fetch a formula' },
      ],
      args: { name: 'formula/cask', description: 'Package to fetch', isVariadic: true },
    },
    {
      name: 'switch',
      description: 'Switch between different installed versions of a formula',
      args: [
        { name: 'formula', description: 'Formula to switch' },
        { name: 'version', description: 'Version to switch to' },
      ],
    },
    {
      name: 'shellenv',
      description: 'Print export statements for Homebrew environment',
    },
    {
      name: 'completions',
      description: 'Control whether Homebrew automatically links external tap completions',
      subcommands: [
        { name: 'state', description: 'Show current state' },
        { name: 'link', description: 'Link completions' },
        { name: 'unlink', description: 'Unlink completions' },
      ],
    },
    {
      name: 'analytics',
      description: 'Manage Homebrew analytics',
      subcommands: [
        { name: 'state', description: 'Show analytics state' },
        { name: 'on', description: 'Turn analytics on' },
        { name: 'off', description: 'Turn analytics off' },
        { name: 'regenerate-uuid', description: 'Regenerate UUID' },
      ],
    },
    {
      name: 'help',
      description: 'Show help for a command',
      args: { name: 'command', description: 'Command to get help for', isOptional: true },
    },
    {
      name: 'commands',
      description: 'List all built-in and external commands',
      options: [
        { name: '--quiet', description: 'Quiet output' },
        { name: '-q', description: 'Quiet output' },
        { name: '--include-aliases', description: 'Include aliases' },
      ],
    },
  ],
  options: [
    { name: '--help', description: 'Show help' },
    { name: '-h', description: 'Show help' },
    { name: '--version', description: 'Show version' },
    { name: '-v', description: 'Show version' },
    { name: '--verbose', description: 'Verbose output' },
    { name: '--debug', description: 'Debug mode' },
    { name: '-d', description: 'Debug mode' },
    { name: '--env', description: 'Environment summary' },
  ],
};
