// Bun - Fast all-in-one JavaScript runtime
import { CompletionSpec } from '../types.js';

export const bunSpec: CompletionSpec = {
  name: 'bun',
  description: 'Incredibly fast JavaScript runtime, bundler, test runner, and package manager',
  options: [
    { name: '--version', description: 'Print version' },
    { name: '--help', description: 'Print help' },
    { name: '--cwd', description: 'Change directory', args: { name: 'dir', template: 'folders' } },
    { name: '-c', description: 'Config file', args: { name: 'file', template: 'filepaths' } },
    { name: '--config', description: 'Config file', args: { name: 'file', template: 'filepaths' } },
  ],
  subcommands: [
    {
      name: 'run',
      description: 'Run a file, script, or package bin',
      options: [
        { name: '--watch', description: 'Watch mode' },
        { name: '--hot', description: 'Hot reload' },
        { name: '--smol', description: 'Use less memory' },
        { name: '--silent', description: 'No output' },
        { name: '--bun', description: 'Force bun runtime' },
        { name: '--if-present', description: "Don't error if missing" },
        { name: '--filter', description: 'Filter workspaces', args: { name: 'pattern' } },
        { name: '--cwd', description: 'Working directory', args: { name: 'dir', template: 'folders' } },
        { name: '--preload', description: 'Preload module', args: { name: 'module' } },
        { name: '--env-file', description: 'Load env file', args: { name: 'file', template: 'filepaths' } },
      ],
      args: { name: 'script', description: 'Script or file to run', isVariadic: true },
    },
    {
      name: 'install',
      description: 'Install dependencies',
      options: [
        { name: ['-d', '--dev', '-D'], description: 'Add as dev dependency' },
        { name: '--optional', description: 'Add as optional dependency' },
        { name: ['-g', '--global'], description: 'Install globally' },
        { name: ['-p', '--production'], description: 'Production only' },
        { name: '--frozen-lockfile', description: 'Error if lockfile changes' },
        { name: '--no-save', description: "Don't update package.json" },
        { name: '--dry-run', description: 'Dry run' },
        { name: ['-f', '--force'], description: 'Force reinstall' },
        { name: '--cache-dir', description: 'Cache directory', args: { name: 'dir', template: 'folders' } },
        { name: '--no-cache', description: 'Ignore cache' },
        { name: '--silent', description: 'No output' },
        { name: ['-y', '--yarn'], description: 'Use yarn.lock' },
        { name: '--backend', description: 'Package backend', args: { name: 'backend', suggestions: [{ name: 'hardlink' }, { name: 'symlink' }, { name: 'copyfile' }] } },
        { name: '--concurrent-scripts', description: 'Max concurrent scripts', args: { name: 'number' } },
        { name: '--trust', description: 'Trust lifecycle scripts' },
      ],
      args: { name: 'package', description: 'Package to install', isOptional: true, isVariadic: true },
    },
    { name: 'i', description: 'Alias for install' },
    {
      name: 'add',
      description: 'Add a dependency',
      options: [
        { name: ['-d', '--dev', '-D'], description: 'Add as dev dependency' },
        { name: '--optional', description: 'Add as optional dependency' },
        { name: '--exact', description: 'Add exact version' },
        { name: ['-g', '--global'], description: 'Install globally' },
        { name: '--trust', description: 'Trust lifecycle scripts' },
      ],
      args: { name: 'package', description: 'Package to add', isVariadic: true },
    },
    {
      name: 'remove',
      description: 'Remove a dependency',
      options: [
        { name: ['-g', '--global'], description: 'Remove global package' },
      ],
      args: { name: 'package', description: 'Package to remove', isVariadic: true },
    },
    { name: 'rm', description: 'Alias for remove', args: { name: 'package', isVariadic: true } },
    {
      name: 'update',
      description: 'Update dependencies',
      options: [
        { name: '--latest', description: 'Update to latest' },
        { name: ['-g', '--global'], description: 'Update global packages' },
      ],
      args: { name: 'package', description: 'Package to update', isOptional: true, isVariadic: true },
    },
    {
      name: 'link',
      description: 'Link a package',
      options: [
        { name: '--save', description: 'Save to package.json' },
      ],
      args: { name: 'package', description: 'Package to link', isOptional: true },
    },
    { name: 'unlink', description: 'Unlink a package', args: { name: 'package', isOptional: true } },
    { name: 'pm', description: 'Package manager utilities', subcommands: [
      { name: 'bin', description: 'Print bin folder', options: [{ name: ['-g', '--global'] }] },
      { name: 'ls', description: 'List installed packages', options: [{ name: '--all' }] },
      { name: 'hash', description: 'Hash dependencies' },
      { name: 'hash-print', description: 'Print dependency hash' },
      { name: 'hash-string', description: 'Hash a string', args: { name: 'string' } },
      { name: 'cache', description: 'Manage cache', subcommands: [
        { name: 'rm', description: 'Clear cache' },
      ]},
      { name: 'trust', description: 'Trust package scripts', args: { name: 'package', isVariadic: true } },
      { name: 'untrust', description: 'Untrust package scripts', args: { name: 'package', isVariadic: true } },
      { name: 'default-trusted', description: 'List default trusted packages' },
      { name: 'migrate', description: 'Migrate from other package managers' },
    ]},
    {
      name: 'test',
      description: 'Run tests',
      options: [
        { name: '--watch', description: 'Watch mode' },
        { name: '--bail', description: 'Stop on first failure', args: { name: 'count', isOptional: true } },
        { name: '--timeout', description: 'Test timeout', args: { name: 'ms' } },
        { name: '--rerun-each', description: 'Rerun each test', args: { name: 'count' } },
        { name: '--only', description: 'Run only focused tests' },
        { name: '--todo', description: 'Include todo tests' },
        { name: '--coverage', description: 'Enable coverage' },
        { name: '--coverage-dir', description: 'Coverage directory', args: { name: 'dir', template: 'folders' } },
        { name: '--preload', description: 'Preload module', args: { name: 'module' } },
        { name: '-t', description: 'Test name pattern', args: { name: 'pattern' } },
        { name: '--test-name-pattern', description: 'Test name pattern', args: { name: 'pattern' } },
      ],
      args: { name: 'files', description: 'Test files', template: 'filepaths', isOptional: true, isVariadic: true },
    },
    {
      name: 'build',
      description: 'Bundle TypeScript and JavaScript',
      options: [
        { name: '--compile', description: 'Create executable' },
        { name: '--outdir', description: 'Output directory', args: { name: 'dir', template: 'folders' } },
        { name: '--outfile', description: 'Output file', args: { name: 'file', template: 'filepaths' } },
        { name: '--target', description: 'Target', args: { name: 'target', suggestions: [{ name: 'browser' }, { name: 'bun' }, { name: 'node' }] } },
        { name: '--format', description: 'Output format', args: { name: 'format', suggestions: [{ name: 'esm' }, { name: 'cjs' }, { name: 'iife' }] } },
        { name: '--minify', description: 'Minify output' },
        { name: '--minify-syntax', description: 'Minify syntax' },
        { name: '--minify-whitespace', description: 'Minify whitespace' },
        { name: '--minify-identifiers', description: 'Minify identifiers' },
        { name: '--sourcemap', description: 'Generate sourcemap', args: { name: 'type', suggestions: [{ name: 'none' }, { name: 'inline' }, { name: 'external' }, { name: 'linked' }], isOptional: true } },
        { name: '--entry-naming', description: 'Entry naming pattern', args: { name: 'pattern' } },
        { name: '--chunk-naming', description: 'Chunk naming pattern', args: { name: 'pattern' } },
        { name: '--asset-naming', description: 'Asset naming pattern', args: { name: 'pattern' } },
        { name: '--splitting', description: 'Enable code splitting' },
        { name: '--no-bundle', description: 'Disable bundling' },
        { name: '--external', description: 'Mark as external', args: { name: 'module' } },
        { name: '--public-path', description: 'Public URL prefix', args: { name: 'path' } },
        { name: '--root', description: 'Root directory', args: { name: 'dir', template: 'folders' } },
        { name: '--define', description: 'Define constant', args: { name: 'key=value' } },
        { name: '--loader', description: 'File loader', args: { name: 'ext:loader' } },
        { name: '--packages', description: 'Package handling', args: { name: 'mode', suggestions: [{ name: 'bundle' }, { name: 'external' }] } },
      ],
      args: { name: 'entrypoints', description: 'Entry files', template: 'filepaths', isVariadic: true },
    },
    {
      name: 'x',
      description: 'Execute a package binary (like npx)',
      options: [
        { name: '--bun', description: 'Force bun runtime' },
      ],
      args: { name: 'command', description: 'Package command', isVariadic: true },
    },
    { name: 'create', description: 'Create a new project', args: [{ name: 'template', description: 'Template', suggestions: [{ name: 'react' }, { name: 'next' }, { name: 'vite' }, { name: 'elysia' }, { name: 'hono' }] }, { name: 'name', description: 'Project name', isOptional: true }] },
    { name: 'init', description: 'Initialize a project', options: [{ name: ['-y', '--yes'], description: 'Use defaults' }] },
    { name: 'repl', description: 'Start interactive REPL' },
    { name: 'upgrade', description: 'Upgrade bun', options: [{ name: '--canary' }, { name: '--stable' }] },
    { name: 'outdated', description: 'List outdated dependencies' },
  ],
  args: {
    name: 'file',
    description: 'File to run',
    template: 'filepaths',
    isOptional: true,
  },
};
