// Conda - Package, dependency and environment management
import { CompletionSpec, Suggestion } from '../types.js';

export const condaSpec: CompletionSpec = {
  name: 'conda',
  description: 'Package, dependency, and environment management',
  subcommands: [
    // Environment management
    {
      name: 'create',
      description: 'Create a new conda environment',
      options: [
        { name: ['-n', '--name'], description: 'Name of environment', args: { name: 'name' } },
        { name: ['-p', '--prefix'], description: 'Path to environment', args: { name: 'path', template: 'folders' } },
        { name: ['-c', '--channel'], description: 'Additional channel', args: { name: 'channel' } },
        { name: '--use-local', description: 'Use locally built packages' },
        { name: '--override-channels', description: 'Override channels' },
        { name: '--repodata-fn', description: 'Repodata filename', args: { name: 'filename' } },
        { name: '--strict-channel-priority', description: 'Strict channel priority' },
        { name: '--no-channel-priority', description: 'No channel priority' },
        { name: '--no-deps', description: 'Do not install dependencies' },
        { name: '--only-deps', description: 'Only install dependencies' },
        { name: '--no-pin', description: 'Ignore pinned specs' },
        { name: '--copy', description: 'Install using copies instead of links' },
        { name: '--no-shortcuts', description: 'Dont create shortcuts' },
        { name: ['-C', '--use-index-cache'], description: 'Use index cache' },
        { name: ['-k', '--insecure'], description: 'Allow insecure SSL' },
        { name: '--offline', description: 'Offline mode' },
        { name: ['-d', '--dry-run'], description: 'Dry run' },
        { name: '--json', description: 'Output as JSON' },
        { name: ['-q', '--quiet'], description: 'Quiet mode' },
        { name: ['-v', '--verbose'], description: 'Verbose mode' },
        { name: ['-y', '--yes'], description: 'Do not ask for confirmation' },
        { name: '--download-only', description: 'Download only' },
        { name: '--show-channel-urls', description: 'Show channel URLs' },
        { name: '--file', description: 'Read package specs from file', args: { name: 'file', template: 'filepaths' } },
        { name: '--no-default-packages', description: 'Ignore default packages' },
        { name: '--solver', description: 'Solver backend', args: { name: 'solver', suggestions: [{ name: 'classic' }, { name: 'libmamba' }] } },
        { name: '--clone', description: 'Clone existing environment', args: { name: 'env' } },
      ],
      args: { name: 'packages', description: 'Packages to install', isOptional: true, isVariadic: true },
    },
    {
      name: 'activate',
      description: 'Activate a conda environment',
      options: [
        { name: '--stack', description: 'Stack environment on top of current' },
        { name: '--no-stack', description: 'Do not stack' },
      ],
      args: { name: 'environment', description: 'Environment to activate', isOptional: true },
    },
    {
      name: 'deactivate',
      description: 'Deactivate the current conda environment',
    },
    {
      name: 'env',
      description: 'Manage environments',
      subcommands: [
        {
          name: 'list',
          description: 'List all environments',
          options: [
            { name: '--json', description: 'Output as JSON' },
            { name: ['-q', '--quiet'], description: 'Quiet mode' },
            { name: ['-v', '--verbose'], description: 'Verbose mode' },
          ],
        },
        {
          name: 'create',
          description: 'Create an environment from a YAML file',
          options: [
            { name: ['-f', '--file'], description: 'Environment file', args: { name: 'file', template: 'filepaths' } },
            { name: ['-n', '--name'], description: 'Environment name', args: { name: 'name' } },
            { name: ['-p', '--prefix'], description: 'Environment path', args: { name: 'path', template: 'folders' } },
            { name: ['-q', '--quiet'], description: 'Quiet mode' },
            { name: ['-v', '--verbose'], description: 'Verbose mode' },
            { name: '--force', description: 'Force creation' },
            { name: '--json', description: 'Output as JSON' },
            { name: '--solver', description: 'Solver backend', args: { name: 'solver' } },
          ],
        },
        {
          name: 'export',
          description: 'Export environment to a YAML file',
          options: [
            { name: ['-n', '--name'], description: 'Environment name', args: { name: 'name' } },
            { name: ['-p', '--prefix'], description: 'Environment path', args: { name: 'path', template: 'folders' } },
            { name: ['-f', '--file'], description: 'Output file', args: { name: 'file', template: 'filepaths' } },
            { name: '--no-builds', description: 'Remove build strings' },
            { name: '--ignore-channels', description: 'Ignore channel info' },
            { name: '--from-history', description: 'Only explicitly requested packages' },
            { name: '--json', description: 'Output as JSON' },
            { name: ['-q', '--quiet'], description: 'Quiet mode' },
            { name: ['-v', '--verbose'], description: 'Verbose mode' },
          ],
        },
        {
          name: 'remove',
          description: 'Remove an environment',
          options: [
            { name: ['-n', '--name'], description: 'Environment name', args: { name: 'name' } },
            { name: ['-p', '--prefix'], description: 'Environment path', args: { name: 'path', template: 'folders' } },
            { name: ['-d', '--dry-run'], description: 'Dry run' },
            { name: '--json', description: 'Output as JSON' },
            { name: ['-q', '--quiet'], description: 'Quiet mode' },
            { name: ['-v', '--verbose'], description: 'Verbose mode' },
            { name: ['-y', '--yes'], description: 'Do not ask for confirmation' },
            { name: '--all', description: 'Remove all packages' },
          ],
        },
        {
          name: 'update',
          description: 'Update environment from a YAML file',
          options: [
            { name: ['-f', '--file'], description: 'Environment file', args: { name: 'file', template: 'filepaths' } },
            { name: ['-n', '--name'], description: 'Environment name', args: { name: 'name' } },
            { name: ['-p', '--prefix'], description: 'Environment path', args: { name: 'path', template: 'folders' } },
            { name: '--prune', description: 'Remove packages not in file' },
            { name: ['-q', '--quiet'], description: 'Quiet mode' },
            { name: ['-v', '--verbose'], description: 'Verbose mode' },
            { name: '--json', description: 'Output as JSON' },
            { name: '--solver', description: 'Solver backend', args: { name: 'solver' } },
          ],
        },
        {
          name: 'config',
          description: 'Configure environment settings',
          subcommands: [
            {
              name: 'vars',
              description: 'Manage environment variables',
              subcommands: [
                { name: 'list', description: 'List environment variables' },
                { name: 'set', description: 'Set environment variables', args: { name: 'KEY=VALUE', isVariadic: true } },
                { name: 'unset', description: 'Unset environment variables', args: { name: 'KEY', isVariadic: true } },
              ],
            },
          ],
        },
      ],
    },
    // Package management
    {
      name: 'install',
      description: 'Install packages',
      options: [
        { name: ['-n', '--name'], description: 'Environment name', args: { name: 'name' } },
        { name: ['-p', '--prefix'], description: 'Environment path', args: { name: 'path', template: 'folders' } },
        { name: ['-c', '--channel'], description: 'Additional channel', args: { name: 'channel' } },
        { name: '--use-local', description: 'Use locally built packages' },
        { name: '--override-channels', description: 'Override channels' },
        { name: '--repodata-fn', description: 'Repodata filename', args: { name: 'filename' } },
        { name: '--strict-channel-priority', description: 'Strict channel priority' },
        { name: '--no-channel-priority', description: 'No channel priority' },
        { name: '--no-deps', description: 'Do not install dependencies' },
        { name: '--only-deps', description: 'Only install dependencies' },
        { name: '--no-pin', description: 'Ignore pinned specs' },
        { name: '--force-reinstall', description: 'Force reinstall' },
        { name: '--freeze-installed', description: 'Do not update existing packages' },
        { name: '--update-deps', description: 'Update dependencies' },
        { name: '-S', description: 'Do not update existing packages' },
        { name: '--update-all', description: 'Update all packages' },
        { name: '--update-specs', description: 'Update based on specs' },
        { name: '--copy', description: 'Install using copies' },
        { name: ['-m', '--mkdir'], description: 'Create prefix directory' },
        { name: '--clobber', description: 'Allow clobbering' },
        { name: ['-C', '--use-index-cache'], description: 'Use index cache' },
        { name: ['-k', '--insecure'], description: 'Allow insecure SSL' },
        { name: '--offline', description: 'Offline mode' },
        { name: ['-d', '--dry-run'], description: 'Dry run' },
        { name: '--json', description: 'Output as JSON' },
        { name: ['-q', '--quiet'], description: 'Quiet mode' },
        { name: ['-v', '--verbose'], description: 'Verbose mode' },
        { name: ['-y', '--yes'], description: 'Do not ask for confirmation' },
        { name: '--download-only', description: 'Download only' },
        { name: '--show-channel-urls', description: 'Show channel URLs' },
        { name: '--file', description: 'Read package specs from file', args: { name: 'file', template: 'filepaths' } },
        { name: '--solver', description: 'Solver backend', args: { name: 'solver' } },
        { name: '--revision', description: 'Revert to revision', args: { name: 'revision' } },
      ],
      args: { name: 'packages', description: 'Packages to install', isVariadic: true },
    },
    {
      name: 'update',
      description: 'Update packages',
      options: [
        { name: ['-n', '--name'], description: 'Environment name', args: { name: 'name' } },
        { name: ['-p', '--prefix'], description: 'Environment path', args: { name: 'path', template: 'folders' } },
        { name: ['-c', '--channel'], description: 'Additional channel', args: { name: 'channel' } },
        { name: '--use-local', description: 'Use locally built packages' },
        { name: '--override-channels', description: 'Override channels' },
        { name: '--all', description: 'Update all packages' },
        { name: '--freeze-installed', description: 'Do not update other packages' },
        { name: ['-d', '--dry-run'], description: 'Dry run' },
        { name: '--json', description: 'Output as JSON' },
        { name: ['-q', '--quiet'], description: 'Quiet mode' },
        { name: ['-v', '--verbose'], description: 'Verbose mode' },
        { name: ['-y', '--yes'], description: 'Do not ask for confirmation' },
        { name: '--solver', description: 'Solver backend', args: { name: 'solver' } },
      ],
      args: { name: 'packages', description: 'Packages to update', isOptional: true, isVariadic: true },
    },
    {
      name: 'upgrade',
      description: 'Alias for update',
      options: [
        { name: ['-n', '--name'], description: 'Environment name', args: { name: 'name' } },
        { name: ['-p', '--prefix'], description: 'Environment path', args: { name: 'path', template: 'folders' } },
        { name: '--all', description: 'Update all packages' },
        { name: ['-d', '--dry-run'], description: 'Dry run' },
        { name: ['-y', '--yes'], description: 'Do not ask for confirmation' },
      ],
      args: { name: 'packages', description: 'Packages to upgrade', isOptional: true, isVariadic: true },
    },
    {
      name: 'remove',
      description: 'Remove packages',
      options: [
        { name: ['-n', '--name'], description: 'Environment name', args: { name: 'name' } },
        { name: ['-p', '--prefix'], description: 'Environment path', args: { name: 'path', template: 'folders' } },
        { name: ['-c', '--channel'], description: 'Additional channel', args: { name: 'channel' } },
        { name: '--use-local', description: 'Use locally built packages' },
        { name: '--override-channels', description: 'Override channels' },
        { name: '--all', description: 'Remove all packages' },
        { name: '--features', description: 'Remove features' },
        { name: '--force-remove', description: 'Force removal' },
        { name: '--no-pin', description: 'Ignore pinned specs' },
        { name: ['-C', '--use-index-cache'], description: 'Use index cache' },
        { name: ['-k', '--insecure'], description: 'Allow insecure SSL' },
        { name: '--offline', description: 'Offline mode' },
        { name: ['-d', '--dry-run'], description: 'Dry run' },
        { name: '--json', description: 'Output as JSON' },
        { name: ['-q', '--quiet'], description: 'Quiet mode' },
        { name: ['-v', '--verbose'], description: 'Verbose mode' },
        { name: ['-y', '--yes'], description: 'Do not ask for confirmation' },
        { name: '--solver', description: 'Solver backend', args: { name: 'solver' } },
      ],
      args: { name: 'packages', description: 'Packages to remove', isOptional: true, isVariadic: true },
    },
    {
      name: 'uninstall',
      description: 'Alias for remove',
      args: { name: 'packages', description: 'Packages to uninstall', isVariadic: true },
    },
    {
      name: 'list',
      description: 'List packages in an environment',
      options: [
        { name: ['-n', '--name'], description: 'Environment name', args: { name: 'name' } },
        { name: ['-p', '--prefix'], description: 'Environment path', args: { name: 'path', template: 'folders' } },
        { name: '--show-channel-urls', description: 'Show channel URLs' },
        { name: '--no-show-channel-urls', description: 'Hide channel URLs' },
        { name: ['-r', '--revisions'], description: 'Show revision history' },
        { name: '--no-pip', description: 'Do not include pip packages' },
        { name: ['-e', '--export'], description: 'Output for export' },
        { name: '--md5', description: 'Show MD5 sums' },
        { name: '--explicit', description: 'Explicit format' },
        { name: '--json', description: 'Output as JSON' },
        { name: ['-q', '--quiet'], description: 'Quiet mode' },
        { name: ['-v', '--verbose'], description: 'Verbose mode' },
      ],
      args: { name: 'regex', description: 'Package name pattern', isOptional: true },
    },
    {
      name: 'search',
      description: 'Search for packages',
      options: [
        { name: ['-c', '--channel'], description: 'Additional channel', args: { name: 'channel' } },
        { name: '--use-local', description: 'Use locally built packages' },
        { name: '--override-channels', description: 'Override channels' },
        { name: '--envs', description: 'Search all environments' },
        { name: '--subdir', description: 'Search subdirectory', args: { name: 'subdir' } },
        { name: '--platform', description: 'Search platform', args: { name: 'platform' } },
        { name: '-i', description: 'Full info' },
        { name: '--info', description: 'Full info' },
        { name: ['-C', '--use-index-cache'], description: 'Use index cache' },
        { name: ['-k', '--insecure'], description: 'Allow insecure SSL' },
        { name: '--offline', description: 'Offline mode' },
        { name: '--json', description: 'Output as JSON' },
        { name: ['-q', '--quiet'], description: 'Quiet mode' },
        { name: ['-v', '--verbose'], description: 'Verbose mode' },
      ],
      args: { name: 'package', description: 'Package name to search', isOptional: true },
    },
    {
      name: 'info',
      description: 'Display information about conda',
      options: [
        { name: ['-a', '--all'], description: 'Show all information' },
        { name: ['-s', '--system'], description: 'Show system information' },
        { name: '-e', description: 'Show environments' },
        { name: '--envs', description: 'Show environments' },
        { name: '--base', description: 'Show base environment path' },
        { name: '--unsafe-channels', description: 'Show unsafe channels' },
        { name: '--json', description: 'Output as JSON' },
        { name: ['-q', '--quiet'], description: 'Quiet mode' },
        { name: ['-v', '--verbose'], description: 'Verbose mode' },
      ],
    },
    {
      name: 'init',
      description: 'Initialize conda for shell interaction',
      options: [
        { name: ['-d', '--dry-run'], description: 'Dry run' },
        { name: '--json', description: 'Output as JSON' },
        { name: ['-q', '--quiet'], description: 'Quiet mode' },
        { name: ['-v', '--verbose'], description: 'Verbose mode' },
        { name: '--all', description: 'Initialize for all shells' },
        { name: '--reverse', description: 'Undo conda init' },
        { name: '--user', description: 'User-level initialization' },
        { name: '--no-user', description: 'System-level initialization' },
        { name: '--system', description: 'System-level initialization' },
      ],
      args: {
        name: 'shell',
        description: 'Shell to initialize',
        isOptional: true,
        isVariadic: true,
        suggestions: [
          { name: 'bash', description: 'Bash shell' },
          { name: 'zsh', description: 'Zsh shell' },
          { name: 'fish', description: 'Fish shell' },
          { name: 'tcsh', description: 'Tcsh shell' },
          { name: 'xonsh', description: 'Xonsh shell' },
          { name: 'powershell', description: 'PowerShell' },
          { name: 'cmd.exe', description: 'Windows CMD' },
        ],
      },
    },
    {
      name: 'config',
      description: 'Modify configuration values',
      options: [
        { name: '--system', description: 'System configuration file' },
        { name: '--env', description: 'Environment configuration file' },
        { name: '--file', description: 'Configuration file', args: { name: 'file', template: 'filepaths' } },
        { name: '--show', description: 'Show configuration' },
        { name: '--show-sources', description: 'Show configuration sources' },
        { name: '--validate', description: 'Validate configuration' },
        { name: '--describe', description: 'Describe configuration options' },
        { name: '--write-default', description: 'Write default configuration' },
        { name: '--get', description: 'Get a configuration value', args: { name: 'key' } },
        { name: '--append', description: 'Append to a list key', args: { name: 'key=value' } },
        { name: '--prepend', description: 'Prepend to a list key', args: { name: 'key=value' } },
        { name: '--add', description: 'Alias for prepend', args: { name: 'key=value' } },
        { name: '--set', description: 'Set a boolean key', args: { name: 'key=value' } },
        { name: '--remove', description: 'Remove a value from a list key', args: { name: 'key=value' } },
        { name: '--remove-key', description: 'Remove a configuration key', args: { name: 'key' } },
        { name: '--stdin', description: 'Read JSON from stdin' },
        { name: '--json', description: 'Output as JSON' },
        { name: ['-q', '--quiet'], description: 'Quiet mode' },
        { name: ['-v', '--verbose'], description: 'Verbose mode' },
      ],
    },
    {
      name: 'run',
      description: 'Run an executable in a conda environment',
      options: [
        { name: ['-n', '--name'], description: 'Environment name', args: { name: 'name' } },
        { name: ['-p', '--prefix'], description: 'Environment path', args: { name: 'path', template: 'folders' } },
        { name: '--live-stream', description: 'Stream output live' },
        { name: '--debug-wrapper-scripts', description: 'Debug wrapper scripts' },
        { name: '--cwd', description: 'Working directory', args: { name: 'path', template: 'folders' } },
        { name: '--no-capture-output', description: 'Do not capture output' },
        { name: ['-v', '--verbose'], description: 'Verbose mode' },
      ],
      args: { name: 'command', description: 'Command to run', isVariadic: true },
    },
    {
      name: 'clean',
      description: 'Remove unused packages and caches',
      options: [
        { name: ['-a', '--all'], description: 'Remove all' },
        { name: ['-i', '--index-cache'], description: 'Remove index cache' },
        { name: ['-p', '--packages'], description: 'Remove unused packages' },
        { name: ['-t', '--tarballs'], description: 'Remove tarballs' },
        { name: ['-f', '--force-pkgs-dirs'], description: 'Force removal' },
        { name: ['-c', '--tempfiles'], description: 'Remove temp files' },
        { name: ['-l', '--logfiles'], description: 'Remove log files' },
        { name: ['-d', '--dry-run'], description: 'Dry run' },
        { name: '--json', description: 'Output as JSON' },
        { name: ['-q', '--quiet'], description: 'Quiet mode' },
        { name: ['-v', '--verbose'], description: 'Verbose mode' },
        { name: ['-y', '--yes'], description: 'Do not ask for confirmation' },
      ],
    },
    {
      name: 'compare',
      description: 'Compare packages between environments',
      options: [
        { name: ['-n', '--name'], description: 'Environment name', args: { name: 'name' } },
        { name: ['-p', '--prefix'], description: 'Environment path', args: { name: 'path', template: 'folders' } },
        { name: '--json', description: 'Output as JSON' },
        { name: ['-q', '--quiet'], description: 'Quiet mode' },
        { name: ['-v', '--verbose'], description: 'Verbose mode' },
      ],
      args: { name: 'file', description: 'File to compare', template: 'filepaths' },
    },
    { name: 'doctor', description: 'Check for issues with conda' },
    {
      name: 'notices',
      description: 'Retrieve and display channel notices',
      options: [
        { name: ['-c', '--channel'], description: 'Channel', args: { name: 'channel' } },
        { name: ['-q', '--quiet'], description: 'Quiet mode' },
        { name: ['-v', '--verbose'], description: 'Verbose mode' },
      ],
    },
    {
      name: 'pack',
      description: 'Create a conda pack archive',
    },
    {
      name: 'rename',
      description: 'Rename an existing environment',
      options: [
        { name: ['-n', '--name'], description: 'Environment to rename', args: { name: 'name' } },
        { name: ['-p', '--prefix'], description: 'Environment path', args: { name: 'path', template: 'folders' } },
        { name: ['-d', '--dry-run'], description: 'Dry run' },
        { name: '--force', description: 'Force rename' },
        { name: ['-y', '--yes'], description: 'Do not ask for confirmation' },
      ],
      args: { name: 'destination', description: 'New name or path' },
    },
    { name: 'help', description: 'Show help', args: { name: 'command', isOptional: true } },
  ],
  options: [
    { name: ['-h', '--help'], description: 'Show help' },
    { name: ['-V', '--version'], description: 'Show version' },
  ],
};
