// create-completion-spec completion spec for CLIFlow
// Auto-converted from Fig.io spec: https://github.com/withfig/autocomplete
// License: MIT

import { CompletionSpec, Subcommand, Option, Suggestion } from '../types.js';

// Autogenerated by @fig/complete-commander
const completionSpec= {
  name: "create-completion-spec",
  description: "Setup fig folder and create spec with the given name",
  subcommands: [
    {
      name: "help",
      description: "Display help for command",
      priority: 49,
      args: { name: "command", isOptional: true }
    }
  ],
  options: [
    {
      name: "--here",
      description: "Set if the spec should be created in the current folder"
    },
    {
      name: ["-h", "--help"],
      description: "Display help for command",
      priority: 49
    }
  ],
  args: { name: "name" }
};
export default completionSpec;
