// deno - Deno JavaScript/TypeScript runtime
import { CompletionSpec } from '../types.js';

const permissionFlags = [
  { name: '-A', description: 'Allow all permissions' },
  { name: '--allow-all', description: 'Allow all permissions' },
  { name: '--allow-env', description: 'Allow environment access', args: { name: 'vars', isOptional: true } },
  { name: '--allow-ffi', description: 'Allow FFI', args: { name: 'paths', isOptional: true } },
  { name: '--allow-hrtime', description: 'Allow high resolution time' },
  { name: '--allow-net', description: 'Allow network access', args: { name: 'hosts', isOptional: true } },
  { name: '--allow-read', description: 'Allow file read', args: { name: 'paths', isOptional: true } },
  { name: '--allow-run', description: 'Allow running subprocesses', args: { name: 'programs', isOptional: true } },
  { name: '--allow-sys', description: 'Allow system info access', args: { name: 'apis', isOptional: true } },
  { name: '--allow-write', description: 'Allow file write', args: { name: 'paths', isOptional: true } },
  { name: '--deny-env', description: 'Deny environment access', args: { name: 'vars', isOptional: true } },
  { name: '--deny-ffi', description: 'Deny FFI', args: { name: 'paths', isOptional: true } },
  { name: '--deny-hrtime', description: 'Deny high resolution time' },
  { name: '--deny-net', description: 'Deny network access', args: { name: 'hosts', isOptional: true } },
  { name: '--deny-read', description: 'Deny file read', args: { name: 'paths', isOptional: true } },
  { name: '--deny-run', description: 'Deny running subprocesses', args: { name: 'programs', isOptional: true } },
  { name: '--deny-sys', description: 'Deny system info access', args: { name: 'apis', isOptional: true } },
  { name: '--deny-write', description: 'Deny file write', args: { name: 'paths', isOptional: true } },
  { name: '--no-prompt', description: 'Deny all permissions without prompting' },
];

const commonOptions = [
  { name: ['-h', '--help'], description: 'Print help' },
  { name: ['-q', '--quiet'], description: 'Suppress output' },
  { name: '--unstable', description: 'Enable unstable features' },
  { name: '--unstable-bare-node-builtins', description: 'Enable bare Node.js builtins' },
  { name: '--unstable-byonm', description: 'Enable bring-your-own node_modules' },
  { name: '--unstable-cron', description: 'Enable Deno.cron' },
  { name: '--unstable-ffi', description: 'Enable unstable FFI APIs' },
  { name: '--unstable-fs', description: 'Enable unstable file system APIs' },
  { name: '--unstable-http', description: 'Enable unstable HTTP APIs' },
  { name: '--unstable-kv', description: 'Enable Deno KV' },
  { name: '--unstable-net', description: 'Enable unstable net APIs' },
  { name: '--unstable-sloppy-imports', description: 'Enable sloppy imports' },
  { name: '--unstable-temporal', description: 'Enable Temporal API' },
  { name: '--unstable-webgpu', description: 'Enable WebGPU API' },
  { name: '--unstable-worker-options', description: 'Enable unstable Worker options' },
];

const typeCheckOptions = [
  { name: '--check', description: 'Type-check modules', args: { name: 'scope', isOptional: true, suggestions: [{ name: 'all', description: 'Type-check all modules' }] } },
  { name: '--no-check', description: 'Skip type checking', args: { name: 'scope', isOptional: true } },
];

const configOptions = [
  { name: ['-c', '--config'], description: 'Config file', args: { name: 'file', template: 'filepaths' } },
  { name: '--no-config', description: 'Disable config file' },
  { name: '--import-map', description: 'Import map file', args: { name: 'file', template: 'filepaths' } },
  { name: '--no-remote', description: 'Don\'t download remote modules' },
  { name: '--no-npm', description: 'Don\'t resolve npm modules' },
  { name: '--node-modules-dir', description: 'Create local node_modules', args: { name: 'bool', isOptional: true, suggestions: [{ name: 'true' }, { name: 'false' }] } },
  { name: '--vendor', description: 'Vendor remote modules', args: { name: 'bool', isOptional: true, suggestions: [{ name: 'true' }, { name: 'false' }] } },
  { name: '--lock', description: 'Lock file', args: { name: 'file', template: 'filepaths' } },
  { name: '--no-lock', description: 'Disable lock file' },
  { name: '--lock-write', description: 'Write lock file' },
  { name: '--frozen', description: 'Error on out-of-date lock file', args: { name: 'bool', isOptional: true, suggestions: [{ name: 'true' }, { name: 'false' }] } },
  { name: '--cached-only', description: 'Require cached modules' },
  { name: '--cert', description: 'Load certificate authority', args: { name: 'file', template: 'filepaths' } },
  { name: '--seed', description: 'Random seed', args: { name: 'seed' } },
  { name: '--location', description: 'Location URL', args: { name: 'url' } },
  { name: '--v8-flags', description: 'V8 flags', args: { name: 'flags' } },
];

const inspectorOptions = [
  { name: '--inspect', description: 'Activate inspector', args: { name: 'host:port', isOptional: true } },
  { name: '--inspect-brk', description: 'Activate inspector and break', args: { name: 'host:port', isOptional: true } },
  { name: '--inspect-wait', description: 'Activate inspector and wait', args: { name: 'host:port', isOptional: true } },
];

export const denoSpec: CompletionSpec = {
  name: 'deno',
  description: 'A modern runtime for JavaScript and TypeScript',
  options: [
    ...commonOptions,
    { name: ['-V', '--version'], description: 'Print version' },
    { name: '--log-level', description: 'Log level', args: { name: 'level', suggestions: [{ name: 'debug' }, { name: 'info' }] } },
  ],
  subcommands: [
    {
      name: 'run',
      description: 'Run a JavaScript or TypeScript program',
      options: [
        ...commonOptions,
        ...permissionFlags,
        ...typeCheckOptions,
        ...configOptions,
        ...inspectorOptions,
        { name: '--watch', description: 'Watch for file changes', args: { name: 'paths', isOptional: true } },
        { name: '--watch-exclude', description: 'Exclude paths from watch', args: { name: 'paths' } },
        { name: '--no-clear-screen', description: 'Don\'t clear screen on rebuild' },
        { name: '--ext', description: 'Content type', args: { name: 'ext', suggestions: [{ name: 'ts' }, { name: 'tsx' }, { name: 'js' }, { name: 'jsx' }] } },
        { name: '--env', description: 'Load env file', args: { name: 'file', template: 'filepaths', isOptional: true } },
        { name: '--reload', description: 'Reload source code cache', args: { name: 'modules', isOptional: true } },
        { name: ['-r', '--reload'], description: 'Reload source code cache', args: { name: 'modules', isOptional: true } },
      ],
      args: [{ name: 'script', description: 'Script to run', template: 'filepaths' }, { name: 'args', description: 'Script arguments', isOptional: true, isVariadic: true }],
    },
    {
      name: 'serve',
      description: 'Run a server',
      options: [
        ...commonOptions,
        ...permissionFlags,
        ...typeCheckOptions,
        ...configOptions,
        ...inspectorOptions,
        { name: '--port', description: 'Port', args: { name: 'port' } },
        { name: '--host', description: 'Host', args: { name: 'host' } },
        { name: '--watch', description: 'Watch for file changes', args: { name: 'paths', isOptional: true } },
        { name: '--reload', description: 'Reload source code cache', args: { name: 'modules', isOptional: true } },
      ],
      args: [{ name: 'script', description: 'Script to run', template: 'filepaths' }, { name: 'args', description: 'Script arguments', isOptional: true, isVariadic: true }],
    },
    {
      name: 'test',
      description: 'Run tests',
      options: [
        ...commonOptions,
        ...permissionFlags,
        ...typeCheckOptions,
        ...configOptions,
        ...inspectorOptions,
        { name: '--ignore', description: 'Ignore files', args: { name: 'paths' } },
        { name: '--no-run', description: 'Cache test modules only' },
        { name: '--doc', description: 'Type-check code in JSDoc' },
        { name: '--fail-fast', description: 'Stop on first failure', args: { name: 'count', isOptional: true } },
        { name: '--filter', description: 'Filter tests', args: { name: 'pattern' } },
        { name: '--shuffle', description: 'Shuffle test order', args: { name: 'seed', isOptional: true } },
        { name: '--coverage', description: 'Coverage directory', args: { name: 'dir', template: 'folders', isOptional: true } },
        { name: '--parallel', description: 'Run tests in parallel' },
        { name: '--jobs', description: 'Number of parallel workers', args: { name: 'count' } },
        { name: '--trace-leaks', description: 'Trace async operation leaks' },
        { name: '--reporter', description: 'Test reporter', args: { name: 'reporter', suggestions: [{ name: 'pretty' }, { name: 'dot' }, { name: 'junit' }, { name: 'tap' }] } },
        { name: '--junit-path', description: 'JUnit report path', args: { name: 'path', template: 'filepaths' } },
        { name: '--hide-stacktraces', description: 'Hide stack traces' },
        { name: '--watch', description: 'Watch for file changes' },
        { name: '--reload', description: 'Reload source code cache', args: { name: 'modules', isOptional: true } },
        { name: '--clean', description: 'Empty coverage directory' },
      ],
      args: { name: 'files', description: 'Test files', template: 'filepaths', isOptional: true, isVariadic: true },
    },
    {
      name: 'bench',
      description: 'Run benchmarks',
      options: [
        ...commonOptions,
        ...permissionFlags,
        ...typeCheckOptions,
        ...configOptions,
        ...inspectorOptions,
        { name: '--ignore', description: 'Ignore files', args: { name: 'paths' } },
        { name: '--filter', description: 'Filter benchmarks', args: { name: 'pattern' } },
        { name: '--no-run', description: 'Cache benchmark modules only' },
        { name: '--json', description: 'Output JSON' },
        { name: '--watch', description: 'Watch for file changes' },
        { name: '--reload', description: 'Reload source code cache', args: { name: 'modules', isOptional: true } },
      ],
      args: { name: 'files', description: 'Benchmark files', template: 'filepaths', isOptional: true, isVariadic: true },
    },
    {
      name: 'compile',
      description: 'Compile to standalone executable',
      options: [
        ...commonOptions,
        ...permissionFlags,
        ...typeCheckOptions,
        ...configOptions,
        { name: ['-o', '--output'], description: 'Output file', args: { name: 'file', template: 'filepaths' } },
        { name: '--target', description: 'Target OS/arch', args: { name: 'target', suggestions: [{ name: 'x86_64-unknown-linux-gnu' }, { name: 'x86_64-pc-windows-msvc' }, { name: 'x86_64-apple-darwin' }, { name: 'aarch64-apple-darwin' }] } },
        { name: '--include', description: 'Include files', args: { name: 'files' } },
        { name: '--no-terminal', description: 'No terminal on Windows' },
        { name: '--icon', description: 'Windows icon', args: { name: 'file', template: 'filepaths' } },
        { name: '--ext', description: 'Content type', args: { name: 'ext', suggestions: [{ name: 'ts' }, { name: 'tsx' }, { name: 'js' }, { name: 'jsx' }] } },
        { name: '--reload', description: 'Reload source code cache', args: { name: 'modules', isOptional: true } },
      ],
      args: [{ name: 'script', description: 'Script to compile', template: 'filepaths' }, { name: 'args', description: 'Script arguments', isOptional: true, isVariadic: true }],
    },
    {
      name: 'bundle',
      description: 'Bundle module and dependencies (deprecated)',
      options: [
        ...commonOptions,
        ...typeCheckOptions,
        ...configOptions,
        { name: '--ext', description: 'Content type', args: { name: 'ext' } },
        { name: '--watch', description: 'Watch for file changes' },
        { name: '--reload', description: 'Reload source code cache', args: { name: 'modules', isOptional: true } },
      ],
      args: [{ name: 'source', description: 'Source module', template: 'filepaths' }, { name: 'output', description: 'Output file', template: 'filepaths', isOptional: true }],
    },
    {
      name: 'cache',
      description: 'Cache dependencies',
      options: [
        ...commonOptions,
        ...typeCheckOptions,
        ...configOptions,
        { name: '--reload', description: 'Reload source code cache', args: { name: 'modules', isOptional: true } },
      ],
      args: { name: 'file', description: 'Module files', template: 'filepaths', isVariadic: true },
    },
    {
      name: 'check',
      description: 'Type-check modules',
      options: [
        ...commonOptions,
        ...configOptions,
        { name: '--all', description: 'Type-check all modules' },
        { name: '--reload', description: 'Reload source code cache', args: { name: 'modules', isOptional: true } },
      ],
      args: { name: 'file', description: 'Module files', template: 'filepaths', isVariadic: true },
    },
    {
      name: 'fmt',
      description: 'Format source files',
      options: [
        ...commonOptions,
        { name: ['-c', '--config'], description: 'Config file', args: { name: 'file', template: 'filepaths' } },
        { name: '--no-config', description: 'Disable config file' },
        { name: '--check', description: 'Check formatting' },
        { name: '--ext', description: 'File extension', args: { name: 'ext', suggestions: [{ name: 'ts' }, { name: 'tsx' }, { name: 'js' }, { name: 'jsx' }, { name: 'md' }, { name: 'json' }, { name: 'jsonc' }] } },
        { name: '--ignore', description: 'Ignore files', args: { name: 'paths' } },
        { name: '--watch', description: 'Watch for file changes' },
        { name: '--use-tabs', description: 'Use tabs', args: { name: 'bool', isOptional: true, suggestions: [{ name: 'true' }, { name: 'false' }] } },
        { name: '--line-width', description: 'Line width', args: { name: 'width' } },
        { name: '--indent-width', description: 'Indent width', args: { name: 'width' } },
        { name: '--single-quote', description: 'Use single quotes', args: { name: 'bool', isOptional: true, suggestions: [{ name: 'true' }, { name: 'false' }] } },
        { name: '--prose-wrap', description: 'Prose wrap', args: { name: 'mode', suggestions: [{ name: 'always' }, { name: 'never' }, { name: 'preserve' }] } },
        { name: '--no-semicolons', description: 'No semicolons', args: { name: 'bool', isOptional: true, suggestions: [{ name: 'true' }, { name: 'false' }] } },
      ],
      args: { name: 'files', description: 'Files to format', template: 'filepaths', isOptional: true, isVariadic: true },
    },
    {
      name: 'lint',
      description: 'Lint source files',
      options: [
        ...commonOptions,
        { name: ['-c', '--config'], description: 'Config file', args: { name: 'file', template: 'filepaths' } },
        { name: '--no-config', description: 'Disable config file' },
        { name: '--ignore', description: 'Ignore files', args: { name: 'paths' } },
        { name: '--rules', description: 'Show available rules' },
        { name: '--rules-tags', description: 'Filter by tags', args: { name: 'tags' } },
        { name: '--rules-include', description: 'Include rules', args: { name: 'rules' } },
        { name: '--rules-exclude', description: 'Exclude rules', args: { name: 'rules' } },
        { name: '--json', description: 'Output JSON' },
        { name: '--compact', description: 'Compact output' },
        { name: '--watch', description: 'Watch for file changes' },
        { name: '--fix', description: 'Auto-fix issues' },
      ],
      args: { name: 'files', description: 'Files to lint', template: 'filepaths', isOptional: true, isVariadic: true },
    },
    {
      name: 'doc',
      description: 'Show documentation',
      options: [
        ...commonOptions,
        { name: '--json', description: 'Output JSON' },
        { name: '--html', description: 'Output HTML' },
        { name: '--name', description: 'Library name', args: { name: 'name' } },
        { name: '--category-docs', description: 'Category docs path', args: { name: 'path', template: 'filepaths' } },
        { name: '--symbol-redirect-map', description: 'Symbol redirect map', args: { name: 'path', template: 'filepaths' } },
        { name: '--strip-trailing-html', description: 'Strip trailing .html' },
        { name: '--default-symbol-map', description: 'Default symbol map', args: { name: 'path', template: 'filepaths' } },
        { name: '--output', description: 'Output directory', args: { name: 'dir', template: 'folders' } },
        { name: '--private', description: 'Show private symbols' },
        { name: '--filter', description: 'Filter paths', args: { name: 'filter' } },
        { name: '--lint', description: 'Check documentation' },
        { name: '--reload', description: 'Reload source code cache', args: { name: 'modules', isOptional: true } },
      ],
      args: [{ name: 'source', description: 'Source module', template: 'filepaths', isOptional: true }, { name: 'filter', description: 'Symbol filter', isOptional: true }],
    },
    {
      name: 'info',
      description: 'Show module information',
      options: [
        ...commonOptions,
        ...configOptions,
        { name: '--json', description: 'Output JSON' },
        { name: '--reload', description: 'Reload source code cache', args: { name: 'modules', isOptional: true } },
      ],
      args: { name: 'file', description: 'Module file', template: 'filepaths', isOptional: true },
    },
    {
      name: 'eval',
      description: 'Evaluate JavaScript',
      options: [
        ...commonOptions,
        ...permissionFlags,
        ...typeCheckOptions,
        ...configOptions,
        ...inspectorOptions,
        { name: '--ext', description: 'Content type', args: { name: 'ext', suggestions: [{ name: 'ts' }, { name: 'tsx' }, { name: 'js' }, { name: 'jsx' }] } },
        { name: ['-p', '--print'], description: 'Print result' },
        { name: '--env', description: 'Load env file', args: { name: 'file', template: 'filepaths', isOptional: true } },
      ],
      args: { name: 'code', description: 'Code to evaluate' },
    },
    {
      name: 'repl',
      description: 'Start interactive REPL',
      options: [
        ...commonOptions,
        ...permissionFlags,
        ...typeCheckOptions,
        ...configOptions,
        ...inspectorOptions,
        { name: '--eval', description: 'Evaluate code on startup', args: { name: 'code' } },
        { name: '--eval-file', description: 'Evaluate files on startup', args: { name: 'files' } },
        { name: '--env', description: 'Load env file', args: { name: 'file', template: 'filepaths', isOptional: true } },
      ],
    },
    {
      name: 'install',
      description: 'Install script as executable',
      options: [
        ...commonOptions,
        ...permissionFlags,
        ...typeCheckOptions,
        ...configOptions,
        { name: ['-n', '--name'], description: 'Executable name', args: { name: 'name' } },
        { name: '--root', description: 'Installation root', args: { name: 'dir', template: 'folders' } },
        { name: ['-f', '--force'], description: 'Force overwrite' },
        { name: ['-g', '--global'], description: 'Install globally' },
        { name: '--reload', description: 'Reload source code cache', args: { name: 'modules', isOptional: true } },
      ],
      args: [{ name: 'script', description: 'Script to install', template: 'filepaths', isOptional: true }, { name: 'args', description: 'Script arguments', isOptional: true, isVariadic: true }],
    },
    {
      name: 'uninstall',
      description: 'Uninstall a script',
      options: [
        ...commonOptions,
        { name: '--root', description: 'Installation root', args: { name: 'dir', template: 'folders' } },
        { name: ['-g', '--global'], description: 'Uninstall globally' },
      ],
      args: { name: 'name', description: 'Script name' },
    },
    {
      name: 'add',
      description: 'Add dependencies',
      options: [
        ...commonOptions,
        { name: '--dev', description: 'Add as dev dependency' },
      ],
      args: { name: 'packages', description: 'Packages to add', isVariadic: true },
    },
    {
      name: 'remove',
      description: 'Remove dependencies',
      options: commonOptions,
      args: { name: 'packages', description: 'Packages to remove', isVariadic: true },
    },
    {
      name: 'task',
      description: 'Run a task',
      options: [
        ...commonOptions,
        { name: ['-c', '--config'], description: 'Config file', args: { name: 'file', template: 'filepaths' } },
        { name: '--cwd', description: 'Working directory', args: { name: 'dir', template: 'folders' } },
      ],
      args: [{ name: 'task', description: 'Task name', isOptional: true }, { name: 'args', description: 'Task arguments', isOptional: true, isVariadic: true }],
    },
    {
      name: 'init',
      description: 'Initialize a new project',
      options: commonOptions,
      args: { name: 'dir', description: 'Project directory', template: 'folders', isOptional: true },
    },
    {
      name: 'jupyter',
      description: 'Deno kernel for Jupyter notebooks',
      options: [
        ...commonOptions,
        { name: '--install', description: 'Install kernel' },
        { name: '--conn', description: 'Connection file', args: { name: 'file', template: 'filepaths' } },
      ],
    },
    {
      name: 'coverage',
      description: 'Report test coverage',
      options: [
        ...commonOptions,
        { name: '--ignore', description: 'Ignore files', args: { name: 'paths' } },
        { name: '--include', description: 'Include files', args: { name: 'patterns' } },
        { name: '--exclude', description: 'Exclude files', args: { name: 'patterns' } },
        { name: '--lcov', description: 'Output lcov format' },
        { name: '--html', description: 'Output HTML' },
        { name: '--detailed', description: 'Detailed coverage' },
        { name: '--output', description: 'Output path', args: { name: 'path', template: 'filepaths' } },
      ],
      args: { name: 'files', description: 'Coverage files', template: 'filepaths', isOptional: true, isVariadic: true },
    },
    {
      name: 'publish',
      description: 'Publish to JSR',
      options: [
        ...commonOptions,
        { name: '--token', description: 'API token', args: { name: 'token' } },
        { name: ['-c', '--config'], description: 'Config file', args: { name: 'file', template: 'filepaths' } },
        { name: '--no-config', description: 'Disable config file' },
        { name: '--dry-run', description: 'Perform dry run' },
        { name: '--allow-slow-types', description: 'Allow slow types' },
        { name: '--allow-dirty', description: 'Allow dirty working directory' },
        { name: '--no-provenance', description: 'Disable provenance' },
      ],
    },
    {
      name: 'upgrade',
      description: 'Upgrade Deno',
      options: [
        ...commonOptions,
        { name: '--version', description: 'Target version', args: { name: 'version' } },
        { name: '--output', description: 'Output path', args: { name: 'path', template: 'filepaths' } },
        { name: '--dry-run', description: 'Perform dry run' },
        { name: ['-f', '--force'], description: 'Force upgrade' },
        { name: '--canary', description: 'Upgrade to canary' },
        { name: '--rc', description: 'Upgrade to RC' },
      ],
    },
    { name: 'completions', description: 'Generate shell completions', args: { name: 'shell', suggestions: [{ name: 'bash' }, { name: 'fish' }, { name: 'powershell' }, { name: 'zsh' }, { name: 'fig' }] } },
    {
      name: 'types',
      description: 'Print runtime TypeScript declarations',
      options: commonOptions,
    },
    {
      name: 'vendor',
      description: 'Vendor remote modules',
      options: [
        ...commonOptions,
        ...configOptions,
        { name: ['-o', '--output'], description: 'Output directory', args: { name: 'dir', template: 'folders' } },
        { name: ['-f', '--force'], description: 'Force overwrite' },
        { name: '--reload', description: 'Reload source code cache', args: { name: 'modules', isOptional: true } },
      ],
      args: { name: 'specifiers', description: 'Module specifiers', template: 'filepaths', isVariadic: true },
    },
    {
      name: 'lsp',
      description: 'Start language server',
      options: commonOptions,
    },
    { name: 'help', description: 'Show help', args: { name: 'command', isOptional: true } },
  ],
};
