// docker-compose - Define and run multi-container Docker applications
import { CompletionSpec, Suggestion } from '../types.js';

export const dockerComposeSpec: CompletionSpec = {
  name: 'docker-compose',
  description: 'Define and run multi-container Docker applications',
  options: [
    { name: ['-f', '--file'], description: 'Specify compose file', args: { name: 'file', template: 'filepaths' } },
    { name: ['-p', '--project-name'], description: 'Specify project name', args: { name: 'name' } },
    { name: '--profile', description: 'Specify profile to enable', args: { name: 'profile' } },
    { name: ['-c', '--context'], description: 'Docker context', args: { name: 'context' } },
    { name: '--verbose', description: 'Verbose output' },
    { name: '--log-level', description: 'Set log level', args: {
      name: 'level',
      suggestions: [
        { name: 'DEBUG' }, { name: 'INFO' }, { name: 'WARNING' }, { name: 'ERROR' }, { name: 'CRITICAL' },
      ],
    }},
    { name: '--ansi', description: 'Control ANSI output', args: { name: 'when', suggestions: [{ name: 'never' }, { name: 'always' }, { name: 'auto' }] } },
    { name: ['-v', '--version'], description: 'Print version' },
    { name: '--project-directory', description: 'Project directory', args: { name: 'dir', template: 'folders' } },
    { name: '--env-file', description: 'Environment file', args: { name: 'file', template: 'filepaths' } },
  ],
  subcommands: [
    {
      name: 'up',
      description: 'Create and start containers',
      options: [
        { name: ['-d', '--detach'], description: 'Detached mode' },
        { name: '--no-color', description: 'Monochrome output' },
        { name: '--quiet-pull', description: 'Pull without progress' },
        { name: '--no-deps', description: 'Dont start linked services' },
        { name: '--force-recreate', description: 'Recreate containers' },
        { name: '--no-recreate', description: 'Dont recreate if exists' },
        { name: '--no-build', description: 'Dont build' },
        { name: '--build', description: 'Build before starting' },
        { name: '--abort-on-container-exit', description: 'Stop all if any stops' },
        { name: ['-t', '--timeout'], description: 'Shutdown timeout', args: { name: 'seconds' } },
        { name: ['-V', '--renew-anon-volumes'], description: 'Recreate volumes' },
        { name: '--remove-orphans', description: 'Remove orphans' },
        { name: '--scale', description: 'Scale service', args: { name: 'service=num' } },
        { name: '--wait', description: 'Wait for healthy' },
      ],
      args: { name: 'service', isOptional: true, isVariadic: true },
    },
    {
      name: 'down',
      description: 'Stop and remove containers',
      options: [
        { name: '--rmi', description: 'Remove images', args: { name: 'type', suggestions: [{ name: 'all' }, { name: 'local' }] } },
        { name: ['-v', '--volumes'], description: 'Remove volumes' },
        { name: '--remove-orphans', description: 'Remove orphans' },
        { name: ['-t', '--timeout'], description: 'Timeout', args: { name: 'seconds' } },
      ],
    },
    { name: 'start', description: 'Start services', args: { name: 'service', isOptional: true, isVariadic: true } },
    { name: 'stop', description: 'Stop services', options: [{ name: ['-t', '--timeout'], args: { name: 'seconds' } }], args: { name: 'service', isOptional: true, isVariadic: true } },
    { name: 'restart', description: 'Restart services', options: [{ name: ['-t', '--timeout'], args: { name: 'seconds' } }], args: { name: 'service', isOptional: true, isVariadic: true } },
    {
      name: 'build',
      description: 'Build services',
      options: [
        { name: '--no-cache', description: 'No cache' },
        { name: '--pull', description: 'Always pull' },
        { name: '--build-arg', description: 'Build arg', args: { name: 'key=val' } },
        { name: ['-q', '--quiet'], description: 'Quiet' },
        { name: '--parallel', description: 'Parallel build' },
      ],
      args: { name: 'service', isOptional: true, isVariadic: true },
    },
    { name: 'pull', description: 'Pull images', options: [{ name: ['-q', '--quiet'] }, { name: '--include-deps' }], args: { name: 'service', isOptional: true, isVariadic: true } },
    { name: 'push', description: 'Push images', args: { name: 'service', isOptional: true, isVariadic: true } },
    {
      name: 'logs',
      description: 'View logs',
      options: [
        { name: ['-f', '--follow'], description: 'Follow' },
        { name: ['-t', '--timestamps'], description: 'Timestamps' },
        { name: '--tail', description: 'Lines', args: { name: 'lines' } },
        { name: '--since', description: 'Since', args: { name: 'time' } },
      ],
      args: { name: 'service', isOptional: true, isVariadic: true },
    },
    {
      name: 'ps',
      description: 'List containers',
      options: [
        { name: ['-q', '--quiet'], description: 'IDs only' },
        { name: '--services', description: 'Services' },
        { name: ['-a', '--all'], description: 'All' },
        { name: '--format', description: 'Format', args: { name: 'format', suggestions: [{ name: 'table' }, { name: 'json' }] } },
      ],
      args: { name: 'service', isOptional: true, isVariadic: true },
    },
    {
      name: 'exec',
      description: 'Execute command',
      options: [
        { name: ['-d', '--detach'], description: 'Detach' },
        { name: ['-u', '--user'], description: 'User', args: { name: 'user' } },
        { name: '-T', description: 'No TTY' },
        { name: ['-e', '--env'], description: 'Env var', args: { name: 'key=val' } },
        { name: ['-w', '--workdir'], description: 'Workdir', args: { name: 'dir' } },
      ],
      args: [{ name: 'service' }, { name: 'command', isVariadic: true }],
    },
    {
      name: 'run',
      description: 'Run one-off command',
      options: [
        { name: ['-d', '--detach'], description: 'Detach' },
        { name: '--name', description: 'Name', args: { name: 'name' } },
        { name: '--entrypoint', description: 'Entrypoint', args: { name: 'cmd' } },
        { name: ['-e', '--env'], description: 'Env', args: { name: 'key=val' } },
        { name: ['-u', '--user'], description: 'User', args: { name: 'user' } },
        { name: '--no-deps', description: 'No deps' },
        { name: '--rm', description: 'Remove after' },
        { name: ['-v', '--volume'], description: 'Volume', args: { name: 'vol' } },
        { name: '-T', description: 'No TTY' },
      ],
      args: [{ name: 'service' }, { name: 'command', isOptional: true, isVariadic: true }],
    },
    { name: 'rm', description: 'Remove containers', options: [{ name: ['-f', '--force'] }, { name: ['-s', '--stop'] }, { name: ['-v', '--volumes'] }], args: { name: 'service', isOptional: true, isVariadic: true } },
    { name: 'kill', description: 'Kill containers', options: [{ name: ['-s', '--signal'], args: { name: 'signal' } }], args: { name: 'service', isOptional: true, isVariadic: true } },
    { name: 'pause', description: 'Pause services', args: { name: 'service', isOptional: true, isVariadic: true } },
    { name: 'unpause', description: 'Unpause services', args: { name: 'service', isOptional: true, isVariadic: true } },
    { name: 'config', description: 'Validate compose file', options: [{ name: ['-q', '--quiet'] }, { name: '--services' }, { name: '--volumes' }] },
    { name: 'images', description: 'List images', options: [{ name: ['-q', '--quiet'] }], args: { name: 'service', isOptional: true, isVariadic: true } },
    { name: 'events', description: 'Stream events', options: [{ name: '--json' }], args: { name: 'service', isOptional: true, isVariadic: true } },
    { name: 'top', description: 'Display processes', args: { name: 'service', isOptional: true, isVariadic: true } },
    { name: 'port', description: 'Print port', options: [{ name: '--protocol', args: { name: 'proto', suggestions: [{ name: 'tcp' }, { name: 'udp' }] } }], args: [{ name: 'service' }, { name: 'port' }] },
    { name: 'scale', description: 'Scale services', args: { name: 'service=num', isVariadic: true } },
    { name: 'create', description: 'Create containers', options: [{ name: '--force-recreate' }, { name: '--no-recreate' }, { name: '--build' }], args: { name: 'service', isOptional: true, isVariadic: true } },
    { name: 'version', description: 'Show version', options: [{ name: '--short' }] },
    { name: 'help', description: 'Get help', args: { name: 'command', isOptional: true } },
    { name: 'ls', description: 'List projects', options: [{ name: ['-q', '--quiet'] }, { name: ['-a', '--all'] }] },
    { name: 'cp', description: 'Copy files', args: [{ name: 'source' }, { name: 'destination' }] },
    { name: 'wait', description: 'Wait for containers', args: { name: 'service', isOptional: true, isVariadic: true } },
    { name: 'watch', description: 'Watch and rebuild', args: { name: 'service', isOptional: true, isVariadic: true } },
  ],
};
