// dotnet - .NET CLI
import { CompletionSpec } from '../types.js';

export const dotnetSpec: CompletionSpec = {
  name: 'dotnet',
  description: '.NET CLI',
  options: [
    { name: ['-d', '--diagnostics'], description: 'Enable diagnostic output' },
    { name: ['-h', '--help'], description: 'Show help' },
    { name: '--info', description: 'Display .NET information' },
    { name: '--list-runtimes', description: 'List installed runtimes' },
    { name: '--list-sdks', description: 'List installed SDKs' },
    { name: '--version', description: 'Display .NET SDK version' },
  ],
  subcommands: [
    {
      name: 'new',
      description: 'Create a new .NET project or file',
      options: [
        { name: ['-n', '--name'], description: 'Project name', args: { name: 'name' } },
        { name: ['-o', '--output'], description: 'Output directory', args: { name: 'dir', template: 'folders' } },
        { name: ['-f', '--framework'], description: 'Target framework', args: { name: 'framework', suggestions: [{ name: 'net8.0' }, { name: 'net7.0' }, { name: 'net6.0' }, { name: 'netstandard2.1' }, { name: 'netstandard2.0' }] } },
        { name: '--dry-run', description: 'Show what would happen' },
        { name: '--force', description: 'Force content generation' },
        { name: '--no-update-check', description: 'Disable template update check' },
        { name: '--project', description: 'Project to apply to', args: { name: 'project', template: 'filepaths' } },
      ],
      args: {
        name: 'template',
        description: 'Template to create',
        suggestions: [
          { name: 'console', description: 'Console application' },
          { name: 'classlib', description: 'Class library' },
          { name: 'webapi', description: 'ASP.NET Core Web API' },
          { name: 'web', description: 'ASP.NET Core empty' },
          { name: 'mvc', description: 'ASP.NET Core MVC' },
          { name: 'webapp', description: 'ASP.NET Core Razor Pages' },
          { name: 'blazorserver', description: 'Blazor Server app' },
          { name: 'blazorwasm', description: 'Blazor WebAssembly app' },
          { name: 'blazor', description: 'Blazor Web app' },
          { name: 'grpc', description: 'ASP.NET Core gRPC' },
          { name: 'worker', description: 'Worker Service' },
          { name: 'mstest', description: 'MSTest project' },
          { name: 'nunit', description: 'NUnit project' },
          { name: 'xunit', description: 'xUnit project' },
          { name: 'razorclasslib', description: 'Razor class library' },
          { name: 'gitignore', description: '.gitignore file' },
          { name: 'globaljson', description: 'global.json file' },
          { name: 'nugetconfig', description: 'NuGet config' },
          { name: 'sln', description: 'Solution file' },
          { name: 'editorconfig', description: 'EditorConfig file' },
          { name: 'tool-manifest', description: '.NET local tool manifest' },
          { name: 'maui', description: '.NET MAUI app' },
          { name: 'maui-blazor', description: '.NET MAUI Blazor app' },
          { name: 'mauilib', description: '.NET MAUI class library' },
          { name: 'winforms', description: 'Windows Forms app' },
          { name: 'wpf', description: 'WPF app' },
          { name: 'wpflib', description: 'WPF class library' },
          { name: 'wpfcustomcontrollib', description: 'WPF custom control library' },
          { name: 'wpfusercontrollib', description: 'WPF user control library' },
        ],
      },
    },
    {
      name: 'build',
      description: 'Build a .NET project',
      options: [
        { name: ['-c', '--configuration'], description: 'Build configuration', args: { name: 'config', suggestions: [{ name: 'Debug' }, { name: 'Release' }] } },
        { name: ['-f', '--framework'], description: 'Target framework', args: { name: 'framework' } },
        { name: ['-r', '--runtime'], description: 'Target runtime', args: { name: 'runtime', suggestions: [{ name: 'win-x64' }, { name: 'win-x86' }, { name: 'win-arm64' }, { name: 'linux-x64' }, { name: 'linux-arm64' }, { name: 'osx-x64' }, { name: 'osx-arm64' }] } },
        { name: ['-o', '--output'], description: 'Output directory', args: { name: 'dir', template: 'folders' } },
        { name: '--no-dependencies', description: 'Don\'t build project-to-project references' },
        { name: '--no-incremental', description: 'Disable incremental build' },
        { name: '--no-restore', description: 'Don\'t restore before building' },
        { name: '--nologo', description: 'Hide startup banner' },
        { name: '--self-contained', description: 'Publish self-contained', args: { name: 'bool', isOptional: true, suggestions: [{ name: 'true' }, { name: 'false' }] } },
        { name: ['-v', '--verbosity'], description: 'Verbosity level', args: { name: 'level', suggestions: [{ name: 'q' }, { name: 'quiet' }, { name: 'm' }, { name: 'minimal' }, { name: 'n' }, { name: 'normal' }, { name: 'd' }, { name: 'detailed' }, { name: 'diag' }, { name: 'diagnostic' }] } },
        { name: '--version-suffix', description: 'Version suffix', args: { name: 'suffix' } },
        { name: ['-p', '--property'], description: 'Set property', args: { name: 'property' } },
        { name: '--arch', description: 'Target architecture', args: { name: 'arch', suggestions: [{ name: 'x64' }, { name: 'x86' }, { name: 'arm64' }, { name: 'arm' }] } },
        { name: '--os', description: 'Target OS', args: { name: 'os', suggestions: [{ name: 'win' }, { name: 'linux' }, { name: 'osx' }] } },
        { name: '--artifacts-path', description: 'Artifacts path', args: { name: 'path', template: 'folders' } },
        { name: '--tl', description: 'Terminal logger', args: { name: 'mode', isOptional: true, suggestions: [{ name: 'auto' }, { name: 'on' }, { name: 'off' }] } },
      ],
      args: { name: 'project', description: 'Project or solution file', template: 'filepaths', isOptional: true },
    },
    {
      name: 'run',
      description: 'Run a .NET application',
      options: [
        { name: ['-c', '--configuration'], description: 'Build configuration', args: { name: 'config', suggestions: [{ name: 'Debug' }, { name: 'Release' }] } },
        { name: ['-f', '--framework'], description: 'Target framework', args: { name: 'framework' } },
        { name: ['-r', '--runtime'], description: 'Target runtime', args: { name: 'runtime' } },
        { name: ['-p', '--project'], description: 'Project file', args: { name: 'project', template: 'filepaths' } },
        { name: '--launch-profile', description: 'Launch profile', args: { name: 'profile' } },
        { name: '--no-launch-profile', description: 'Don\'t use launch profiles' },
        { name: '--no-build', description: 'Don\'t build before running' },
        { name: '--no-restore', description: 'Don\'t restore before running' },
        { name: ['-v', '--verbosity'], description: 'Verbosity level', args: { name: 'level', suggestions: [{ name: 'quiet' }, { name: 'minimal' }, { name: 'normal' }, { name: 'detailed' }, { name: 'diagnostic' }] } },
        { name: '--arch', description: 'Target architecture', args: { name: 'arch' } },
        { name: '--os', description: 'Target OS', args: { name: 'os' } },
        { name: '--property', description: 'Set property', args: { name: 'property' } },
      ],
      args: { name: 'args', description: 'Arguments to pass', isOptional: true, isVariadic: true },
    },
    {
      name: 'test',
      description: 'Run unit tests',
      options: [
        { name: ['-c', '--configuration'], description: 'Build configuration', args: { name: 'config', suggestions: [{ name: 'Debug' }, { name: 'Release' }] } },
        { name: ['-f', '--framework'], description: 'Target framework', args: { name: 'framework' } },
        { name: ['-r', '--runtime'], description: 'Target runtime', args: { name: 'runtime' } },
        { name: ['-o', '--output'], description: 'Output directory', args: { name: 'dir', template: 'folders' } },
        { name: '--filter', description: 'Filter expression', args: { name: 'filter' } },
        { name: ['-l', '--logger'], description: 'Logger', args: { name: 'logger', suggestions: [{ name: 'console' }, { name: 'trx' }, { name: 'html' }, { name: 'junit' }] } },
        { name: '--results-directory', description: 'Results directory', args: { name: 'dir', template: 'folders' } },
        { name: '--collect', description: 'Data collector', args: { name: 'collector', suggestions: [{ name: 'Code Coverage' }, { name: 'XPlat Code Coverage' }] } },
        { name: '--settings', description: 'Settings file', args: { name: 'file', template: 'filepaths' } },
        { name: '--no-build', description: 'Don\'t build before testing' },
        { name: '--no-restore', description: 'Don\'t restore before testing' },
        { name: '--blame', description: 'Run tests in blame mode' },
        { name: '--blame-crash', description: 'Collect crash dump' },
        { name: '--blame-hang', description: 'Collect hang dump' },
        { name: '--blame-hang-timeout', description: 'Hang timeout', args: { name: 'timeout' } },
        { name: ['-v', '--verbosity'], description: 'Verbosity level', args: { name: 'level', suggestions: [{ name: 'quiet' }, { name: 'minimal' }, { name: 'normal' }, { name: 'detailed' }, { name: 'diagnostic' }] } },
        { name: ['-e', '--environment'], description: 'Environment variable', args: { name: 'var' } },
        { name: ['-a', '--arch'], description: 'Target architecture', args: { name: 'arch' } },
        { name: '--os', description: 'Target OS', args: { name: 'os' } },
        { name: '--nologo', description: 'Hide logo' },
      ],
      args: { name: 'project', description: 'Project or solution file', template: 'filepaths', isOptional: true },
    },
    {
      name: 'publish',
      description: 'Publish a .NET application',
      options: [
        { name: ['-c', '--configuration'], description: 'Build configuration', args: { name: 'config', suggestions: [{ name: 'Debug' }, { name: 'Release' }] } },
        { name: ['-f', '--framework'], description: 'Target framework', args: { name: 'framework' } },
        { name: ['-r', '--runtime'], description: 'Target runtime', args: { name: 'runtime', suggestions: [{ name: 'win-x64' }, { name: 'win-x86' }, { name: 'win-arm64' }, { name: 'linux-x64' }, { name: 'linux-arm64' }, { name: 'linux-musl-x64' }, { name: 'osx-x64' }, { name: 'osx-arm64' }] } },
        { name: ['-o', '--output'], description: 'Output directory', args: { name: 'dir', template: 'folders' } },
        { name: '--self-contained', description: 'Publish self-contained', args: { name: 'bool', isOptional: true, suggestions: [{ name: 'true' }, { name: 'false' }] } },
        { name: '--no-self-contained', description: 'Framework-dependent' },
        { name: '--no-build', description: 'Don\'t build before publishing' },
        { name: '--no-restore', description: 'Don\'t restore before publishing' },
        { name: ['-v', '--verbosity'], description: 'Verbosity level', args: { name: 'level', suggestions: [{ name: 'quiet' }, { name: 'minimal' }, { name: 'normal' }, { name: 'detailed' }, { name: 'diagnostic' }] } },
        { name: '--version-suffix', description: 'Version suffix', args: { name: 'suffix' } },
        { name: ['-p', '--property'], description: 'Set property', args: { name: 'property' } },
        { name: '--arch', description: 'Target architecture', args: { name: 'arch' } },
        { name: '--os', description: 'Target OS', args: { name: 'os' } },
        { name: '--use-current-runtime', description: 'Use current runtime' },
      ],
      args: { name: 'project', description: 'Project or solution file', template: 'filepaths', isOptional: true },
    },
    {
      name: 'restore',
      description: 'Restore dependencies',
      options: [
        { name: ['-s', '--source'], description: 'NuGet source', args: { name: 'source' } },
        { name: ['-r', '--runtime'], description: 'Target runtime', args: { name: 'runtime' } },
        { name: '--packages', description: 'Packages directory', args: { name: 'dir', template: 'folders' } },
        { name: '--disable-parallel', description: 'Disable parallel restore' },
        { name: '--configfile', description: 'NuGet config file', args: { name: 'file', template: 'filepaths' } },
        { name: '--no-cache', description: 'Don\'t cache packages' },
        { name: '--ignore-failed-sources', description: 'Treat failures as warnings' },
        { name: '--force', description: 'Force restore' },
        { name: ['-f', '--force-evaluate'], description: 'Force re-evaluate dependencies' },
        { name: '--no-dependencies', description: 'Don\'t restore project-to-project references' },
        { name: ['-v', '--verbosity'], description: 'Verbosity level', args: { name: 'level', suggestions: [{ name: 'quiet' }, { name: 'minimal' }, { name: 'normal' }, { name: 'detailed' }, { name: 'diagnostic' }] } },
        { name: '--interactive', description: 'Interactive mode' },
        { name: '--use-lock-file', description: 'Use packages.lock.json' },
        { name: '--locked-mode', description: 'Don\'t update lock file' },
        { name: '--lock-file-path', description: 'Lock file path', args: { name: 'path', template: 'filepaths' } },
      ],
      args: { name: 'project', description: 'Project or solution file', template: 'filepaths', isOptional: true },
    },
    {
      name: 'clean',
      description: 'Clean build outputs',
      options: [
        { name: ['-c', '--configuration'], description: 'Build configuration', args: { name: 'config', suggestions: [{ name: 'Debug' }, { name: 'Release' }] } },
        { name: ['-f', '--framework'], description: 'Target framework', args: { name: 'framework' } },
        { name: ['-r', '--runtime'], description: 'Target runtime', args: { name: 'runtime' } },
        { name: ['-o', '--output'], description: 'Output directory', args: { name: 'dir', template: 'folders' } },
        { name: ['-v', '--verbosity'], description: 'Verbosity level', args: { name: 'level', suggestions: [{ name: 'quiet' }, { name: 'minimal' }, { name: 'normal' }, { name: 'detailed' }, { name: 'diagnostic' }] } },
        { name: '--nologo', description: 'Hide logo' },
      ],
      args: { name: 'project', description: 'Project or solution file', template: 'filepaths', isOptional: true },
    },
    {
      name: 'pack',
      description: 'Create a NuGet package',
      options: [
        { name: ['-c', '--configuration'], description: 'Build configuration', args: { name: 'config', suggestions: [{ name: 'Debug' }, { name: 'Release' }] } },
        { name: ['-o', '--output'], description: 'Output directory', args: { name: 'dir', template: 'folders' } },
        { name: '--no-build', description: 'Don\'t build before packing' },
        { name: '--no-restore', description: 'Don\'t restore before packing' },
        { name: '--include-symbols', description: 'Include symbol packages' },
        { name: '--include-source', description: 'Include source files' },
        { name: ['-v', '--verbosity'], description: 'Verbosity level', args: { name: 'level', suggestions: [{ name: 'quiet' }, { name: 'minimal' }, { name: 'normal' }, { name: 'detailed' }, { name: 'diagnostic' }] } },
        { name: '--version-suffix', description: 'Version suffix', args: { name: 'suffix' } },
        { name: ['-p', '--property'], description: 'Set property', args: { name: 'property' } },
        { name: '--serviceable', description: 'Set serviceable flag' },
        { name: '--nologo', description: 'Hide logo' },
      ],
      args: { name: 'project', description: 'Project or solution file', template: 'filepaths', isOptional: true },
    },
    {
      name: 'add',
      description: 'Add a reference or package',
      subcommands: [
        { name: 'package', description: 'Add a NuGet package reference', options: [{ name: ['-v', '--version'], description: 'Package version', args: { name: 'version' } }, { name: ['-f', '--framework'], description: 'Target framework', args: { name: 'framework' } }, { name: ['-n', '--no-restore'], description: 'Don\'t restore' }, { name: ['-s', '--source'], description: 'NuGet source', args: { name: 'source' } }, { name: '--package-directory', description: 'Packages directory', args: { name: 'dir', template: 'folders' } }, { name: '--prerelease', description: 'Allow prerelease' }, { name: '--interactive', description: 'Interactive mode' }], args: { name: 'package', description: 'Package name' } },
        { name: 'reference', description: 'Add a project-to-project reference', options: [{ name: ['-f', '--framework'], description: 'Target framework', args: { name: 'framework' } }, { name: '--interactive', description: 'Interactive mode' }], args: { name: 'project', description: 'Project path', template: 'filepaths', isVariadic: true } },
      ],
      args: { name: 'project', description: 'Project file', template: 'filepaths', isOptional: true },
    },
    {
      name: 'remove',
      description: 'Remove a reference or package',
      subcommands: [
        { name: 'package', description: 'Remove a NuGet package reference', options: [{ name: '--interactive', description: 'Interactive mode' }], args: { name: 'package', description: 'Package name' } },
        { name: 'reference', description: 'Remove a project-to-project reference', options: [{ name: ['-f', '--framework'], description: 'Target framework', args: { name: 'framework' } }], args: { name: 'project', description: 'Project path', template: 'filepaths', isVariadic: true } },
      ],
      args: { name: 'project', description: 'Project file', template: 'filepaths', isOptional: true },
    },
    {
      name: 'list',
      description: 'List project references or packages',
      subcommands: [
        { name: 'package', description: 'List package references', options: [{ name: '--outdated', description: 'Show outdated packages' }, { name: '--deprecated', description: 'Show deprecated packages' }, { name: '--vulnerable', description: 'Show vulnerable packages' }, { name: ['-f', '--framework'], description: 'Target framework', args: { name: 'framework' } }, { name: '--include-transitive', description: 'Include transitive packages' }, { name: '--include-prerelease', description: 'Include prerelease' }, { name: '--highest-patch', description: 'Show highest patch' }, { name: '--highest-minor', description: 'Show highest minor' }, { name: '--config', description: 'NuGet config', args: { name: 'file', template: 'filepaths' } }, { name: ['-s', '--source'], description: 'NuGet source', args: { name: 'source' } }, { name: '--format', description: 'Output format', args: { name: 'format', suggestions: [{ name: 'console' }, { name: 'json' }] } }, { name: '--output-version', description: 'Output version', args: { name: 'version' } }, { name: '--interactive', description: 'Interactive mode' }] },
        { name: 'reference', description: 'List project-to-project references' },
      ],
      args: { name: 'project', description: 'Project file', template: 'filepaths', isOptional: true },
    },
    {
      name: 'sln',
      description: 'Modify solution files',
      subcommands: [
        { name: 'add', description: 'Add projects to solution', options: [{ name: ['-s', '--solution-folder'], description: 'Solution folder', args: { name: 'folder' } }, { name: '--in-root', description: 'Place in root' }], args: { name: 'projects', description: 'Project files', template: 'filepaths', isVariadic: true } },
        { name: 'remove', description: 'Remove projects from solution', args: { name: 'projects', description: 'Project files', template: 'filepaths', isVariadic: true } },
        { name: 'list', description: 'List projects in solution' },
      ],
      args: { name: 'solution', description: 'Solution file', template: 'filepaths', isOptional: true },
    },
    {
      name: 'nuget',
      description: 'NuGet commands',
      subcommands: [
        { name: 'push', description: 'Push a package', options: [{ name: ['-s', '--source'], description: 'Source', args: { name: 'source' } }, { name: ['-k', '--api-key'], description: 'API key', args: { name: 'key' } }, { name: '--symbol-source', description: 'Symbol source', args: { name: 'source' } }, { name: '--symbol-api-key', description: 'Symbol API key', args: { name: 'key' } }, { name: ['-t', '--timeout'], description: 'Timeout', args: { name: 'seconds' } }, { name: ['-n', '--no-symbols'], description: 'Don\'t push symbols' }, { name: '--disable-buffering', description: 'Disable buffering' }, { name: '--no-service-endpoint', description: 'Don\'t append endpoint' }, { name: '--interactive', description: 'Interactive mode' }, { name: '--skip-duplicate', description: 'Skip duplicate packages' }, { name: '--force-english-output', description: 'Force English output' }], args: { name: 'package', description: 'Package file', template: 'filepaths' } },
        { name: 'delete', description: 'Delete a package', options: [{ name: ['-s', '--source'], description: 'Source', args: { name: 'source' } }, { name: ['-k', '--api-key'], description: 'API key', args: { name: 'key' } }, { name: '--non-interactive', description: 'Non-interactive mode' }, { name: '--no-service-endpoint', description: 'Don\'t append endpoint' }, { name: '--interactive', description: 'Interactive mode' }, { name: '--force-english-output', description: 'Force English output' }], args: [{ name: 'package', description: 'Package ID' }, { name: 'version', description: 'Package version' }] },
        { name: 'locals', description: 'Show local NuGet resources', options: [{ name: ['-c', '--clear'], description: 'Clear cache' }, { name: ['-l', '--list'], description: 'List locations' }, { name: '--force-english-output', description: 'Force English output' }], args: { name: 'cache', description: 'Cache to manage', suggestions: [{ name: 'all' }, { name: 'http-cache' }, { name: 'global-packages' }, { name: 'plugins-cache' }, { name: 'temp' }] } },
        { name: 'verify', description: 'Verify a signed package', options: [{ name: '--all', description: 'Verify all signatures' }, { name: '--certificate-fingerprint', description: 'Certificate fingerprint', args: { name: 'fingerprint' } }, { name: ['-v', '--verbosity'], description: 'Verbosity level', args: { name: 'level', suggestions: [{ name: 'quiet' }, { name: 'normal' }, { name: 'detailed' }] } }], args: { name: 'package', description: 'Package file', template: 'filepaths', isVariadic: true } },
        { name: 'sign', description: 'Sign a package', options: [{ name: ['-o', '--output'], description: 'Output directory', args: { name: 'dir', template: 'folders' } }, { name: '--certificate-path', description: 'Certificate path', args: { name: 'path', template: 'filepaths' } }, { name: '--certificate-store-name', description: 'Store name', args: { name: 'name' } }, { name: '--certificate-store-location', description: 'Store location', args: { name: 'location' } }, { name: '--certificate-subject-name', description: 'Subject name', args: { name: 'name' } }, { name: '--certificate-fingerprint', description: 'Fingerprint', args: { name: 'fingerprint' } }, { name: '--certificate-password', description: 'Password', args: { name: 'password' } }, { name: '--hash-algorithm', description: 'Hash algorithm', args: { name: 'algo', suggestions: [{ name: 'SHA256' }, { name: 'SHA384' }, { name: 'SHA512' }] } }, { name: '--timestamper', description: 'Timestamper URL', args: { name: 'url' } }, { name: '--timestamp-hash-algorithm', description: 'Timestamp hash algorithm', args: { name: 'algo' } }, { name: '--overwrite', description: 'Overwrite existing signature' }, { name: ['-v', '--verbosity'], description: 'Verbosity level', args: { name: 'level' } }], args: { name: 'package', description: 'Package file', template: 'filepaths', isVariadic: true } },
        { name: 'trust', description: 'Manage trusted signers', subcommands: [{ name: 'list', description: 'List trusted signers' }, { name: 'author', description: 'Add author signer', options: [{ name: '--allow-untrusted-root', description: 'Allow untrusted root' }, { name: '--configfile', description: 'Config file', args: { name: 'file', template: 'filepaths' } }], args: [{ name: 'name' }, { name: 'package', template: 'filepaths' }] }, { name: 'repository', description: 'Add repository signer', options: [{ name: '--allow-untrusted-root' }, { name: '--owners', args: { name: 'owners' } }, { name: '--configfile', args: { name: 'file', template: 'filepaths' } }], args: [{ name: 'name' }, { name: 'package', template: 'filepaths' }] }, { name: 'source', description: 'Add source', options: [{ name: '--allow-untrusted-root' }, { name: '--owners', args: { name: 'owners' } }, { name: '--configfile', args: { name: 'file', template: 'filepaths' } }, { name: '--source-url', args: { name: 'url' } }], args: { name: 'name' } }, { name: 'certificate', description: 'Add certificate', options: [{ name: '--allow-untrusted-root' }, { name: '--fingerprint', args: { name: 'fingerprint' } }, { name: '--algorithm', args: { name: 'algorithm' } }, { name: '--configfile', args: { name: 'file', template: 'filepaths' } }], args: { name: 'name' } }, { name: 'remove', description: 'Remove trusted signer', options: [{ name: '--configfile', args: { name: 'file', template: 'filepaths' } }], args: { name: 'name' } }, { name: 'sync', description: 'Sync trusted certificates', options: [{ name: '--configfile', args: { name: 'file', template: 'filepaths' } }], args: { name: 'name' } }] },
      ],
    },
    {
      name: 'tool',
      description: 'Manage .NET tools',
      subcommands: [
        { name: 'install', description: 'Install a .NET tool', options: [{ name: ['-g', '--global'], description: 'Global install' }, { name: '--local', description: 'Local install' }, { name: '--tool-path', description: 'Tool path', args: { name: 'path', template: 'folders' } }, { name: '--version', description: 'Version', args: { name: 'version' } }, { name: '--configfile', description: 'NuGet config', args: { name: 'file', template: 'filepaths' } }, { name: '--tool-manifest', description: 'Tool manifest', args: { name: 'file', template: 'filepaths' } }, { name: '--add-source', description: 'Add source', args: { name: 'source' } }, { name: ['-f', '--framework'], description: 'Target framework', args: { name: 'framework' } }, { name: '--prerelease', description: 'Allow prerelease' }, { name: ['-v', '--verbosity'], description: 'Verbosity', args: { name: 'level' } }], args: { name: 'package', description: 'Package name' } },
        { name: 'uninstall', description: 'Uninstall a .NET tool', options: [{ name: ['-g', '--global'], description: 'Global uninstall' }, { name: '--local', description: 'Local uninstall' }, { name: '--tool-path', description: 'Tool path', args: { name: 'path', template: 'folders' } }, { name: '--tool-manifest', description: 'Tool manifest', args: { name: 'file', template: 'filepaths' } }], args: { name: 'package', description: 'Package name' } },
        { name: 'update', description: 'Update a .NET tool', options: [{ name: ['-g', '--global'], description: 'Global update' }, { name: '--local', description: 'Local update' }, { name: '--tool-path', description: 'Tool path', args: { name: 'path', template: 'folders' } }, { name: '--configfile', description: 'NuGet config', args: { name: 'file', template: 'filepaths' } }, { name: '--tool-manifest', description: 'Tool manifest', args: { name: 'file', template: 'filepaths' } }, { name: '--add-source', description: 'Add source', args: { name: 'source' } }, { name: ['-f', '--framework'], description: 'Target framework', args: { name: 'framework' } }, { name: '--version', description: 'Version', args: { name: 'version' } }, { name: '--prerelease', description: 'Allow prerelease' }, { name: ['-v', '--verbosity'], description: 'Verbosity', args: { name: 'level' } }], args: { name: 'package', description: 'Package name' } },
        { name: 'list', description: 'List installed tools', options: [{ name: ['-g', '--global'], description: 'List global tools' }, { name: '--local', description: 'List local tools' }, { name: '--tool-path', description: 'Tool path', args: { name: 'path', template: 'folders' } }] },
        { name: 'run', description: 'Run a local tool', args: { name: 'command', description: 'Tool command', isVariadic: true } },
        { name: 'search', description: 'Search for tools', options: [{ name: '--detail', description: 'Show details' }, { name: '--skip', description: 'Skip results', args: { name: 'count' } }, { name: '--take', description: 'Take results', args: { name: 'count' } }, { name: '--prerelease', description: 'Include prerelease' }], args: { name: 'term', description: 'Search term', isOptional: true } },
        { name: 'restore', description: 'Restore local tools', options: [{ name: '--configfile', description: 'NuGet config', args: { name: 'file', template: 'filepaths' } }, { name: '--add-source', description: 'Add source', args: { name: 'source' } }, { name: '--tool-manifest', description: 'Tool manifest', args: { name: 'file', template: 'filepaths' } }, { name: ['-v', '--verbosity'], description: 'Verbosity', args: { name: 'level' } }] },
      ],
    },
    {
      name: 'watch',
      description: 'Run with file watcher',
      options: [
        { name: '--project', description: 'Project file', args: { name: 'project', template: 'filepaths' } },
        { name: '--launch-profile', description: 'Launch profile', args: { name: 'profile' } },
        { name: '--no-launch-profile', description: 'Don\'t use launch profiles' },
        { name: '--no-hot-reload', description: 'Disable hot reload' },
        { name: '--non-interactive', description: 'Non-interactive mode' },
        { name: ['-v', '--verbose'], description: 'Verbose output' },
        { name: ['-q', '--quiet'], description: 'Quiet output' },
      ],
      args: { name: 'command', description: 'Command to run (run, test, build)', isOptional: true },
    },
    {
      name: 'format',
      description: 'Format source code',
      options: [
        { name: '--diagnostics', description: 'Show diagnostics' },
        { name: '--severity', description: 'Minimum severity', args: { name: 'level', suggestions: [{ name: 'info' }, { name: 'warn' }, { name: 'error' }] } },
        { name: '--no-restore', description: 'Don\'t restore' },
        { name: '--verify-no-changes', description: 'Verify no changes' },
        { name: '--include', description: 'Include files', args: { name: 'pattern' } },
        { name: '--exclude', description: 'Exclude files', args: { name: 'pattern' } },
        { name: '--include-generated', description: 'Include generated' },
        { name: ['-v', '--verbosity'], description: 'Verbosity level', args: { name: 'level', suggestions: [{ name: 'quiet' }, { name: 'minimal' }, { name: 'normal' }, { name: 'detailed' }, { name: 'diagnostic' }] } },
        { name: '--binarylog', description: 'Binary log', args: { name: 'path', template: 'filepaths', isOptional: true } },
        { name: '--report', description: 'Report path', args: { name: 'path', template: 'filepaths' } },
      ],
      args: { name: 'project', description: 'Project or solution', template: 'filepaths', isOptional: true },
    },
    { name: 'workload', description: 'Manage workloads', subcommands: [
      { name: 'install', description: 'Install workloads', options: [{ name: '--skip-manifest-update' }, { name: '--temp-dir', args: { name: 'dir', template: 'folders' } }, { name: '--configfile', args: { name: 'file', template: 'filepaths' } }, { name: '--add-source', args: { name: 'source' } }, { name: '--skip-sign-check' }, { name: '--include-previews' }, { name: ['-v', '--verbosity'], args: { name: 'level' } }], args: { name: 'workloads', isVariadic: true } },
      { name: 'update', description: 'Update workloads', options: [{ name: '--temp-dir', args: { name: 'dir', template: 'folders' } }, { name: '--configfile', args: { name: 'file', template: 'filepaths' } }, { name: '--add-source', args: { name: 'source' } }, { name: '--include-previews' }, { name: ['-v', '--verbosity'], args: { name: 'level' } }] },
      { name: 'uninstall', description: 'Uninstall workloads', args: { name: 'workloads', isVariadic: true } },
      { name: 'list', description: 'List installed workloads', options: [{ name: ['-v', '--verbosity'], args: { name: 'level' } }] },
      { name: 'search', description: 'Search for workloads', options: [{ name: ['-v', '--verbosity'], args: { name: 'level' } }], args: { name: 'term', isOptional: true } },
      { name: 'repair', description: 'Repair workload installations', options: [{ name: '--temp-dir', args: { name: 'dir', template: 'folders' } }, { name: '--configfile', args: { name: 'file', template: 'filepaths' } }, { name: '--add-source', args: { name: 'source' } }, { name: ['-v', '--verbosity'], args: { name: 'level' } }] },
      { name: 'restore', description: 'Restore workloads required by project', options: [{ name: '--temp-dir', args: { name: 'dir', template: 'folders' } }, { name: '--configfile', args: { name: 'file', template: 'filepaths' } }, { name: '--add-source', args: { name: 'source' } }, { name: '--skip-sign-check' }, { name: '--include-previews' }, { name: ['-v', '--verbosity'], args: { name: 'level' } }], args: { name: 'project', template: 'filepaths', isOptional: true } },
      { name: 'clean', description: 'Clean workload installation state' },
    ]},
    {
      name: 'ef',
      description: 'Entity Framework Core commands',
      subcommands: [
        { name: 'migrations', description: 'Manage migrations', subcommands: [
          { name: 'add', description: 'Add a migration', options: [{ name: ['-o', '--output-dir'], args: { name: 'dir', template: 'folders' } }, { name: '--namespace', args: { name: 'ns' } }, { name: ['-c', '--context'], args: { name: 'context' } }, { name: ['-p', '--project'], args: { name: 'project', template: 'filepaths' } }, { name: ['-s', '--startup-project'], args: { name: 'project', template: 'filepaths' } }, { name: '--configuration', args: { name: 'config' } }, { name: ['-f', '--framework'], args: { name: 'framework' } }, { name: '--no-build' }], args: { name: 'name' } },
          { name: 'remove', description: 'Remove migration', options: [{ name: ['-c', '--context'], args: { name: 'context' } }, { name: ['-p', '--project'], args: { name: 'project', template: 'filepaths' } }, { name: ['-s', '--startup-project'], args: { name: 'project', template: 'filepaths' } }, { name: ['-f', '--force'] }, { name: '--no-build' }] },
          { name: 'list', description: 'List migrations', options: [{ name: ['-c', '--context'], args: { name: 'context' } }, { name: ['-p', '--project'], args: { name: 'project', template: 'filepaths' } }, { name: ['-s', '--startup-project'], args: { name: 'project', template: 'filepaths' } }, { name: '--connection', args: { name: 'connection' } }, { name: '--no-connect' }, { name: '--no-build' }] },
          { name: 'script', description: 'Generate SQL script', options: [{ name: ['-o', '--output'], args: { name: 'file', template: 'filepaths' } }, { name: ['-i', '--idempotent'] }, { name: '--no-transactions' }, { name: ['-c', '--context'], args: { name: 'context' } }, { name: ['-p', '--project'], args: { name: 'project', template: 'filepaths' } }, { name: ['-s', '--startup-project'], args: { name: 'project', template: 'filepaths' } }, { name: '--no-build' }], args: [{ name: 'from', isOptional: true }, { name: 'to', isOptional: true }] },
          { name: 'bundle', description: 'Create executable bundle', options: [{ name: ['-o', '--output'], args: { name: 'file', template: 'filepaths' } }, { name: ['-r', '--runtime'], args: { name: 'runtime' } }, { name: '--self-contained' }, { name: ['-f', '--force'] }, { name: ['-c', '--context'], args: { name: 'context' } }, { name: ['-p', '--project'], args: { name: 'project', template: 'filepaths' } }, { name: ['-s', '--startup-project'], args: { name: 'project', template: 'filepaths' } }, { name: '--no-build' }] },
        ]},
        { name: 'database', description: 'Database commands', subcommands: [
          { name: 'update', description: 'Update database', options: [{ name: ['-c', '--context'], args: { name: 'context' } }, { name: ['-p', '--project'], args: { name: 'project', template: 'filepaths' } }, { name: ['-s', '--startup-project'], args: { name: 'project', template: 'filepaths' } }, { name: '--connection', args: { name: 'connection' } }, { name: '--no-build' }], args: { name: 'migration', isOptional: true } },
          { name: 'drop', description: 'Drop database', options: [{ name: ['-c', '--context'], args: { name: 'context' } }, { name: ['-p', '--project'], args: { name: 'project', template: 'filepaths' } }, { name: ['-s', '--startup-project'], args: { name: 'project', template: 'filepaths' } }, { name: ['-f', '--force'] }, { name: '--dry-run' }, { name: '--no-build' }] },
        ]},
        { name: 'dbcontext', description: 'DbContext commands', subcommands: [
          { name: 'info', description: 'Get context info', options: [{ name: ['-c', '--context'], args: { name: 'context' } }, { name: ['-p', '--project'], args: { name: 'project', template: 'filepaths' } }, { name: ['-s', '--startup-project'], args: { name: 'project', template: 'filepaths' } }, { name: '--no-build' }] },
          { name: 'list', description: 'List contexts', options: [{ name: ['-p', '--project'], args: { name: 'project', template: 'filepaths' } }, { name: ['-s', '--startup-project'], args: { name: 'project', template: 'filepaths' } }, { name: '--no-build' }] },
          { name: 'scaffold', description: 'Scaffold from database', options: [{ name: ['-d', '--data-annotations'] }, { name: ['-c', '--context'], args: { name: 'context' } }, { name: '--context-dir', args: { name: 'dir', template: 'folders' } }, { name: '--context-namespace', args: { name: 'ns' } }, { name: ['-f', '--force'] }, { name: ['-o', '--output-dir'], args: { name: 'dir', template: 'folders' } }, { name: '--namespace', args: { name: 'ns' } }, { name: ['-t', '--table'], args: { name: 'table' } }, { name: '--schema', args: { name: 'schema' } }, { name: '--use-database-names' }, { name: ['-p', '--project'], args: { name: 'project', template: 'filepaths' } }, { name: ['-s', '--startup-project'], args: { name: 'project', template: 'filepaths' } }, { name: '--no-build' }, { name: '--no-onconfiguring' }, { name: '--no-pluralize' }], args: [{ name: 'connection' }, { name: 'provider' }] },
          { name: 'optimize', description: 'Generate compiled model', options: [{ name: ['-o', '--output-dir'], args: { name: 'dir', template: 'folders' } }, { name: ['-n', '--namespace'], args: { name: 'ns' } }, { name: ['-c', '--context'], args: { name: 'context' } }, { name: ['-p', '--project'], args: { name: 'project', template: 'filepaths' } }, { name: ['-s', '--startup-project'], args: { name: 'project', template: 'filepaths' } }, { name: '--no-build' }] },
        ]},
      ],
    },
  ],
};
