// ffmpeg - Multimedia framework for encoding, decoding, transcoding
import { CompletionSpec } from '../types.js';

const formatSuggestions = [
  { name: 'mp4', description: 'MPEG-4 Part 14' },
  { name: 'mkv', description: 'Matroska' },
  { name: 'webm', description: 'WebM' },
  { name: 'avi', description: 'Audio Video Interleaved' },
  { name: 'mov', description: 'QuickTime' },
  { name: 'flv', description: 'Flash Video' },
  { name: 'mp3', description: 'MPEG Audio Layer 3' },
  { name: 'wav', description: 'Waveform Audio' },
  { name: 'aac', description: 'Advanced Audio Coding' },
  { name: 'ogg', description: 'Ogg' },
  { name: 'flac', description: 'Free Lossless Audio Codec' },
  { name: 'gif', description: 'Graphics Interchange Format' },
  { name: 'png', description: 'PNG image' },
  { name: 'mjpeg', description: 'Motion JPEG' },
  { name: 'image2', description: 'Image sequence' },
  { name: 'null', description: 'Null output' },
  { name: 'hls', description: 'HTTP Live Streaming' },
  { name: 'dash', description: 'DASH' },
  { name: 'matroska', description: 'Matroska container' },
  { name: 'rawvideo', description: 'Raw video' },
];

const videoCodecSuggestions = [
  { name: 'libx264', description: 'H.264/AVC encoder' },
  { name: 'libx265', description: 'H.265/HEVC encoder' },
  { name: 'libvpx', description: 'VP8 encoder' },
  { name: 'libvpx-vp9', description: 'VP9 encoder' },
  { name: 'libaom-av1', description: 'AV1 encoder' },
  { name: 'libsvtav1', description: 'SVT-AV1 encoder' },
  { name: 'h264_nvenc', description: 'NVIDIA H.264 encoder' },
  { name: 'hevc_nvenc', description: 'NVIDIA HEVC encoder' },
  { name: 'h264_videotoolbox', description: 'macOS H.264 encoder' },
  { name: 'hevc_videotoolbox', description: 'macOS HEVC encoder' },
  { name: 'h264_qsv', description: 'Intel QSV H.264' },
  { name: 'hevc_qsv', description: 'Intel QSV HEVC' },
  { name: 'h264_amf', description: 'AMD AMF H.264' },
  { name: 'hevc_amf', description: 'AMD AMF HEVC' },
  { name: 'mpeg4', description: 'MPEG-4 Part 2' },
  { name: 'mpeg2video', description: 'MPEG-2' },
  { name: 'prores', description: 'Apple ProRes' },
  { name: 'prores_ks', description: 'Apple ProRes (ks)' },
  { name: 'dnxhd', description: 'Avid DNxHD' },
  { name: 'mjpeg', description: 'Motion JPEG' },
  { name: 'gif', description: 'GIF' },
  { name: 'png', description: 'PNG' },
  { name: 'copy', description: 'Copy (no re-encode)' },
];

const audioCodecSuggestions = [
  { name: 'aac', description: 'AAC encoder' },
  { name: 'libfdk_aac', description: 'Fraunhofer AAC' },
  { name: 'libmp3lame', description: 'MP3 encoder' },
  { name: 'libvorbis', description: 'Vorbis encoder' },
  { name: 'libopus', description: 'Opus encoder' },
  { name: 'flac', description: 'FLAC encoder' },
  { name: 'alac', description: 'Apple Lossless' },
  { name: 'ac3', description: 'AC-3' },
  { name: 'eac3', description: 'E-AC-3' },
  { name: 'pcm_s16le', description: 'PCM 16-bit little-endian' },
  { name: 'pcm_s24le', description: 'PCM 24-bit little-endian' },
  { name: 'pcm_s32le', description: 'PCM 32-bit little-endian' },
  { name: 'copy', description: 'Copy (no re-encode)' },
];

const presetSuggestions = [
  { name: 'ultrafast', description: 'Fastest encoding' },
  { name: 'superfast', description: 'Very fast encoding' },
  { name: 'veryfast', description: 'Fast encoding' },
  { name: 'faster', description: 'Faster encoding' },
  { name: 'fast', description: 'Fast encoding' },
  { name: 'medium', description: 'Default preset' },
  { name: 'slow', description: 'Slow encoding' },
  { name: 'slower', description: 'Slower encoding' },
  { name: 'veryslow', description: 'Slowest encoding' },
  { name: 'placebo', description: 'Placebo (extremely slow)' },
];

const pixelFormatSuggestions = [
  { name: 'yuv420p', description: 'YUV 4:2:0 (most compatible)' },
  { name: 'yuv422p', description: 'YUV 4:2:2' },
  { name: 'yuv444p', description: 'YUV 4:4:4' },
  { name: 'yuv420p10le', description: 'YUV 4:2:0 10-bit' },
  { name: 'yuv422p10le', description: 'YUV 4:2:2 10-bit' },
  { name: 'yuv444p10le', description: 'YUV 4:4:4 10-bit' },
  { name: 'rgb24', description: 'RGB 24-bit' },
  { name: 'rgba', description: 'RGBA 32-bit' },
  { name: 'gray', description: 'Grayscale' },
  { name: 'nv12', description: 'NV12' },
  { name: 'p010le', description: 'P010 10-bit' },
];

export const ffmpegSpec: CompletionSpec = {
  name: 'ffmpeg',
  description: 'FFmpeg multimedia framework',
  options: [
    // Global options
    { name: '-y', description: 'Overwrite output files' },
    { name: '-n', description: 'Never overwrite output files' },
    { name: '-v', description: 'Verbosity level', args: { name: 'level', suggestions: [{ name: 'quiet' }, { name: 'panic' }, { name: 'fatal' }, { name: 'error' }, { name: 'warning' }, { name: 'info' }, { name: 'verbose' }, { name: 'debug' }, { name: 'trace' }] } },
    { name: '-loglevel', description: 'Log level', args: { name: 'level', suggestions: [{ name: 'quiet' }, { name: 'panic' }, { name: 'fatal' }, { name: 'error' }, { name: 'warning' }, { name: 'info' }, { name: 'verbose' }, { name: 'debug' }, { name: 'trace' }] } },
    { name: '-hide_banner', description: 'Hide banner' },
    { name: '-stats', description: 'Show encoding stats' },
    { name: '-progress', description: 'Progress output', args: { name: 'url' } },
    { name: '-max_alloc', description: 'Maximum allocation', args: { name: 'bytes' } },

    // Input options
    { name: '-i', description: 'Input file', args: { name: 'file', template: 'filepaths' }, isRepeatable: true },
    { name: '-f', description: 'Force format', args: { name: 'format', suggestions: formatSuggestions } },
    { name: '-ss', description: 'Start time', args: { name: 'time', suggestions: [{ name: '00:00:00' }, { name: '00:01:00' }, { name: '00:00:30' }, { name: '10' }, { name: '60' }] } },
    { name: '-t', description: 'Duration', args: { name: 'duration', suggestions: [{ name: '00:00:10' }, { name: '00:01:00' }, { name: '10' }, { name: '60' }] } },
    { name: '-to', description: 'End time', args: { name: 'time' } },
    { name: '-sseof', description: 'Start time from end', args: { name: 'time' } },
    { name: '-itsoffset', description: 'Input timestamp offset', args: { name: 'offset' } },
    { name: '-itsscale', description: 'Input timestamp scale', args: { name: 'scale' } },
    { name: '-re', description: 'Read input at native frame rate' },
    { name: '-stream_loop', description: 'Loop input', args: { name: 'count' } },
    { name: '-thread_queue_size', description: 'Input thread queue size', args: { name: 'size' } },

    // Video options
    { name: '-c:v', description: 'Video codec', args: { name: 'codec', suggestions: videoCodecSuggestions } },
    { name: '-vcodec', description: 'Video codec', args: { name: 'codec', suggestions: videoCodecSuggestions } },
    { name: '-b:v', description: 'Video bitrate', args: { name: 'bitrate', suggestions: [{ name: '1M' }, { name: '2M' }, { name: '5M' }, { name: '10M' }, { name: '20M' }, { name: '50M' }] } },
    { name: '-r', description: 'Frame rate', args: { name: 'fps', suggestions: [{ name: '23.976' }, { name: '24' }, { name: '25' }, { name: '29.97' }, { name: '30' }, { name: '50' }, { name: '59.94' }, { name: '60' }] } },
    { name: '-s', description: 'Video size', args: { name: 'size', suggestions: [{ name: '1920x1080' }, { name: '1280x720' }, { name: '3840x2160' }, { name: '640x480' }, { name: '854x480' }] } },
    { name: '-aspect', description: 'Aspect ratio', args: { name: 'ratio', suggestions: [{ name: '16:9' }, { name: '4:3' }, { name: '21:9' }, { name: '1:1' }] } },
    { name: '-vn', description: 'Disable video' },
    { name: '-vframes', description: 'Number of video frames', args: { name: 'count' } },
    { name: '-pix_fmt', description: 'Pixel format', args: { name: 'format', suggestions: pixelFormatSuggestions } },
    { name: '-crf', description: 'Constant rate factor', args: { name: 'value', suggestions: [{ name: '18', description: 'High quality' }, { name: '23', description: 'Default' }, { name: '28', description: 'Lower quality' }, { name: '0', description: 'Lossless' }] } },
    { name: '-preset', description: 'Encoding preset', args: { name: 'preset', suggestions: presetSuggestions } },
    { name: '-tune', description: 'Encoding tune', args: { name: 'tune', suggestions: [{ name: 'film' }, { name: 'animation' }, { name: 'grain' }, { name: 'stillimage' }, { name: 'fastdecode' }, { name: 'zerolatency' }, { name: 'psnr' }, { name: 'ssim' }] } },
    { name: '-profile:v', description: 'Video profile', args: { name: 'profile', suggestions: [{ name: 'baseline' }, { name: 'main' }, { name: 'high' }, { name: 'high10' }, { name: 'high422' }, { name: 'high444' }] } },
    { name: '-level', description: 'Video level', args: { name: 'level', suggestions: [{ name: '3.0' }, { name: '3.1' }, { name: '4.0' }, { name: '4.1' }, { name: '4.2' }, { name: '5.0' }, { name: '5.1' }, { name: '5.2' }] } },
    { name: '-g', description: 'GOP size', args: { name: 'size' } },
    { name: '-keyint_min', description: 'Minimum GOP size', args: { name: 'size' } },
    { name: '-sc_threshold', description: 'Scene change threshold', args: { name: 'value' } },
    { name: '-bf', description: 'B-frames', args: { name: 'count' } },
    { name: '-refs', description: 'Reference frames', args: { name: 'count' } },
    { name: '-maxrate', description: 'Max bitrate', args: { name: 'rate' } },
    { name: '-minrate', description: 'Min bitrate', args: { name: 'rate' } },
    { name: '-bufsize', description: 'Buffer size', args: { name: 'size' } },
    { name: '-rc', description: 'Rate control', args: { name: 'mode', suggestions: [{ name: 'vbr' }, { name: 'cbr' }, { name: 'cqp' }, { name: 'vbr_hq' }, { name: 'cbr_hq' }] } },
    { name: '-qp', description: 'Quantization parameter', args: { name: 'value' } },
    { name: '-qmin', description: 'Min QP', args: { name: 'value' } },
    { name: '-qmax', description: 'Max QP', args: { name: 'value' } },
    { name: '-pass', description: 'Pass number', args: { name: 'pass', suggestions: [{ name: '1' }, { name: '2' }] } },
    { name: '-passlogfile', description: 'Pass log file', args: { name: 'file', template: 'filepaths' } },
    { name: '-x264-params', description: 'x264 parameters', args: { name: 'params' } },
    { name: '-x265-params', description: 'x265 parameters', args: { name: 'params' } },

    // Audio options
    { name: '-c:a', description: 'Audio codec', args: { name: 'codec', suggestions: audioCodecSuggestions } },
    { name: '-acodec', description: 'Audio codec', args: { name: 'codec', suggestions: audioCodecSuggestions } },
    { name: '-b:a', description: 'Audio bitrate', args: { name: 'bitrate', suggestions: [{ name: '128k' }, { name: '192k' }, { name: '256k' }, { name: '320k' }] } },
    { name: '-ar', description: 'Audio sample rate', args: { name: 'rate', suggestions: [{ name: '44100' }, { name: '48000' }, { name: '96000' }, { name: '22050' }] } },
    { name: '-ac', description: 'Audio channels', args: { name: 'channels', suggestions: [{ name: '1', description: 'Mono' }, { name: '2', description: 'Stereo' }, { name: '6', description: '5.1 surround' }, { name: '8', description: '7.1 surround' }] } },
    { name: '-an', description: 'Disable audio' },
    { name: '-aframes', description: 'Number of audio frames', args: { name: 'count' } },
    { name: '-af', description: 'Audio filter', args: { name: 'filter', suggestions: [{ name: 'volume=2.0' }, { name: 'aresample=48000' }, { name: 'loudnorm' }, { name: 'highpass=f=200' }, { name: 'lowpass=f=3000' }, { name: 'adelay' }, { name: 'aecho' }, { name: 'atempo=0.5' }, { name: 'atempo=2.0' }] } },
    { name: '-aq', description: 'Audio quality', args: { name: 'quality' } },

    // Subtitle options
    { name: '-c:s', description: 'Subtitle codec', args: { name: 'codec', suggestions: [{ name: 'mov_text' }, { name: 'srt' }, { name: 'ass' }, { name: 'webvtt' }, { name: 'dvdsub' }, { name: 'copy' }] } },
    { name: '-scodec', description: 'Subtitle codec', args: { name: 'codec' } },
    { name: '-sn', description: 'Disable subtitles' },

    // Filter options
    { name: '-vf', description: 'Video filter', args: { name: 'filter', suggestions: [{ name: 'scale=1280:720' }, { name: 'scale=1920:1080' }, { name: 'scale=-1:720' }, { name: 'crop=w:h:x:y' }, { name: 'transpose=1' }, { name: 'transpose=2' }, { name: 'hflip' }, { name: 'vflip' }, { name: 'fps=30' }, { name: 'setpts=0.5*PTS' }, { name: 'setpts=2.0*PTS' }, { name: 'eq=brightness=0.1' }, { name: 'eq=contrast=1.2' }, { name: 'deinterlace' }, { name: 'yadif' }, { name: 'pad' }, { name: 'overlay' }, { name: 'drawtext' }, { name: 'subtitles' }, { name: 'colorbalance' }, { name: 'unsharp' }, { name: 'denoise' }, { name: 'palettegen' }, { name: 'paletteuse' }] } },
    { name: '-filter_complex', description: 'Complex filtergraph', args: { name: 'graph' } },
    { name: '-lavfi', description: 'Libavfilter input', args: { name: 'graph' } },

    // Codec options
    { name: '-c', description: 'Codec', args: { name: 'codec', suggestions: [{ name: 'copy' }] } },
    { name: '-codec', description: 'Codec', args: { name: 'codec' } },

    // Mapping options
    { name: '-map', description: 'Stream mapping', args: { name: 'mapping', suggestions: [{ name: '0' }, { name: '0:v' }, { name: '0:a' }, { name: '0:s' }, { name: '0:v:0' }, { name: '0:a:0' }, { name: '1:a' }] } },
    { name: '-map_metadata', description: 'Metadata mapping', args: { name: 'mapping' } },
    { name: '-map_chapters', description: 'Chapters mapping', args: { name: 'input' } },

    // Metadata options
    { name: '-metadata', description: 'Metadata', args: { name: 'key=value' } },
    { name: '-metadata:s', description: 'Stream metadata', args: { name: 'key=value' } },
    { name: '-disposition', description: 'Stream disposition', args: { name: 'disposition' } },

    // Output options
    { name: '-movflags', description: 'MOV flags', args: { name: 'flags', suggestions: [{ name: '+faststart' }, { name: 'frag_keyframe' }, { name: 'empty_moov' }, { name: 'separate_moof' }, { name: 'dash' }] } },
    { name: '-segment_time', description: 'Segment duration', args: { name: 'time' } },
    { name: '-hls_time', description: 'HLS segment duration', args: { name: 'time' } },
    { name: '-hls_list_size', description: 'HLS playlist size', args: { name: 'size' } },
    { name: '-hls_segment_filename', description: 'HLS segment filename', args: { name: 'pattern' } },
    { name: '-start_number', description: 'Starting number', args: { name: 'number' } },
    { name: '-shortest', description: 'Finish when shortest input ends' },
    { name: '-shortest_buf_duration', description: 'Shortest buffer duration', args: { name: 'duration' } },

    // Threading
    { name: '-threads', description: 'Number of threads', args: { name: 'count', suggestions: [{ name: '0', description: 'Auto' }, { name: '1' }, { name: '2' }, { name: '4' }, { name: '8' }, { name: '16' }] } },
    { name: '-filter_threads', description: 'Filter threads', args: { name: 'count' } },
    { name: '-filter_complex_threads', description: 'Complex filter threads', args: { name: 'count' } },

    // Hardware acceleration
    { name: '-hwaccel', description: 'Hardware acceleration', args: { name: 'method', suggestions: [{ name: 'none' }, { name: 'auto' }, { name: 'cuda' }, { name: 'nvdec' }, { name: 'videotoolbox' }, { name: 'qsv' }, { name: 'vaapi' }, { name: 'dxva2' }, { name: 'd3d11va' }] } },
    { name: '-hwaccel_device', description: 'Hardware device', args: { name: 'device' } },
    { name: '-hwaccel_output_format', description: 'Hardware output format', args: { name: 'format' } },
    { name: '-init_hw_device', description: 'Initialize hardware device', args: { name: 'type=name' } },
    { name: '-filter_hw_device', description: 'Filter hardware device', args: { name: 'name' } },

    // Info options
    { name: '-formats', description: 'Show available formats' },
    { name: '-codecs', description: 'Show available codecs' },
    { name: '-decoders', description: 'Show available decoders' },
    { name: '-encoders', description: 'Show available encoders' },
    { name: '-filters', description: 'Show available filters' },
    { name: '-pix_fmts', description: 'Show pixel formats' },
    { name: '-layouts', description: 'Show channel layouts' },
    { name: '-sample_fmts', description: 'Show sample formats' },
    { name: '-hwaccels', description: 'Show hardware accelerators' },
    { name: '-protocols', description: 'Show available protocols' },
    { name: '-bsfs', description: 'Show available bitstream filters' },
    { name: '-muxers', description: 'Show available muxers' },
    { name: '-demuxers', description: 'Show available demuxers' },
    { name: '-devices', description: 'Show available devices' },
    { name: '-h', description: 'Show help', args: { name: 'topic', isOptional: true } },
    { name: '-help', description: 'Show help', args: { name: 'topic', isOptional: true } },
    { name: '-version', description: 'Show version' },
    { name: '-buildconf', description: 'Show build configuration' },
  ],
  args: { name: 'output', description: 'Output file', template: 'filepaths', isOptional: true, isVariadic: true },
};

// Also export ffprobe
export const ffprobeSpec: CompletionSpec = {
  name: 'ffprobe',
  description: 'Multimedia stream analyzer',
  options: [
    { name: '-v', description: 'Log level', args: { name: 'level', suggestions: [{ name: 'quiet' }, { name: 'error' }, { name: 'warning' }, { name: 'info' }, { name: 'verbose' }, { name: 'debug' }] } },
    { name: '-loglevel', description: 'Log level', args: { name: 'level' } },
    { name: '-hide_banner', description: 'Hide banner' },
    { name: '-show_format', description: 'Show format info' },
    { name: '-show_streams', description: 'Show stream info' },
    { name: '-show_frames', description: 'Show frame info' },
    { name: '-show_packets', description: 'Show packet info' },
    { name: '-show_chapters', description: 'Show chapter info' },
    { name: '-show_programs', description: 'Show program info' },
    { name: '-show_entries', description: 'Show specific entries', args: { name: 'entries' } },
    { name: '-show_data', description: 'Show packet data' },
    { name: '-show_error', description: 'Show probing error' },
    { name: '-count_frames', description: 'Count frames' },
    { name: '-count_packets', description: 'Count packets' },
    { name: '-select_streams', description: 'Select streams', args: { name: 'streams', suggestions: [{ name: 'v' }, { name: 'a' }, { name: 's' }, { name: 'v:0' }, { name: 'a:0' }] } },
    { name: '-of', description: 'Output format', args: { name: 'format', suggestions: [{ name: 'default' }, { name: 'compact' }, { name: 'csv' }, { name: 'flat' }, { name: 'ini' }, { name: 'json' }, { name: 'xml' }] } },
    { name: '-print_format', description: 'Output format', args: { name: 'format', suggestions: [{ name: 'default' }, { name: 'compact' }, { name: 'csv' }, { name: 'flat' }, { name: 'ini' }, { name: 'json' }, { name: 'xml' }] } },
    { name: '-pretty', description: 'Pretty print values' },
    { name: '-sexagesimal', description: 'Use sexagesimal time' },
    { name: '-i', description: 'Input file', args: { name: 'file', template: 'filepaths' } },
    { name: '-h', description: 'Show help' },
    { name: '-help', description: 'Show help' },
    { name: '-version', description: 'Show version' },
  ],
  args: { name: 'input', description: 'Input file', template: 'filepaths' },
};

// Export ffplay as well
export const ffplaySpec: CompletionSpec = {
  name: 'ffplay',
  description: 'FFmpeg media player',
  options: [
    { name: '-x', description: 'Force width', args: { name: 'width' } },
    { name: '-y', description: 'Force height', args: { name: 'height' } },
    { name: '-fs', description: 'Start fullscreen' },
    { name: '-an', description: 'Disable audio' },
    { name: '-vn', description: 'Disable video' },
    { name: '-sn', description: 'Disable subtitles' },
    { name: '-ss', description: 'Start position', args: { name: 'time' } },
    { name: '-t', description: 'Duration', args: { name: 'duration' } },
    { name: '-nodisp', description: 'Disable display' },
    { name: '-noborder', description: 'Borderless window' },
    { name: '-alwaysontop', description: 'Always on top' },
    { name: '-volume', description: 'Initial volume (0-100)', args: { name: 'volume' } },
    { name: '-f', description: 'Force format', args: { name: 'format' } },
    { name: '-window_title', description: 'Window title', args: { name: 'title' } },
    { name: '-left', description: 'Window left position', args: { name: 'pos' } },
    { name: '-top', description: 'Window top position', args: { name: 'pos' } },
    { name: '-loop', description: 'Loop count', args: { name: 'count' } },
    { name: '-showmode', description: 'Show mode', args: { name: 'mode', suggestions: [{ name: '0', description: 'Video' }, { name: '1', description: 'Waves' }, { name: '2', description: 'RDFT' }] } },
    { name: '-vf', description: 'Video filter', args: { name: 'filter' } },
    { name: '-af', description: 'Audio filter', args: { name: 'filter' } },
    { name: '-i', description: 'Input file', args: { name: 'file', template: 'filepaths' } },
    { name: '-autoexit', description: 'Exit at end' },
    { name: '-exitonkeydown', description: 'Exit on key press' },
    { name: '-exitonmousedown', description: 'Exit on mouse click' },
    { name: '-v', description: 'Log level', args: { name: 'level' } },
    { name: '-h', description: 'Show help' },
    { name: '-help', description: 'Show help' },
    { name: '-version', description: 'Show version' },
  ],
  args: { name: 'input', description: 'Input file', template: 'filepaths' },
};
