// flutter - Flutter SDK CLI
import { CompletionSpec } from '../types.js';

export const flutterSpec: CompletionSpec = {
  name: 'flutter',
  description: 'Flutter SDK CLI',
  options: [
    { name: ['-h', '--help'], description: 'Print help' },
    { name: ['-v', '--verbose'], description: 'Verbose output' },
    { name: ['-d', '--device-id'], description: 'Target device ID', args: { name: 'device' } },
    { name: '--version', description: 'Print version' },
    { name: '--suppress-analytics', description: 'Suppress analytics' },
  ],
  subcommands: [
    {
      name: 'create',
      description: 'Create a new Flutter project',
      options: [
        { name: '--project-name', description: 'Project name', args: { name: 'name' } },
        { name: '--org', description: 'Organization identifier', args: { name: 'org' } },
        { name: '--description', description: 'Project description', args: { name: 'desc' } },
        { name: ['-t', '--template'], description: 'Project template', args: { name: 'template', suggestions: [{ name: 'app', description: 'Flutter application' }, { name: 'module', description: 'Flutter module' }, { name: 'package', description: 'Flutter package' }, { name: 'plugin', description: 'Flutter plugin' }, { name: 'plugin_ffi', description: 'FFI plugin' }, { name: 'skeleton', description: 'Skeleton app' }] } },
        { name: ['-s', '--sample'], description: 'Sample ID', args: { name: 'sample' } },
        { name: '--list-samples', description: 'List available samples' },
        { name: ['-e', '--empty'], description: 'Empty application' },
        { name: '--platforms', description: 'Platforms', args: { name: 'platforms', suggestions: [{ name: 'ios' }, { name: 'android' }, { name: 'windows' }, { name: 'linux' }, { name: 'macos' }, { name: 'web' }] } },
        { name: '--pub', description: 'Run pub get' },
        { name: '--no-pub', description: 'Don\'t run pub get' },
        { name: '--offline', description: 'Offline mode' },
        { name: '--overwrite', description: 'Overwrite existing files' },
      ],
      args: { name: 'directory', description: 'Project directory', template: 'folders' },
    },
    {
      name: 'run',
      description: 'Run your Flutter app',
      options: [
        { name: '--debug', description: 'Debug mode' },
        { name: '--profile', description: 'Profile mode' },
        { name: '--release', description: 'Release mode' },
        { name: ['-d', '--device-id'], description: 'Target device', args: { name: 'device' } },
        { name: '--flavor', description: 'Build flavor', args: { name: 'flavor' } },
        { name: ['-t', '--target'], description: 'Target file', args: { name: 'file', template: 'filepaths' } },
        { name: '--observatory-port', description: 'Observatory port', args: { name: 'port' } },
        { name: '--device-vmservice-port', description: 'VM service port', args: { name: 'port' } },
        { name: '--host-vmservice-port', description: 'Host VM service port', args: { name: 'port' } },
        { name: '--pub', description: 'Run pub get' },
        { name: '--no-pub', description: 'Don\'t run pub get' },
        { name: '--track-widget-creation', description: 'Track widget creation' },
        { name: '--no-track-widget-creation', description: 'Don\'t track widget creation' },
        { name: '--hot', description: 'Enable hot reload' },
        { name: '--no-hot', description: 'Disable hot reload' },
        { name: '--start-paused', description: 'Start paused' },
        { name: '--enable-software-rendering', description: 'Software rendering' },
        { name: '--skia-deterministic-rendering', description: 'Deterministic Skia' },
        { name: '--trace-startup', description: 'Trace startup' },
        { name: '--cache-startup-profile', description: 'Cache startup profile' },
        { name: '--verbose-system-logs', description: 'Verbose system logs' },
        { name: '--cache-sksl', description: 'Cache SkSL' },
        { name: '--dump-skp-on-shader-compilation', description: 'Dump SkP on shader compilation' },
        { name: '--purge-persistent-cache', description: 'Purge persistent cache' },
        { name: '--route', description: 'Initial route', args: { name: 'route' } },
        { name: '--endless-trace-buffer', description: 'Endless trace buffer' },
        { name: '--trace-systrace', description: 'Trace systrace' },
        { name: '--trace-skia', description: 'Trace Skia' },
        { name: '--dart-define', description: 'Dart define', args: { name: 'define' } },
        { name: '--dart-define-from-file', description: 'Dart defines from file', args: { name: 'file', template: 'filepaths' } },
        { name: '--web-renderer', description: 'Web renderer', args: { name: 'renderer', suggestions: [{ name: 'auto' }, { name: 'canvaskit' }, { name: 'html' }, { name: 'skwasm' }] } },
        { name: '--web-launch-url', description: 'Web launch URL', args: { name: 'url' } },
        { name: '--device-user', description: 'Device user ID', args: { name: 'id' } },
        { name: '--device-timeout', description: 'Device timeout', args: { name: 'seconds' } },
        { name: '--dds-port', description: 'DDS port', args: { name: 'port' } },
        { name: '--android-project-arg', description: 'Android project arg', args: { name: 'arg' } },
        { name: '--multidex', description: 'Enable multidex' },
        { name: '--no-multidex', description: 'Disable multidex' },
        { name: '--ignore-deprecation', description: 'Ignore deprecation' },
        { name: '--await-first-frame-when-tracing', description: 'Await first frame' },
        { name: '--no-await-first-frame-when-tracing', description: 'Don\'t await first frame' },
        { name: '--use-test-fonts', description: 'Use test fonts' },
        { name: '--no-use-test-fonts', description: 'Don\'t use test fonts' },
        { name: '--build', description: 'Build before running' },
        { name: '--no-build', description: 'Don\'t build before running' },
        { name: '--pid-file', description: 'PID file', args: { name: 'file', template: 'filepaths' } },
      ],
      args: { name: 'target', description: 'Target file', template: 'filepaths', isOptional: true },
    },
    {
      name: 'build',
      description: 'Build Flutter application',
      subcommands: [
        {
          name: 'apk',
          description: 'Build Android APK',
          options: [
            { name: '--debug', description: 'Debug build' },
            { name: '--profile', description: 'Profile build' },
            { name: '--release', description: 'Release build' },
            { name: '--flavor', description: 'Build flavor', args: { name: 'flavor' } },
            { name: '--pub', description: 'Run pub get' },
            { name: '--no-pub', description: 'Don\'t run pub get' },
            { name: '--build-number', description: 'Build number', args: { name: 'number' } },
            { name: '--build-name', description: 'Build name', args: { name: 'name' } },
            { name: '--split-debug-info', description: 'Debug info directory', args: { name: 'dir', template: 'folders' } },
            { name: '--obfuscate', description: 'Obfuscate code' },
            { name: '--dart-define', description: 'Dart define', args: { name: 'define' } },
            { name: '--dart-define-from-file', description: 'Dart defines from file', args: { name: 'file', template: 'filepaths' } },
            { name: '--performance-measurement-file', description: 'Performance file', args: { name: 'file', template: 'filepaths' } },
            { name: '--shrink', description: 'Enable shrinking' },
            { name: '--no-shrink', description: 'Disable shrinking' },
            { name: '--target-platform', description: 'Target platform', args: { name: 'platform', suggestions: [{ name: 'android-arm' }, { name: 'android-arm64' }, { name: 'android-x86' }, { name: 'android-x64' }] } },
            { name: '--split-per-abi', description: 'Split by ABI' },
            { name: '--no-split-per-abi', description: 'Don\'t split by ABI' },
            { name: '--track-widget-creation', description: 'Track widget creation' },
            { name: '--tree-shake-icons', description: 'Tree-shake icons' },
            { name: '--no-tree-shake-icons', description: 'Don\'t tree-shake icons' },
            { name: ['-t', '--target'], description: 'Target file', args: { name: 'file', template: 'filepaths' } },
            { name: '--analyze-size', description: 'Analyze size' },
            { name: '--multidex', description: 'Enable multidex' },
            { name: '--no-multidex', description: 'Disable multidex' },
          ],
        },
        {
          name: 'appbundle',
          description: 'Build Android App Bundle',
          options: [
            { name: '--debug', description: 'Debug build' },
            { name: '--profile', description: 'Profile build' },
            { name: '--release', description: 'Release build' },
            { name: '--flavor', description: 'Build flavor', args: { name: 'flavor' } },
            { name: '--build-number', description: 'Build number', args: { name: 'number' } },
            { name: '--build-name', description: 'Build name', args: { name: 'name' } },
            { name: '--shrink', description: 'Enable shrinking' },
            { name: '--target-platform', description: 'Target platform', args: { name: 'platform' } },
            { name: '--dart-define', description: 'Dart define', args: { name: 'define' } },
            { name: '--dart-define-from-file', description: 'Dart defines from file', args: { name: 'file', template: 'filepaths' } },
            { name: '--obfuscate', description: 'Obfuscate code' },
            { name: '--split-debug-info', description: 'Debug info directory', args: { name: 'dir', template: 'folders' } },
            { name: ['-t', '--target'], description: 'Target file', args: { name: 'file', template: 'filepaths' } },
            { name: '--analyze-size', description: 'Analyze size' },
            { name: '--tree-shake-icons', description: 'Tree-shake icons' },
          ],
        },
        {
          name: 'ios',
          description: 'Build iOS application',
          options: [
            { name: '--debug', description: 'Debug build' },
            { name: '--profile', description: 'Profile build' },
            { name: '--release', description: 'Release build' },
            { name: '--simulator', description: 'Build for simulator' },
            { name: '--no-simulator', description: 'Build for device' },
            { name: '--codesign', description: 'Enable code signing' },
            { name: '--no-codesign', description: 'Disable code signing' },
            { name: '--config-only', description: 'Generate config only' },
            { name: '--export-options-plist', description: 'Export options plist', args: { name: 'file', template: 'filepaths' } },
            { name: '--flavor', description: 'Build flavor', args: { name: 'flavor' } },
            { name: '--build-number', description: 'Build number', args: { name: 'number' } },
            { name: '--build-name', description: 'Build name', args: { name: 'name' } },
            { name: '--dart-define', description: 'Dart define', args: { name: 'define' } },
            { name: '--dart-define-from-file', description: 'Dart defines from file', args: { name: 'file', template: 'filepaths' } },
            { name: '--obfuscate', description: 'Obfuscate code' },
            { name: '--split-debug-info', description: 'Debug info directory', args: { name: 'dir', template: 'folders' } },
            { name: ['-t', '--target'], description: 'Target file', args: { name: 'file', template: 'filepaths' } },
            { name: '--analyze-size', description: 'Analyze size' },
            { name: '--tree-shake-icons', description: 'Tree-shake icons' },
          ],
        },
        {
          name: 'ipa',
          description: 'Build iOS IPA',
          options: [
            { name: '--debug', description: 'Debug build' },
            { name: '--profile', description: 'Profile build' },
            { name: '--release', description: 'Release build' },
            { name: '--export-method', description: 'Export method', args: { name: 'method', suggestions: [{ name: 'app-store' }, { name: 'ad-hoc' }, { name: 'development' }, { name: 'enterprise' }] } },
            { name: '--export-options-plist', description: 'Export options plist', args: { name: 'file', template: 'filepaths' } },
            { name: '--flavor', description: 'Build flavor', args: { name: 'flavor' } },
            { name: '--build-number', description: 'Build number', args: { name: 'number' } },
            { name: '--build-name', description: 'Build name', args: { name: 'name' } },
            { name: '--dart-define', description: 'Dart define', args: { name: 'define' } },
            { name: '--dart-define-from-file', description: 'Dart defines from file', args: { name: 'file', template: 'filepaths' } },
            { name: '--obfuscate', description: 'Obfuscate code' },
            { name: '--split-debug-info', description: 'Debug info directory', args: { name: 'dir', template: 'folders' } },
            { name: ['-t', '--target'], description: 'Target file', args: { name: 'file', template: 'filepaths' } },
            { name: '--analyze-size', description: 'Analyze size' },
            { name: '--tree-shake-icons', description: 'Tree-shake icons' },
          ],
        },
        {
          name: 'web',
          description: 'Build web application',
          options: [
            { name: '--release', description: 'Release build' },
            { name: '--profile', description: 'Profile build' },
            { name: '--dart-define', description: 'Dart define', args: { name: 'define' } },
            { name: '--dart-define-from-file', description: 'Dart defines from file', args: { name: 'file', template: 'filepaths' } },
            { name: '--web-renderer', description: 'Web renderer', args: { name: 'renderer', suggestions: [{ name: 'auto' }, { name: 'canvaskit' }, { name: 'html' }, { name: 'skwasm' }] } },
            { name: '--base-href', description: 'Base href', args: { name: 'href' } },
            { name: '--pwa-strategy', description: 'PWA strategy', args: { name: 'strategy', suggestions: [{ name: 'none' }, { name: 'offline-first' }] } },
            { name: ['-o', '--output'], description: 'Output directory', args: { name: 'dir', template: 'folders' } },
            { name: ['-t', '--target'], description: 'Target file', args: { name: 'file', template: 'filepaths' } },
            { name: '--source-maps', description: 'Generate source maps' },
            { name: '--no-source-maps', description: 'Don\'t generate source maps' },
            { name: '--tree-shake-icons', description: 'Tree-shake icons' },
          ],
        },
        {
          name: 'macos',
          description: 'Build macOS application',
          options: [
            { name: '--debug', description: 'Debug build' },
            { name: '--profile', description: 'Profile build' },
            { name: '--release', description: 'Release build' },
            { name: '--flavor', description: 'Build flavor', args: { name: 'flavor' } },
            { name: '--config-only', description: 'Generate config only' },
            { name: '--build-number', description: 'Build number', args: { name: 'number' } },
            { name: '--build-name', description: 'Build name', args: { name: 'name' } },
            { name: '--dart-define', description: 'Dart define', args: { name: 'define' } },
            { name: '--dart-define-from-file', description: 'Dart defines from file', args: { name: 'file', template: 'filepaths' } },
            { name: '--obfuscate', description: 'Obfuscate code' },
            { name: '--split-debug-info', description: 'Debug info directory', args: { name: 'dir', template: 'folders' } },
            { name: ['-t', '--target'], description: 'Target file', args: { name: 'file', template: 'filepaths' } },
            { name: '--tree-shake-icons', description: 'Tree-shake icons' },
          ],
        },
        {
          name: 'linux',
          description: 'Build Linux application',
          options: [
            { name: '--debug', description: 'Debug build' },
            { name: '--profile', description: 'Profile build' },
            { name: '--release', description: 'Release build' },
            { name: '--target-platform', description: 'Target platform', args: { name: 'platform', suggestions: [{ name: 'linux-x64' }, { name: 'linux-arm64' }] } },
            { name: '--target-sysroot', description: 'Target sysroot', args: { name: 'path', template: 'folders' } },
            { name: '--build-number', description: 'Build number', args: { name: 'number' } },
            { name: '--build-name', description: 'Build name', args: { name: 'name' } },
            { name: '--dart-define', description: 'Dart define', args: { name: 'define' } },
            { name: '--dart-define-from-file', description: 'Dart defines from file', args: { name: 'file', template: 'filepaths' } },
            { name: '--obfuscate', description: 'Obfuscate code' },
            { name: '--split-debug-info', description: 'Debug info directory', args: { name: 'dir', template: 'folders' } },
            { name: ['-t', '--target'], description: 'Target file', args: { name: 'file', template: 'filepaths' } },
            { name: '--tree-shake-icons', description: 'Tree-shake icons' },
          ],
        },
        {
          name: 'windows',
          description: 'Build Windows application',
          options: [
            { name: '--debug', description: 'Debug build' },
            { name: '--profile', description: 'Profile build' },
            { name: '--release', description: 'Release build' },
            { name: '--build-number', description: 'Build number', args: { name: 'number' } },
            { name: '--build-name', description: 'Build name', args: { name: 'name' } },
            { name: '--dart-define', description: 'Dart define', args: { name: 'define' } },
            { name: '--dart-define-from-file', description: 'Dart defines from file', args: { name: 'file', template: 'filepaths' } },
            { name: '--obfuscate', description: 'Obfuscate code' },
            { name: '--split-debug-info', description: 'Debug info directory', args: { name: 'dir', template: 'folders' } },
            { name: ['-t', '--target'], description: 'Target file', args: { name: 'file', template: 'filepaths' } },
            { name: '--tree-shake-icons', description: 'Tree-shake icons' },
          ],
        },
        { name: 'aar', description: 'Build Android Archive', options: [{ name: '--debug' }, { name: '--profile' }, { name: '--release' }, { name: '--build-number', args: { name: 'number' } }, { name: '--output-dir', args: { name: 'dir', template: 'folders' } }, { name: ['-t', '--target'], args: { name: 'file', template: 'filepaths' } }] },
        { name: 'bundle', description: 'Build Flutter assets', options: [{ name: '--debug' }, { name: '--profile' }, { name: '--release' }, { name: '--depfile', args: { name: 'file', template: 'filepaths' } }, { name: '--target-platform', args: { name: 'platform' } }, { name: ['-t', '--target'], args: { name: 'file', template: 'filepaths' } }, { name: '--asset-dir', args: { name: 'dir', template: 'folders' } }] },
      ],
    },
    {
      name: 'test',
      description: 'Run Flutter unit tests',
      options: [
        { name: '--pub', description: 'Run pub get' },
        { name: '--no-pub', description: 'Don\'t run pub get' },
        { name: '--name', description: 'Test name pattern', args: { name: 'pattern' } },
        { name: '--plain-name', description: 'Test name substring', args: { name: 'substring' } },
        { name: '--tags', description: 'Test tags', args: { name: 'tags' } },
        { name: '--exclude-tags', description: 'Exclude tags', args: { name: 'tags' } },
        { name: '--start-paused', description: 'Start paused' },
        { name: '--run-skipped', description: 'Run skipped tests' },
        { name: '--coverage', description: 'Collect coverage' },
        { name: '--coverage-path', description: 'Coverage path', args: { name: 'path', template: 'folders' } },
        { name: '--merge-coverage', description: 'Merge coverage' },
        { name: '--coverage-package', description: 'Coverage package', args: { name: 'package' } },
        { name: '--test-randomize-ordering-seed', description: 'Randomize seed', args: { name: 'seed' } },
        { name: '--total-shards', description: 'Total shards', args: { name: 'count' } },
        { name: '--shard-index', description: 'Shard index', args: { name: 'index' } },
        { name: ['-r', '--reporter'], description: 'Reporter', args: { name: 'reporter', suggestions: [{ name: 'compact' }, { name: 'expanded' }, { name: 'github' }, { name: 'json' }] } },
        { name: '--file-reporter', description: 'File reporter', args: { name: 'reporter' } },
        { name: '--timeout', description: 'Test timeout', args: { name: 'timeout' } },
        { name: ['-j', '--concurrency'], description: 'Concurrency', args: { name: 'count' } },
        { name: '--test-assets', description: 'Build test assets' },
        { name: '--no-test-assets', description: 'Don\'t build test assets' },
        { name: '--track-widget-creation', description: 'Track widget creation' },
        { name: '--update-goldens', description: 'Update golden files' },
        { name: ['-d', '--device-id'], description: 'Target device', args: { name: 'device' } },
        { name: '--flavor', description: 'Build flavor', args: { name: 'flavor' } },
        { name: '--dart-define', description: 'Dart define', args: { name: 'define' } },
        { name: '--web-renderer', description: 'Web renderer', args: { name: 'renderer', suggestions: [{ name: 'auto' }, { name: 'canvaskit' }, { name: 'html' }, { name: 'skwasm' }] } },
      ],
      args: { name: 'targets', description: 'Test files or directories', template: 'filepaths', isOptional: true, isVariadic: true },
    },
    {
      name: 'analyze',
      description: 'Analyze Dart code',
      options: [
        { name: '--current-package', description: 'Analyze current package' },
        { name: '--no-current-package', description: 'Don\'t analyze current package' },
        { name: '--fatal-infos', description: 'Treat infos as fatal' },
        { name: '--no-fatal-infos', description: 'Don\'t treat infos as fatal' },
        { name: '--fatal-warnings', description: 'Treat warnings as fatal' },
        { name: '--no-fatal-warnings', description: 'Don\'t treat warnings as fatal' },
        { name: '--write', description: 'Write results to file', args: { name: 'file', template: 'filepaths' } },
        { name: '--suggestions', description: 'Show suggestions' },
        { name: '--no-suggestions', description: 'Don\'t show suggestions' },
        { name: '--watch', description: 'Watch for changes' },
        { name: '--preamble', description: 'Show preamble' },
        { name: '--no-preamble', description: 'Don\'t show preamble' },
        { name: '--congratulate', description: 'Show success message' },
        { name: '--no-congratulate', description: 'Don\'t show success message' },
      ],
      args: { name: 'directories', description: 'Directories to analyze', template: 'folders', isOptional: true, isVariadic: true },
    },
    { name: 'clean', description: 'Delete build/ and .dart_tool/ directories' },
    {
      name: 'doctor',
      description: 'Show environment diagnostic information',
      options: [
        { name: '--android-licenses', description: 'Run Android license manager' },
        { name: '--verbose', description: 'Verbose output' },
      ],
    },
    {
      name: 'devices',
      description: 'List all connected devices',
      options: [
        { name: '--machine', description: 'Output machine-readable JSON' },
        { name: '--timeout', description: 'Timeout', args: { name: 'seconds' } },
        { name: '--device-connection', description: 'Connection type', args: { name: 'type', suggestions: [{ name: 'attached' }, { name: 'wireless' }] } },
      ],
    },
    {
      name: 'pub',
      description: 'Commands for managing packages',
      subcommands: [
        { name: 'add', description: 'Add a dependency', options: [{ name: '--dev', description: 'Add as dev dependency' }, { name: ['-d', '--dev'], description: 'Add as dev dependency' }, { name: '--git-url', args: { name: 'url' } }, { name: '--git-ref', args: { name: 'ref' } }, { name: '--git-path', args: { name: 'path' } }, { name: '--hosted-url', args: { name: 'url' } }, { name: '--path', args: { name: 'path', template: 'folders' } }, { name: '--sdk', args: { name: 'sdk' } }, { name: ['-C', '--directory'], args: { name: 'dir', template: 'folders' } }, { name: '--offline' }, { name: '--no-offline' }, { name: '-n', description: 'Dry run' }, { name: '--precompile' }, { name: '--no-precompile' }], args: { name: 'packages', isVariadic: true } },
        { name: 'cache', description: 'Work with pub cache', subcommands: [{ name: 'add', description: 'Install package to cache', options: [{ name: '--version', args: { name: 'version' } }, { name: '--all' }], args: { name: 'package' } }, { name: 'clean', description: 'Delete packages from cache' }, { name: 'repair', description: 'Reinstall cached packages' }] },
        { name: 'deps', description: 'Print package dependencies', options: [{ name: '--style', args: { name: 'style', suggestions: [{ name: 'compact' }, { name: 'tree' }, { name: 'list' }] } }, { name: ['-C', '--directory'], args: { name: 'dir', template: 'folders' } }, { name: '--json' }, { name: '--no-dev' }, { name: '--executables' }] },
        { name: 'downgrade', description: 'Downgrade dependencies', options: [{ name: '--offline' }, { name: '--dry-run' }, { name: ['-C', '--directory'], args: { name: 'dir', template: 'folders' } }] },
        { name: 'get', description: 'Get dependencies', options: [{ name: '--offline' }, { name: '--no-offline' }, { name: '--dry-run' }, { name: '--enforce-lockfile' }, { name: '--precompile' }, { name: '--no-precompile' }, { name: ['-C', '--directory'], args: { name: 'dir', template: 'folders' } }] },
        { name: 'global', description: 'Work with global packages', subcommands: [{ name: 'activate', description: 'Activate a global package', options: [{ name: '--source', args: { name: 'source', suggestions: [{ name: 'git' }, { name: 'hosted' }, { name: 'path' }] } }, { name: ['-u', '--overwrite'] }, { name: '--git-path', args: { name: 'path' } }, { name: '--git-ref', args: { name: 'ref' } }, { name: ['-x', '--executable'], args: { name: 'executable' } }], args: { name: 'package' } }, { name: 'deactivate', description: 'Deactivate a global package', args: { name: 'package' } }, { name: 'list', description: 'List global packages' }, { name: 'run', description: 'Run a global package', args: [{ name: 'package' }, { name: 'args', isOptional: true, isVariadic: true }] }] },
        { name: 'outdated', description: 'Analyze dependencies for upgrades', options: [{ name: '--json' }, { name: '--no-color' }, { name: '--up-to-date' }, { name: '--no-up-to-date' }, { name: '--prereleases' }, { name: '--no-prereleases' }, { name: '--show-all' }, { name: '--no-show-all' }, { name: '--transitive' }, { name: '--no-transitive' }, { name: '--dev-dependencies' }, { name: '--no-dev-dependencies' }, { name: '--dependency-overrides' }, { name: '--no-dependency-overrides' }, { name: ['-C', '--directory'], args: { name: 'dir', template: 'folders' } }, { name: '--mode', args: { name: 'mode', suggestions: [{ name: 'null-safety' }] } }] },
        { name: 'publish', description: 'Publish package to pub.dev', options: [{ name: ['-n', '--dry-run'] }, { name: ['-f', '--force'] }, { name: '--skip-validation' }, { name: ['-C', '--directory'], args: { name: 'dir', template: 'folders' } }] },
        { name: 'remove', description: 'Remove a dependency', options: [{ name: '--offline' }, { name: ['-n', '--dry-run'] }, { name: '--precompile' }, { name: '--no-precompile' }, { name: ['-C', '--directory'], args: { name: 'dir', template: 'folders' } }], args: { name: 'packages', isVariadic: true } },
        { name: 'run', description: 'Run an executable', args: [{ name: 'executable' }, { name: 'args', isOptional: true, isVariadic: true }] },
        { name: 'token', description: 'Manage pub.dev credentials', subcommands: [{ name: 'add', description: 'Add credential', args: { name: 'hosted-url' } }, { name: 'list', description: 'List credentials' }, { name: 'remove', description: 'Remove credential', options: [{ name: '--all' }], args: { name: 'hosted-url', isOptional: true } }] },
        { name: 'upgrade', description: 'Upgrade dependencies', options: [{ name: '--offline' }, { name: '--dry-run' }, { name: '--precompile' }, { name: '--no-precompile' }, { name: '--null-safety' }, { name: '--major-versions' }, { name: '--tighten' }, { name: ['-C', '--directory'], args: { name: 'dir', template: 'folders' } }], args: { name: 'packages', isOptional: true, isVariadic: true } },
        { name: 'version', description: 'Print pub version' },
      ],
    },
    {
      name: 'channel',
      description: 'List or switch Flutter channels',
      args: { name: 'channel', description: 'Channel to switch to', isOptional: true, suggestions: [{ name: 'stable', description: 'Stable channel' }, { name: 'beta', description: 'Beta channel' }, { name: 'master', description: 'Master channel' }] },
    },
    { name: 'config', description: 'Configure Flutter settings', options: [{ name: '--enable-web', description: 'Enable web support' }, { name: '--no-enable-web', description: 'Disable web support' }, { name: '--enable-linux-desktop', description: 'Enable Linux desktop' }, { name: '--no-enable-linux-desktop', description: 'Disable Linux desktop' }, { name: '--enable-macos-desktop', description: 'Enable macOS desktop' }, { name: '--no-enable-macos-desktop', description: 'Disable macOS desktop' }, { name: '--enable-windows-desktop', description: 'Enable Windows desktop' }, { name: '--no-enable-windows-desktop', description: 'Disable Windows desktop' }, { name: '--android-sdk', description: 'Android SDK path', args: { name: 'path', template: 'folders' } }, { name: '--android-studio-dir', description: 'Android Studio path', args: { name: 'path', template: 'folders' } }, { name: '--clear-features', description: 'Clear feature flags' }, { name: '--list', description: 'List settings' }] },
    { name: 'upgrade', description: 'Upgrade Flutter SDK', options: [{ name: '--force', description: 'Force upgrade' }, { name: '--verify-only', description: 'Verify only' }] },
    { name: 'downgrade', description: 'Downgrade Flutter SDK' },
    { name: 'precache', description: 'Populate Flutter tool cache', options: [{ name: '--all-platforms', description: 'Precache for all platforms' }, { name: ['-f', '--force'], description: 'Force download' }, { name: ['-a', '--android'], description: 'Precache Android' }, { name: '--no-android', description: 'Skip Android' }, { name: '--android_gen_snapshot', description: 'Precache gen_snapshot' }, { name: '--android_maven', description: 'Precache Maven' }, { name: '--android_internal_build', description: 'Precache internal build' }, { name: '--ios', description: 'Precache iOS' }, { name: '--no-ios', description: 'Skip iOS' }, { name: '--web', description: 'Precache web' }, { name: '--no-web', description: 'Skip web' }, { name: '--linux', description: 'Precache Linux' }, { name: '--no-linux', description: 'Skip Linux' }, { name: '--windows', description: 'Precache Windows' }, { name: '--no-windows', description: 'Skip Windows' }, { name: '--macos', description: 'Precache macOS' }, { name: '--no-macos', description: 'Skip macOS' }, { name: '--fuchsia', description: 'Precache Fuchsia' }, { name: '--no-fuchsia', description: 'Skip Fuchsia' }, { name: '--universal', description: 'Precache universal' }, { name: '--no-universal', description: 'Skip universal' }] },
    { name: 'emulators', description: 'List or create emulators', options: [{ name: '--launch', description: 'Launch emulator', args: { name: 'emulator' } }, { name: '--cold', description: 'Cold boot' }, { name: '--create', description: 'Create emulator' }, { name: '--name', description: 'Emulator name', args: { name: 'name' } }] },
    { name: 'install', description: 'Install app on device', options: [{ name: ['-d', '--device-id'], description: 'Target device', args: { name: 'device' } }, { name: '--device-user', description: 'Device user', args: { name: 'user' } }, { name: '--device-timeout', description: 'Timeout', args: { name: 'seconds' } }, { name: '--uninstall-only', description: 'Only uninstall' }, { name: ['-t', '--target'], description: 'Target file', args: { name: 'file', template: 'filepaths' } }, { name: '--flavor', description: 'Build flavor', args: { name: 'flavor' } }, { name: '--debug', description: 'Debug build' }, { name: '--profile', description: 'Profile build' }, { name: '--release', description: 'Release build' }] },
    { name: 'attach', description: 'Attach to running app', options: [{ name: '--debug', description: 'Debug mode' }, { name: '--profile', description: 'Profile mode' }, { name: ['-d', '--device-id'], description: 'Target device', args: { name: 'device' } }, { name: '--debug-uri', description: 'Debug URI', args: { name: 'uri' } }, { name: '--app-id', description: 'App ID', args: { name: 'id' } }, { name: '--pid-file', description: 'PID file', args: { name: 'file', template: 'filepaths' } }, { name: '--track-widget-creation', description: 'Track widget creation' }, { name: ['-t', '--target'], description: 'Target file', args: { name: 'file', template: 'filepaths' } }] },
    { name: 'logs', description: 'Show device logs', options: [{ name: ['-d', '--device-id'], description: 'Target device', args: { name: 'device' } }, { name: ['-c', '--clear'], description: 'Clear existing logs' }, { name: '--device-timeout', description: 'Timeout', args: { name: 'seconds' } }] },
    { name: 'drive', description: 'Run Flutter integration tests', options: [{ name: ['-d', '--device-id'], description: 'Target device', args: { name: 'device' } }, { name: '--driver', description: 'Driver script', args: { name: 'file', template: 'filepaths' } }, { name: '--driver-port', description: 'Driver port', args: { name: 'port' } }, { name: ['-t', '--target'], description: 'Target file', args: { name: 'file', template: 'filepaths' } }, { name: '--screenshot', description: 'Screenshot directory', args: { name: 'dir', template: 'folders' } }, { name: '--debug', description: 'Debug mode' }, { name: '--profile', description: 'Profile mode' }, { name: '--release', description: 'Release mode' }, { name: '--flavor', description: 'Build flavor', args: { name: 'flavor' } }, { name: '--use-existing-app', description: 'Use existing app', args: { name: 'uri' } }, { name: '--keep-app-running', description: 'Keep app running' }, { name: '--browser-name', description: 'Browser', args: { name: 'browser', suggestions: [{ name: 'chrome' }, { name: 'edge' }, { name: 'firefox' }, { name: 'ios-safari' }, { name: 'safari' }] } }, { name: '--browser-dimension', description: 'Browser dimensions', args: { name: 'dimensions' } }, { name: '--headless', description: 'Headless mode' }, { name: '--no-headless', description: 'No headless mode' }, { name: '--web-port', description: 'Web port', args: { name: 'port' } }, { name: '--android-emulator', description: 'Use Android emulator' }, { name: '--chrome-binary', description: 'Chrome binary', args: { name: 'path', template: 'filepaths' } }] },
    { name: 'symbolize', description: 'Symbolize stack traces', options: [{ name: '--debug-info', description: 'Debug info', args: { name: 'file', template: 'filepaths' } }, { name: ['-i', '--input'], description: 'Input file', args: { name: 'file', template: 'filepaths' } }, { name: ['-o', '--output'], description: 'Output file', args: { name: 'file', template: 'filepaths' } }] },
    { name: 'screenshot', description: 'Take a screenshot', options: [{ name: ['-o', '--out'], description: 'Output file', args: { name: 'file', template: 'filepaths' } }, { name: '--observatory-uri', description: 'Observatory URI', args: { name: 'uri' } }, { name: '--type', description: 'Screenshot type', args: { name: 'type', suggestions: [{ name: 'device' }, { name: 'rasterizer' }, { name: 'skia' }] } }, { name: ['-d', '--device-id'], description: 'Target device', args: { name: 'device' } }] },
    { name: 'gen-l10n', description: 'Generate localization files', options: [{ name: '--arb-dir', description: 'ARB directory', args: { name: 'dir', template: 'folders' } }, { name: '--output-dir', description: 'Output directory', args: { name: 'dir', template: 'folders' } }, { name: '--template-arb-file', description: 'Template ARB file', args: { name: 'file', template: 'filepaths' } }, { name: '--output-localization-file', description: 'Output file', args: { name: 'file' } }, { name: '--untranslated-messages-file', description: 'Untranslated messages file', args: { name: 'file', template: 'filepaths' } }, { name: '--output-class', description: 'Output class name', args: { name: 'name' } }, { name: '--header', description: 'File header', args: { name: 'header' } }, { name: '--header-file', description: 'Header file', args: { name: 'file', template: 'filepaths' } }, { name: '--use-deferred-loading', description: 'Use deferred loading' }, { name: '--gen-inputs-and-outputs-list', description: 'Generate inputs/outputs list', args: { name: 'file', template: 'filepaths' } }, { name: '--synthetic-package', description: 'Generate synthetic package' }, { name: '--no-synthetic-package', description: 'Don\'t generate synthetic package' }, { name: '--project-dir', description: 'Project directory', args: { name: 'dir', template: 'folders' } }, { name: '--required-resource-attributes', description: 'Require resource attributes' }, { name: '--nullable-getter', description: 'Nullable getter' }, { name: '--no-nullable-getter', description: 'Non-nullable getter' }, { name: '--format', description: 'Format output' }, { name: '--no-format', description: 'Don\'t format output' }, { name: '--use-escaping', description: 'Use escaping' }, { name: '--no-use-escaping', description: 'Don\'t use escaping' }, { name: '--suppress-warnings', description: 'Suppress warnings' }] },
    { name: 'custom-devices', description: 'List and configure custom devices', subcommands: [{ name: 'add', description: 'Add custom device' }, { name: 'delete', description: 'Delete custom device', args: { name: 'device-id' } }, { name: 'list', description: 'List custom devices' }, { name: 'reset', description: 'Reset custom devices' }] },
  ],
};
