// gpg - GNU Privacy Guard (GnuPG)
import { CompletionSpec } from '../types.js';

export const gpgSpec: CompletionSpec = {
  name: 'gpg',
  description: 'OpenPGP encryption and signing tool',
  options: [
    // Commands
    { name: ['-s', '--sign'], description: 'Sign a message' },
    { name: '--clear-sign', description: 'Make a clear text signature' },
    { name: ['-b', '--detach-sign'], description: 'Make a detached signature' },
    { name: ['-e', '--encrypt'], description: 'Encrypt data' },
    { name: ['-c', '--symmetric'], description: 'Symmetric encryption only' },
    { name: ['-d', '--decrypt'], description: 'Decrypt data' },
    { name: '--verify', description: 'Verify a signature' },
    { name: '-k', description: 'List keys' },
    { name: '--list-keys', description: 'List public keys' },
    { name: '-K', description: 'List secret keys' },
    { name: '--list-secret-keys', description: 'List secret keys' },
    { name: '--list-signatures', description: 'List keys and signatures' },
    { name: '--list-sigs', description: 'List keys and signatures' },
    { name: '--check-signatures', description: 'List and check signatures' },
    { name: '--check-sigs', description: 'List and check signatures' },
    { name: '--fingerprint', description: 'Show fingerprints' },
    { name: '--gen-key', description: 'Generate a new key pair' },
    { name: '--full-generate-key', description: 'Full featured key generation' },
    { name: '--quick-generate-key', description: 'Quick key generation', args: { name: 'user-id' } },
    { name: '--quick-add-uid', description: 'Add user ID to key', args: [{ name: 'key' }, { name: 'user-id' }] },
    { name: '--quick-revoke-uid', description: 'Revoke user ID', args: [{ name: 'key' }, { name: 'user-id' }] },
    { name: '--quick-set-expire', description: 'Set key expiration', args: [{ name: 'key' }, { name: 'expire' }] },
    { name: '--quick-add-key', description: 'Add subkey to key', args: { name: 'key' } },
    { name: '--gen-revoke', description: 'Generate revocation certificate', args: { name: 'key' } },
    { name: '--desig-revoke', description: 'Generate designated revocation certificate', args: { name: 'key' } },
    { name: '--edit-key', description: 'Edit a key', args: { name: 'key' } },
    { name: '--passwd', description: 'Change passphrase', args: { name: 'key' } },
    { name: '--sign-key', description: 'Sign a public key', args: { name: 'key' } },
    { name: '--lsign-key', description: 'Locally sign a public key', args: { name: 'key' } },
    { name: '--quick-sign-key', description: 'Quickly sign a key', args: { name: 'key' } },
    { name: '--quick-lsign-key', description: 'Quickly locally sign a key', args: { name: 'key' } },
    { name: '--delete-key', description: 'Delete a public key', args: { name: 'key' } },
    { name: '--delete-secret-key', description: 'Delete a secret key', args: { name: 'key' } },
    { name: '--delete-secret-and-public-key', description: 'Delete secret and public key', args: { name: 'key' } },
    { name: '--export', description: 'Export public keys', args: { name: 'keys', isOptional: true, isVariadic: true } },
    { name: '--send-keys', description: 'Send keys to keyserver', args: { name: 'keys', isVariadic: true } },
    { name: '--export-secret-keys', description: 'Export secret keys', args: { name: 'keys', isOptional: true, isVariadic: true } },
    { name: '--export-secret-subkeys', description: 'Export secret subkeys', args: { name: 'keys', isOptional: true, isVariadic: true } },
    { name: '--export-ssh-key', description: 'Export SSH public key', args: { name: 'key' } },
    { name: '--import', description: 'Import keys', args: { name: 'files', template: 'filepaths', isVariadic: true } },
    { name: '--receive-keys', description: 'Receive keys from keyserver', args: { name: 'key-ids', isVariadic: true } },
    { name: '--recv-keys', description: 'Receive keys from keyserver', args: { name: 'key-ids', isVariadic: true } },
    { name: '--refresh-keys', description: 'Refresh keys from keyserver', args: { name: 'keys', isOptional: true, isVariadic: true } },
    { name: '--search-keys', description: 'Search keyserver', args: { name: 'names', isVariadic: true } },
    { name: '--fetch-keys', description: 'Fetch keys from URLs', args: { name: 'urls', isVariadic: true } },
    { name: '--update-trustdb', description: 'Update trust database' },
    { name: '--check-trustdb', description: 'Check trust database' },
    { name: '--export-ownertrust', description: 'Export ownertrust values' },
    { name: '--import-ownertrust', description: 'Import ownertrust values', args: { name: 'file', template: 'filepaths', isOptional: true } },
    { name: '--card-status', description: 'Show smartcard status' },
    { name: '--card-edit', description: 'Edit smartcard' },
    { name: '--change-pin', description: 'Change smartcard PIN' },

    // Options
    { name: ['-a', '--armor'], description: 'ASCII armored output' },
    { name: ['-r', '--recipient'], description: 'Encrypt for recipient', args: { name: 'name' }, isRepeatable: true },
    { name: '--hidden-recipient', description: 'Hidden recipient', args: { name: 'name' }, isRepeatable: true },
    { name: ['-u', '--local-user'], description: 'Use this key for signing', args: { name: 'name' } },
    { name: '--default-key', description: 'Default key for signing', args: { name: 'name' } },
    { name: '--default-recipient', description: 'Default recipient', args: { name: 'name' } },
    { name: '--default-recipient-self', description: 'Use default key as recipient' },
    { name: '--no-default-recipient', description: 'No default recipient' },
    { name: ['-o', '--output'], description: 'Output file', args: { name: 'file', template: 'filepaths' } },
    { name: '--compress-algo', description: 'Compression algorithm', args: { name: 'algo', suggestions: [{ name: 'none' }, { name: 'uncompressed' }, { name: 'zip' }, { name: 'zlib' }, { name: 'bzip2' }] } },
    { name: '-z', description: 'Compression level', args: { name: 'level' } },
    { name: '--cipher-algo', description: 'Cipher algorithm', args: { name: 'algo', suggestions: [{ name: 'AES256' }, { name: 'AES192' }, { name: 'AES' }, { name: '3DES' }, { name: 'CAMELLIA256' }, { name: 'CAMELLIA192' }, { name: 'CAMELLIA128' }, { name: 'TWOFISH' }, { name: 'BLOWFISH' }] } },
    { name: '--digest-algo', description: 'Digest algorithm', args: { name: 'algo', suggestions: [{ name: 'SHA512' }, { name: 'SHA384' }, { name: 'SHA256' }, { name: 'SHA224' }, { name: 'SHA1' }, { name: 'RIPEMD160' }] } },
    { name: '--cert-digest-algo', description: 'Certificate digest algorithm', args: { name: 'algo' } },
    { name: '--s2k-mode', description: 'String-to-key mode', args: { name: 'mode', suggestions: [{ name: '0', description: 'Simple' }, { name: '1', description: 'Salted' }, { name: '3', description: 'Iterated' }] } },
    { name: '--s2k-digest-algo', description: 'String-to-key digest', args: { name: 'algo' } },
    { name: '--s2k-cipher-algo', description: 'String-to-key cipher', args: { name: 'algo' } },
    { name: '--s2k-count', description: 'String-to-key iterations', args: { name: 'count' } },
    { name: '--passphrase', description: 'Passphrase', args: { name: 'string' } },
    { name: '--passphrase-fd', description: 'Passphrase file descriptor', args: { name: 'fd' } },
    { name: '--passphrase-file', description: 'Passphrase file', args: { name: 'file', template: 'filepaths' } },
    { name: '--passphrase-repeat', description: 'Repeat passphrase', args: { name: 'n' } },
    { name: '--pinentry-mode', description: 'Pinentry mode', args: { name: 'mode', suggestions: [{ name: 'default' }, { name: 'ask' }, { name: 'cancel' }, { name: 'error' }, { name: 'loopback' }] } },
    { name: '--batch', description: 'Batch mode' },
    { name: '--no-batch', description: 'Disable batch mode' },
    { name: '--yes', description: 'Assume yes' },
    { name: '--no', description: 'Assume no' },
    { name: ['-i', '--interactive'], description: 'Interactive mode' },
    { name: ['-t', '--textmode'], description: 'Text mode' },
    { name: ['-n', '--dry-run'], description: 'Dry run' },
    { name: '--list-only', description: 'List packets only' },
    { name: ['-v', '--verbose'], description: 'Verbose', isRepeatable: true },
    { name: ['-q', '--quiet'], description: 'Quiet' },
    { name: '--no-tty', description: 'No TTY' },
    { name: '--force-mdc', description: 'Force MDC encryption' },
    { name: '--disable-mdc', description: 'Disable MDC' },
    { name: '--force-aead', description: 'Force AEAD encryption' },
    { name: '--disable-signer-uid', description: 'Disable signer UID' },
    { name: '--include-key-block', description: 'Include key block in signature' },
    { name: '--no-include-key-block', description: 'Don\'t include key block' },
    { name: '--personal-cipher-preferences', description: 'Personal cipher preferences', args: { name: 'algos' } },
    { name: '--personal-digest-preferences', description: 'Personal digest preferences', args: { name: 'algos' } },
    { name: '--personal-compress-preferences', description: 'Personal compression preferences', args: { name: 'algos' } },
    { name: '--keyid-format', description: 'Key ID format', args: { name: 'format', suggestions: [{ name: 'none' }, { name: 'short' }, { name: '0xshort' }, { name: 'long' }, { name: '0xlong' }] } },
    { name: '--keyserver', description: 'Keyserver', args: { name: 'server', suggestions: [{ name: 'hkps://keys.openpgp.org' }, { name: 'hkps://keyserver.ubuntu.com' }, { name: 'hkps://pgp.mit.edu' }] } },
    { name: '--keyserver-options', description: 'Keyserver options', args: { name: 'options' } },
    { name: '--homedir', description: 'Home directory', args: { name: 'dir', template: 'folders' } },
    { name: '--options', description: 'Options file', args: { name: 'file', template: 'filepaths' } },
    { name: '--no-options', description: 'Don\'t read options file' },
    { name: '--status-fd', description: 'Status file descriptor', args: { name: 'fd' } },
    { name: '--status-file', description: 'Status file', args: { name: 'file', template: 'filepaths' } },
    { name: '--logger-fd', description: 'Logger file descriptor', args: { name: 'fd' } },
    { name: '--logger-file', description: 'Logger file', args: { name: 'file', template: 'filepaths' } },
    { name: '--attribute-fd', description: 'Attribute file descriptor', args: { name: 'fd' } },
    { name: '--attribute-file', description: 'Attribute file', args: { name: 'file', template: 'filepaths' } },
    { name: '--comment', description: 'Comment string', args: { name: 'string' } },
    { name: '--no-comments', description: 'Don\'t include comments' },
    { name: '--emit-version', description: 'Emit version' },
    { name: '--no-emit-version', description: 'Don\'t emit version' },
    { name: '--sig-notation', description: 'Signature notation', args: { name: 'name=value' } },
    { name: '--cert-notation', description: 'Certification notation', args: { name: 'name=value' } },
    { name: '--set-notation', description: 'Set notation', args: { name: 'name=value' } },
    { name: '--sig-policy-url', description: 'Signature policy URL', args: { name: 'url' } },
    { name: '--cert-policy-url', description: 'Certification policy URL', args: { name: 'url' } },
    { name: '--set-policy-url', description: 'Set policy URL', args: { name: 'url' } },
    { name: '--sig-keyserver-url', description: 'Signature keyserver URL', args: { name: 'url' } },
    { name: '--set-filename', description: 'Set filename in literal packet', args: { name: 'name' } },
    { name: '--for-your-eyes-only', description: 'Set for-your-eyes-only flag' },
    { name: '--no-for-your-eyes-only', description: 'Don\'t set for-your-eyes-only flag' },
    { name: '--use-embedded-filename', description: 'Use embedded filename' },
    { name: '--no-use-embedded-filename', description: 'Don\'t use embedded filename' },
    { name: '--completes-needed', description: 'Completely trusted needed', args: { name: 'n' } },
    { name: '--marginals-needed', description: 'Marginally trusted needed', args: { name: 'n' } },
    { name: '--tofu-default-policy', description: 'Default TOFU policy', args: { name: 'policy', suggestions: [{ name: 'auto' }, { name: 'good' }, { name: 'unknown' }, { name: 'bad' }, { name: 'ask' }] } },
    { name: '--max-cert-depth', description: 'Maximum certification depth', args: { name: 'n' } },
    { name: '--no-sig-cache', description: 'Disable signature cache' },
    { name: '--auto-check-trustdb', description: 'Auto check trust database' },
    { name: '--no-auto-check-trustdb', description: 'Disable auto check trust database' },
    { name: '--throw-keyids', description: 'Throw key IDs' },
    { name: '--no-throw-keyids', description: 'Don\'t throw key IDs' },
    { name: '--not-dash-escaped', description: 'Don\'t dash-escape' },
    { name: '--escape-from-lines', description: 'Escape From lines' },
    { name: '--no-escape-from-lines', description: 'Don\'t escape From lines' },
    { name: '--require-secmem', description: 'Require secure memory' },
    { name: '--no-require-secmem', description: 'Don\'t require secure memory' },
    { name: '--no-permission-warning', description: 'Suppress permission warnings' },
    { name: '--require-cross-certification', description: 'Require cross certification' },
    { name: '--no-require-cross-certification', description: 'Don\'t require cross certification' },
    { name: '--expert', description: 'Expert mode' },
    { name: '--no-expert', description: 'Disable expert mode' },
    { name: '--display-charset', description: 'Display character set', args: { name: 'charset', suggestions: [{ name: 'iso-8859-1' }, { name: 'iso-8859-2' }, { name: 'iso-8859-15' }, { name: 'koi8-r' }, { name: 'utf-8' }] } },
    { name: '--utf8-strings', description: 'Assume UTF-8 strings' },
    { name: '--no-utf8-strings', description: 'Don\'t assume UTF-8 strings' },
    { name: '--with-colons', description: 'Machine-parseable output' },
    { name: '--with-key-data', description: 'Include key data' },
    { name: '--with-sig-list', description: 'Include signature list' },
    { name: '--with-sig-check', description: 'Include signature check' },
    { name: '--with-fingerprint', description: 'Include fingerprint' },
    { name: '--with-subkey-fingerprint', description: 'Include subkey fingerprints' },
    { name: '--with-icao-spelling', description: 'Include ICAO spelling' },
    { name: '--with-keygrip', description: 'Include keygrip' },
    { name: '--with-secret', description: 'Include secret key indicator' },
    { name: '--with-wkd-hash', description: 'Include WKD hash' },
    { name: '--with-key-origin', description: 'Include key origin' },
    { name: '--fast-list-mode', description: 'Fast list mode' },
    { name: '--fixed-list-mode', description: 'Fixed list mode' },
    { name: '--legacy-list-mode', description: 'Legacy list mode' },
    { name: '--trust-model', description: 'Trust model', args: { name: 'model', suggestions: [{ name: 'pgp' }, { name: 'classic' }, { name: 'tofu' }, { name: 'tofu+pgp' }, { name: 'direct' }, { name: 'always' }, { name: 'auto' }] } },
    { name: '--always-trust', description: 'Always trust' },
    { name: '--assert-signer', description: 'Assert signer', args: { name: 'key' } },
    { name: '--auto-key-locate', description: 'Auto key locate', args: { name: 'mechanisms', suggestions: [{ name: 'cert' }, { name: 'dane' }, { name: 'wkd' }, { name: 'ldap' }, { name: 'keyserver' }, { name: 'keyserver-url' }, { name: 'local' }, { name: 'nodefault' }, { name: 'clear' }] } },
    { name: '--no-auto-key-locate', description: 'Disable auto key locate' },
    { name: '--auto-key-import', description: 'Auto import keys' },
    { name: '--no-auto-key-import', description: 'Disable auto import keys' },
    { name: '--auto-key-retrieve', description: 'Auto retrieve keys' },
    { name: '--no-auto-key-retrieve', description: 'Disable auto retrieve keys' },
    { name: '--enable-large-rsa', description: 'Enable large RSA keys' },
    { name: '--disable-large-rsa', description: 'Disable large RSA keys' },
    { name: '--enable-dsa2', description: 'Enable DSA2' },
    { name: '--disable-dsa2', description: 'Disable DSA2' },
    { name: '--photo-viewer', description: 'Photo viewer command', args: { name: 'command' } },
    { name: '--exec-path', description: 'Executable path', args: { name: 'path' } },
    { name: '--keyring', description: 'Add keyring', args: { name: 'file', template: 'filepaths' } },
    { name: '--primary-keyring', description: 'Primary keyring', args: { name: 'file', template: 'filepaths' } },
    { name: '--secret-keyring', description: 'Secret keyring', args: { name: 'file', template: 'filepaths' } },
    { name: '--no-default-keyring', description: 'Don\'t add default keyring' },
    { name: '--no-keyring', description: 'Don\'t use any keyring' },
    { name: '--skip-verify', description: 'Skip signature verification' },
    { name: '--skip-hidden-recipients', description: 'Skip hidden recipients' },
    { name: '--no-skip-hidden-recipients', description: 'Don\'t skip hidden recipients' },
    { name: '--allow-non-selfsigned-uid', description: 'Allow non-self-signed UIDs' },
    { name: '--no-allow-non-selfsigned-uid', description: 'Don\'t allow non-self-signed UIDs' },
    { name: '--allow-freeform-uid', description: 'Allow freeform UIDs' },
    { name: '--ignore-time-conflict', description: 'Ignore time conflicts' },
    { name: '--ignore-valid-from', description: 'Ignore valid-from' },
    { name: '--ignore-crc-error', description: 'Ignore CRC errors' },
    { name: '--ignore-mdc-error', description: 'Ignore MDC errors' },
    { name: '--allow-old-cipher-algos', description: 'Allow old cipher algorithms' },
    { name: '--allow-weak-digest-algos', description: 'Allow weak digest algorithms' },
    { name: '--weak-digest', description: 'Mark digest as weak', args: { name: 'algo' } },
    { name: '--allow-weak-key-signatures', description: 'Allow weak key signatures' },
    { name: '--override-session-key', description: 'Override session key', args: { name: 'key' } },
    { name: '--override-session-key-fd', description: 'Override session key FD', args: { name: 'fd' } },
    { name: '--no-random-seed-file', description: 'Don\'t use random seed file' },
    { name: '--no-greeting', description: 'Suppress greeting' },
    { name: '--no-secmem-warning', description: 'Suppress secure memory warning' },
    { name: '--no-armor', description: 'Don\'t create ASCII armor' },
    { name: '--no-default-recipient', description: 'No default recipient' },
    { name: '--openpgp', description: 'OpenPGP mode' },
    { name: '--gnupg', description: 'GnuPG mode' },
    { name: ['-h', '--help'], description: 'Show help' },
    { name: '--version', description: 'Show version' },
    { name: '--warranty', description: 'Show warranty' },
    { name: '--dump-options', description: 'Dump options' },
  ],
  args: { name: 'files', description: 'Files', template: 'filepaths', isOptional: true, isVariadic: true },
};

// Alias for gpg2
export const gpg2Spec = { ...gpgSpec, name: 'gpg2' };
