// nmap - Network exploration and security auditing tool
import { CompletionSpec } from '../types.js';

export const nmapSpec: CompletionSpec = {
  name: 'nmap',
  description: 'Network exploration tool and security/port scanner',
  options: [
    // Target specification
    { name: '-iL', description: 'Input from list', args: { name: 'file', template: 'filepaths' } },
    { name: '-iR', description: 'Random hosts', args: { name: 'num' } },
    { name: '--exclude', description: 'Exclude hosts', args: { name: 'hosts' } },
    { name: '--excludefile', description: 'Exclude from file', args: { name: 'file', template: 'filepaths' } },

    // Host discovery
    { name: '-sL', description: 'List scan - list targets' },
    { name: '-sn', description: 'Ping scan - no port scan' },
    { name: '-Pn', description: 'No ping - treat hosts as up' },
    { name: '-PS', description: 'TCP SYN discovery', args: { name: 'ports', isOptional: true } },
    { name: '-PA', description: 'TCP ACK discovery', args: { name: 'ports', isOptional: true } },
    { name: '-PU', description: 'UDP discovery', args: { name: 'ports', isOptional: true } },
    { name: '-PY', description: 'SCTP discovery', args: { name: 'ports', isOptional: true } },
    { name: '-PE', description: 'ICMP echo discovery' },
    { name: '-PP', description: 'ICMP timestamp discovery' },
    { name: '-PM', description: 'ICMP netmask discovery' },
    { name: '-PO', description: 'IP protocol ping', args: { name: 'protocols', isOptional: true } },
    { name: '-n', description: 'Never do DNS resolution' },
    { name: '-R', description: 'Always resolve DNS' },
    { name: '--dns-servers', description: 'Custom DNS servers', args: { name: 'servers' } },
    { name: '--system-dns', description: 'Use system DNS resolver' },
    { name: '--traceroute', description: 'Trace hop path to each host' },

    // Scan techniques
    { name: '-sS', description: 'TCP SYN scan (stealth)' },
    { name: '-sT', description: 'TCP connect scan' },
    { name: '-sA', description: 'TCP ACK scan' },
    { name: '-sW', description: 'TCP Window scan' },
    { name: '-sM', description: 'TCP Maimon scan' },
    { name: '-sU', description: 'UDP scan' },
    { name: '-sN', description: 'TCP Null scan' },
    { name: '-sF', description: 'TCP FIN scan' },
    { name: '-sX', description: 'TCP Xmas scan' },
    { name: '--scanflags', description: 'Custom TCP flags', args: { name: 'flags' } },
    { name: '-sI', description: 'Idle scan', args: { name: 'zombie' } },
    { name: '-sY', description: 'SCTP INIT scan' },
    { name: '-sZ', description: 'SCTP COOKIE-ECHO scan' },
    { name: '-sO', description: 'IP protocol scan' },
    { name: '-b', description: 'FTP bounce scan', args: { name: 'host' } },

    // Port specification
    { name: '-p', description: 'Port ranges', args: { name: 'ports', suggestions: [{ name: '-' }, { name: '1-65535' }, { name: '1-1000' }, { name: '22' }, { name: '22,80,443' }, { name: '80,443,8080,8443' }, { name: 'U:53,T:21-25,80' }] } },
    { name: '--exclude-ports', description: 'Exclude ports', args: { name: 'ports' } },
    { name: '-F', description: 'Fast - scan fewer ports' },
    { name: '-r', description: 'Don\'t randomize ports' },
    { name: '--top-ports', description: 'Scan most common ports', args: { name: 'number' } },
    { name: '--port-ratio', description: 'Scan ports by ratio', args: { name: 'ratio' } },

    // Service/version detection
    { name: '-sV', description: 'Version detection' },
    { name: '--version-intensity', description: 'Version intensity (0-9)', args: { name: 'level', suggestions: [{ name: '0' }, { name: '1' }, { name: '2' }, { name: '3' }, { name: '4' }, { name: '5' }, { name: '6' }, { name: '7' }, { name: '8' }, { name: '9' }] } },
    { name: '--version-light', description: 'Light version scan (2)' },
    { name: '--version-all', description: 'Intensive version scan (9)' },
    { name: '--version-trace', description: 'Trace version scan activity' },

    // Script scan
    { name: '-sC', description: 'Default scripts (same as --script=default)' },
    { name: '--script', description: 'NSE scripts', args: { name: 'scripts', suggestions: [{ name: 'default' }, { name: 'safe' }, { name: 'intrusive' }, { name: 'vuln' }, { name: 'exploit' }, { name: 'auth' }, { name: 'broadcast' }, { name: 'brute' }, { name: 'discovery' }, { name: 'dos' }, { name: 'external' }, { name: 'fuzzer' }, { name: 'malware' }, { name: 'version' }, { name: 'http-*' }, { name: 'ssl-*' }, { name: 'smb-*' }, { name: 'dns-*' }, { name: 'ssh-*' }, { name: 'ftp-*' }] } },
    { name: '--script-args', description: 'Script arguments', args: { name: 'args' } },
    { name: '--script-args-file', description: 'Script args from file', args: { name: 'file', template: 'filepaths' } },
    { name: '--script-trace', description: 'Trace script execution' },
    { name: '--script-updatedb', description: 'Update script database' },
    { name: '--script-help', description: 'Script help', args: { name: 'scripts' } },

    // OS detection
    { name: '-O', description: 'Enable OS detection' },
    { name: '--osscan-limit', description: 'Limit OS detection to promising targets' },
    { name: '--osscan-guess', description: 'Guess OS more aggressively' },

    // Timing and performance
    { name: '-T', description: 'Timing template', args: { name: 'timing', suggestions: [{ name: '0', description: 'Paranoid - slowest' }, { name: '1', description: 'Sneaky' }, { name: '2', description: 'Polite' }, { name: '3', description: 'Normal (default)' }, { name: '4', description: 'Aggressive' }, { name: '5', description: 'Insane - fastest' }] } },
    { name: '--min-hostgroup', description: 'Min parallel hosts', args: { name: 'size' } },
    { name: '--max-hostgroup', description: 'Max parallel hosts', args: { name: 'size' } },
    { name: '--min-parallelism', description: 'Min probe parallelism', args: { name: 'probes' } },
    { name: '--max-parallelism', description: 'Max probe parallelism', args: { name: 'probes' } },
    { name: '--min-rtt-timeout', description: 'Min probe round trip', args: { name: 'time' } },
    { name: '--max-rtt-timeout', description: 'Max probe round trip', args: { name: 'time' } },
    { name: '--initial-rtt-timeout', description: 'Initial probe round trip', args: { name: 'time' } },
    { name: '--max-retries', description: 'Max retries', args: { name: 'tries' } },
    { name: '--host-timeout', description: 'Host timeout', args: { name: 'time' } },
    { name: '--scan-delay', description: 'Delay between probes', args: { name: 'time' } },
    { name: '--max-scan-delay', description: 'Max delay between probes', args: { name: 'time' } },
    { name: '--min-rate', description: 'Min packets/second', args: { name: 'number' } },
    { name: '--max-rate', description: 'Max packets/second', args: { name: 'number' } },

    // Firewall/IDS evasion
    { name: '-f', description: 'Fragment packets' },
    { name: '--mtu', description: 'Custom MTU', args: { name: 'size' } },
    { name: '-D', description: 'Decoy scan', args: { name: 'decoys', suggestions: [{ name: 'RND:10' }, { name: 'ME' }] } },
    { name: '-S', description: 'Spoof source address', args: { name: 'ip' } },
    { name: '-e', description: 'Interface to use', args: { name: 'interface' } },
    { name: '-g', description: 'Source port', args: { name: 'port' } },
    { name: '--source-port', description: 'Source port', args: { name: 'port' } },
    { name: '--proxies', description: 'Relay through proxies', args: { name: 'url' } },
    { name: '--data', description: 'Custom payload data', args: { name: 'hex' } },
    { name: '--data-string', description: 'Custom payload string', args: { name: 'string' } },
    { name: '--data-length', description: 'Random payload length', args: { name: 'num' } },
    { name: '--ip-options', description: 'IP options', args: { name: 'options' } },
    { name: '--ttl', description: 'IP time-to-live', args: { name: 'value' } },
    { name: '--spoof-mac', description: 'Spoof MAC address', args: { name: 'mac', suggestions: [{ name: '0' }, { name: 'Apple' }, { name: 'Dell' }, { name: 'Cisco' }] } },
    { name: '--badsum', description: 'Send bad checksum' },

    // Output
    { name: '-oN', description: 'Normal output', args: { name: 'file', template: 'filepaths' } },
    { name: '-oX', description: 'XML output', args: { name: 'file', template: 'filepaths' } },
    { name: '-oS', description: 'Script kiddie output', args: { name: 'file', template: 'filepaths' } },
    { name: '-oG', description: 'Grepable output', args: { name: 'file', template: 'filepaths' } },
    { name: '-oA', description: 'Output all formats', args: { name: 'basename' } },
    { name: '-v', description: 'Increase verbosity', isRepeatable: true },
    { name: '-d', description: 'Increase debugging', isRepeatable: true },
    { name: '--reason', description: 'Show port state reason' },
    { name: '--open', description: 'Show only open ports' },
    { name: '--packet-trace', description: 'Trace packets' },
    { name: '--iflist', description: 'List interfaces' },
    { name: '--append-output', description: 'Append to output files' },
    { name: '--resume', description: 'Resume aborted scan', args: { name: 'file', template: 'filepaths' } },
    { name: '--stylesheet', description: 'XSL stylesheet', args: { name: 'path', template: 'filepaths' } },
    { name: '--webxml', description: 'Reference Nmap.Org stylesheet' },
    { name: '--no-stylesheet', description: 'No stylesheet' },

    // Miscellaneous
    { name: '-6', description: 'Enable IPv6 scanning' },
    { name: '-A', description: 'Aggressive scan (-O -sV -sC --traceroute)' },
    { name: '--datadir', description: 'Custom data directory', args: { name: 'dir', template: 'folders' } },
    { name: '--send-eth', description: 'Send using raw ethernet' },
    { name: '--send-ip', description: 'Send using raw IP' },
    { name: '--privileged', description: 'Assume privileged user' },
    { name: '--unprivileged', description: 'Assume non-privileged user' },
    { name: '-V', description: 'Print version' },
    { name: '--version', description: 'Print version' },
    { name: '-h', description: 'Print help' },
    { name: '--help', description: 'Print help' },
  ],
  args: {
    name: 'target',
    description: 'Target specification (hostname, IP, network)',
    isVariadic: true,
    suggestions: [
      { name: 'localhost', description: 'Local machine' },
      { name: '127.0.0.1', description: 'Loopback address' },
      { name: '192.168.1.0/24', description: 'Local network example' },
      { name: '10.0.0.0/8', description: 'Private network' },
      { name: '172.16.0.0/12', description: 'Private network' },
      { name: 'scanme.nmap.org', description: 'Nmap test target' },
    ],
  },
};
