// Node.js - JavaScript runtime
import { CompletionSpec } from '../types.js';

export const nodeSpec: CompletionSpec = {
  name: 'node',
  description: 'Node.js JavaScript runtime',
  options: [
    { name: ['-v', '--version'], description: 'Print Node.js version' },
    { name: ['-h', '--help'], description: 'Print help' },
    { name: ['-e', '--eval'], description: 'Evaluate script', args: { name: 'script' } },
    { name: ['-p', '--print'], description: 'Evaluate and print result', args: { name: 'script' } },
    { name: ['-c', '--check'], description: 'Check syntax only' },
    { name: ['-i', '--interactive'], description: 'Start REPL' },
    { name: ['-r', '--require'], description: 'Preload module', args: { name: 'module' } },
    { name: '--import', description: 'Preload ES module', args: { name: 'module' } },
    { name: '--inspect', description: 'Enable inspector', args: { name: '[host:]port', isOptional: true } },
    { name: '--inspect-brk', description: 'Enable inspector and break', args: { name: '[host:]port', isOptional: true } },
    { name: '--inspect-port', description: 'Inspector port', args: { name: 'port' } },
    { name: '--no-deprecation', description: 'Silence deprecation warnings' },
    { name: '--throw-deprecation', description: 'Throw on deprecations' },
    { name: '--trace-deprecation', description: 'Show stack traces for deprecations' },
    { name: '--trace-warnings', description: 'Show stack traces for warnings' },
    { name: '--trace-sync-io', description: 'Show sync I/O warning' },
    { name: '--trace-uncaught', description: 'Show stack trace for uncaught exceptions' },
    { name: '--unhandled-rejections', description: 'Handle unhandled rejections', args: { name: 'mode', suggestions: [{ name: 'strict' }, { name: 'warn' }, { name: 'none' }, { name: 'throw' }] } },
    { name: '--abort-on-uncaught-exception', description: 'Abort on uncaught exception' },
    { name: '--max-old-space-size', description: 'Max old space size (MB)', args: { name: 'size' } },
    { name: '--max-semi-space-size', description: 'Max semi-space size (MB)', args: { name: 'size' } },
    { name: '--stack-size', description: 'Stack size (kB)', args: { name: 'size' } },
    { name: '--preserve-symlinks', description: 'Preserve symlinks when resolving' },
    { name: '--preserve-symlinks-main', description: 'Preserve symlinks for main module' },
    { name: '--experimental-modules', description: 'Enable ES modules' },
    { name: '--experimental-json-modules', description: 'Enable JSON modules' },
    { name: '--experimental-wasm-modules', description: 'Enable WASM modules' },
    { name: '--experimental-vm-modules', description: 'Enable ES modules in vm' },
    { name: '--experimental-loader', description: 'Custom ES module loader', args: { name: 'module' } },
    { name: '--experimental-policy', description: 'Security policy', args: { name: 'file', template: 'filepaths' } },
    { name: '--experimental-repl-await', description: 'Enable REPL await' },
    { name: '--input-type', description: 'Input type', args: { name: 'type', suggestions: [{ name: 'commonjs' }, { name: 'module' }] } },
    { name: '--es-module-specifier-resolution', description: 'Resolution algorithm', args: { name: 'mode', suggestions: [{ name: 'explicit' }, { name: 'node' }] } },
    { name: '--conditions', description: 'Package conditions', args: { name: 'conditions' } },
    { name: '--no-warnings', description: 'Silence all warnings' },
    { name: '--no-force-async-hooks-checks', description: 'Disable async hooks checks' },
    { name: '--pending-deprecation', description: 'Emit pending deprecation warnings' },
    { name: '--redirect-warnings', description: 'Write warnings to file', args: { name: 'file', template: 'filepaths' } },
    { name: '--prof', description: 'Generate V8 profiler output' },
    { name: '--prof-process', description: 'Process V8 profiler output' },
    { name: '--cpu-prof', description: 'Start CPU profiler on startup' },
    { name: '--cpu-prof-dir', description: 'CPU profile directory', args: { name: 'dir', template: 'folders' } },
    { name: '--cpu-prof-name', description: 'CPU profile filename', args: { name: 'name' } },
    { name: '--heap-prof', description: 'Start heap profiler on startup' },
    { name: '--heap-prof-dir', description: 'Heap profile directory', args: { name: 'dir', template: 'folders' } },
    { name: '--heap-prof-name', description: 'Heap profile filename', args: { name: 'name' } },
    { name: '--heapsnapshot-signal', description: 'Signal for heap snapshot', args: { name: 'signal' } },
    { name: '--report-on-fatalerror', description: 'Generate report on fatal error' },
    { name: '--report-on-signal', description: 'Generate report on signal' },
    { name: '--report-signal', description: 'Signal for report', args: { name: 'signal' } },
    { name: '--report-uncaught-exception', description: 'Generate report on uncaught exception' },
    { name: '--report-directory', description: 'Report directory', args: { name: 'dir', template: 'folders' } },
    { name: '--report-filename', description: 'Report filename', args: { name: 'name' } },
    { name: '--title', description: 'Process title', args: { name: 'title' } },
    { name: '--tls-cipher-list', description: 'TLS cipher list', args: { name: 'list' } },
    { name: '--tls-min-v1.0', description: 'Set minimum TLS version to 1.0' },
    { name: '--tls-min-v1.1', description: 'Set minimum TLS version to 1.1' },
    { name: '--tls-min-v1.2', description: 'Set minimum TLS version to 1.2' },
    { name: '--tls-min-v1.3', description: 'Set minimum TLS version to 1.3' },
    { name: '--tls-max-v1.2', description: 'Set maximum TLS version to 1.2' },
    { name: '--tls-max-v1.3', description: 'Set maximum TLS version to 1.3' },
    { name: '--use-openssl-ca', description: 'Use OpenSSL CA store' },
    { name: '--use-bundled-ca', description: 'Use bundled CA store' },
    { name: '--openssl-config', description: 'OpenSSL config file', args: { name: 'file', template: 'filepaths' } },
    { name: '--icu-data-dir', description: 'ICU data directory', args: { name: 'dir', template: 'folders' } },
    { name: '--enable-source-maps', description: 'Enable Source Map V3' },
    { name: '--enable-fips', description: 'Enable FIPS mode' },
    { name: '--force-fips', description: 'Force FIPS mode' },
    { name: '--secure-heap', description: 'Secure heap size', args: { name: 'size' } },
    { name: '--secure-heap-min', description: 'Minimum secure heap allocation', args: { name: 'size' } },
    { name: '--zero-fill-buffers', description: 'Zero-fill Buffer allocations' },
    { name: '--v8-options', description: 'Print V8 options' },
    { name: '--v8-pool-size', description: 'V8 thread pool size', args: { name: 'size' } },
    { name: '--watch', description: 'Run in watch mode' },
    { name: '--watch-path', description: 'Watch specific path', args: { name: 'path', template: 'filepaths' } },
    { name: '--watch-preserve-output', description: 'Preserve console output on restart' },
    { name: '--test', description: 'Run test files' },
    { name: '--test-reporter', description: 'Test reporter', args: { name: 'reporter', suggestions: [{ name: 'spec' }, { name: 'tap' }, { name: 'dot' }] } },
    { name: '--test-reporter-destination', description: 'Test reporter output', args: { name: 'file', template: 'filepaths' } },
    { name: '--test-only', description: 'Run only tests with only option' },
    { name: '--test-concurrency', description: 'Test concurrency', args: { name: 'number' } },
    { name: '--env-file', description: 'Load environment from file', args: { name: 'file', template: 'filepaths' } },
    { name: '--no-global-search-paths', description: 'Disable global search paths' },
    { name: '--no-network-family-autoselection', description: 'Disable automatic IPv4/IPv6 selection' },
    { name: '--dns-result-order', description: 'DNS result order', args: { name: 'order', suggestions: [{ name: 'ipv4first' }, { name: 'verbatim' }] } },
    { name: '--disable-proto', description: 'Disable __proto__', args: { name: 'mode', suggestions: [{ name: 'delete' }, { name: 'throw' }] } },
    { name: '--frozen-intrinsics', description: 'Freeze intrinsic objects' },
    { name: '--', description: 'Pass remaining args to script' },
  ],
  args: {
    name: 'script',
    description: 'Script file to run',
    template: 'filepaths',
    isOptional: true,
  },
};
