// npx - Execute npm package binaries
import { CompletionSpec } from '../types.js';

export const npxSpec: CompletionSpec = {
  name: 'npx',
  description: 'Execute npm package binaries',
  options: [
    { name: ['-p', '--package'], description: 'Package to install', args: { name: 'package' } },
    { name: ['-c', '--call'], description: 'Execute string as if in npm run-script', args: { name: 'script' } },
    { name: ['-y', '--yes'], description: 'Skip prompts to install' },
    { name: ['-n', '--no'], description: 'Answer no to prompts' },
    { name: '--no-install', description: 'Skip installation if not found' },
    { name: '--ignore-existing', description: 'Ignore existing in PATH' },
    { name: ['-q', '--quiet'], description: 'Suppress npm output' },
    { name: '--prefer-online', description: 'Prefer online packages' },
    { name: '--prefer-offline', description: 'Prefer cached packages' },
    { name: '--registry', description: 'Registry URL', args: { name: 'url' } },
    { name: '--cache', description: 'Cache location', args: { name: 'path', template: 'folders' } },
    { name: '--userconfig', description: 'User config file', args: { name: 'file', template: 'filepaths' } },
    { name: '--shell', description: 'Shell to run in', args: { name: 'shell', suggestions: [{ name: 'bash' }, { name: 'sh' }, { name: 'zsh' }, { name: 'fish' }] } },
    { name: '--shell-auto-fallback', description: 'Fallback shell behavior' },
    { name: ['-h', '--help'], description: 'Show help' },
    { name: ['-v', '--version'], description: 'Show version' },
  ],
  args: {
    name: 'command',
    description: 'Package binary or command',
    isVariadic: true,
    suggestions: [
      { name: 'create-react-app', description: 'Create React App' },
      { name: 'create-next-app', description: 'Create Next.js App' },
      { name: 'create-vite', description: 'Create Vite project' },
      { name: 'create-svelte', description: 'Create SvelteKit project' },
      { name: 'create-vue', description: 'Create Vue project' },
      { name: 'create-nuxt-app', description: 'Create Nuxt.js app' },
      { name: 'create-astro', description: 'Create Astro project' },
      { name: 'create-remix', description: 'Create Remix app' },
      { name: 'create-turbo', description: 'Create Turborepo' },
      { name: 'create-expo-app', description: 'Create Expo app' },
      { name: 'degit', description: 'Scaffold from git repo' },
      { name: 'prettier', description: 'Code formatter' },
      { name: 'eslint', description: 'JavaScript linter' },
      { name: 'tsc', description: 'TypeScript compiler' },
      { name: 'tsx', description: 'TypeScript execute' },
      { name: 'ts-node', description: 'TypeScript execution' },
      { name: 'jest', description: 'Testing framework' },
      { name: 'vitest', description: 'Vite test runner' },
      { name: 'playwright', description: 'Browser testing' },
      { name: 'cypress', description: 'E2E testing' },
      { name: 'serve', description: 'Static file server' },
      { name: 'http-server', description: 'HTTP server' },
      { name: 'json-server', description: 'Mock REST API' },
      { name: 'concurrently', description: 'Run commands concurrently' },
      { name: 'nodemon', description: 'Auto-restart Node.js' },
      { name: 'pm2', description: 'Process manager' },
      { name: 'prisma', description: 'Database toolkit' },
      { name: 'drizzle-kit', description: 'Drizzle ORM CLI' },
      { name: 'typeorm', description: 'TypeORM CLI' },
      { name: 'sequelize-cli', description: 'Sequelize CLI' },
      { name: 'tailwindcss', description: 'Tailwind CSS CLI' },
      { name: 'postcss', description: 'PostCSS CLI' },
      { name: 'sass', description: 'Sass compiler' },
      { name: 'esbuild', description: 'JavaScript bundler' },
      { name: 'rollup', description: 'Module bundler' },
      { name: 'webpack', description: 'Module bundler' },
      { name: 'parcel', description: 'Build tool' },
      { name: 'husky', description: 'Git hooks' },
      { name: 'lint-staged', description: 'Run linters on staged files' },
      { name: 'commitlint', description: 'Lint commit messages' },
      { name: 'semantic-release', description: 'Automated releases' },
      { name: 'changeset', description: 'Changelog management' },
      { name: 'envinfo', description: 'Environment info' },
      { name: 'npm-check-updates', description: 'Update package.json' },
      { name: 'depcheck', description: 'Find unused dependencies' },
      { name: 'license-checker', description: 'Check licenses' },
      { name: 'madge', description: 'Dependency graph' },
      { name: 'plop', description: 'Code generator' },
      { name: 'hygen', description: 'Code generator' },
      { name: 'yo', description: 'Yeoman generator' },
    ],
  },
};
