// pip3 - Python package installer
import { CompletionSpec } from '../types.js';

export const pip3Spec: CompletionSpec = {
  name: 'pip3',
  description: 'Python package installer (pip for Python 3)',
  options: [
    { name: ['-h', '--help'], description: 'Show help' },
    { name: ['-V', '--version'], description: 'Show version' },
    { name: ['-v', '--verbose'], description: 'Verbose output' },
    { name: ['-q', '--quiet'], description: 'Quiet output' },
    { name: '--log', description: 'Log file', args: { name: 'path', template: 'filepaths' } },
    { name: '--no-input', description: 'Disable prompting' },
    { name: '--proxy', description: 'Proxy', args: { name: 'proxy' } },
    { name: '--retries', description: 'Max retries', args: { name: 'retries' } },
    { name: '--timeout', description: 'Socket timeout', args: { name: 'seconds' } },
    { name: '--exists-action', description: 'Action for existing', args: { name: 'action', suggestions: [{ name: 's', description: 'Switch' }, { name: 'i', description: 'Ignore' }, { name: 'w', description: 'Wipe' }, { name: 'b', description: 'Backup' }, { name: 'a', description: 'Abort' }] } },
    { name: '--trusted-host', description: 'Trusted host', args: { name: 'hostname' } },
    { name: '--cert', description: 'CA bundle', args: { name: 'path', template: 'filepaths' } },
    { name: '--client-cert', description: 'Client cert', args: { name: 'path', template: 'filepaths' } },
    { name: '--cache-dir', description: 'Cache directory', args: { name: 'dir', template: 'folders' } },
    { name: '--no-cache-dir', description: 'Disable cache' },
    { name: '--disable-pip-version-check', description: 'Disable version check' },
    { name: '--no-color', description: 'No colored output' },
    { name: '--no-python-version-warning', description: 'Suppress Python version warning' },
    { name: '--use-feature', description: 'Enable feature', args: { name: 'feature' } },
    { name: '--use-deprecated', description: 'Enable deprecated feature', args: { name: 'feature' } },
  ],
  subcommands: [
    {
      name: 'install',
      description: 'Install packages',
      options: [
        { name: ['-r', '--requirement'], description: 'Requirements file', args: { name: 'file', template: 'filepaths' } },
        { name: ['-c', '--constraint'], description: 'Constraints file', args: { name: 'file', template: 'filepaths' } },
        { name: '--no-deps', description: "Don't install dependencies" },
        { name: '--pre', description: 'Include pre-releases' },
        { name: ['-e', '--editable'], description: 'Install in editable mode', args: { name: 'path', template: 'folders' } },
        { name: ['-t', '--target'], description: 'Install to directory', args: { name: 'dir', template: 'folders' } },
        { name: '--platform', description: 'Platform', args: { name: 'platform' } },
        { name: '--python-version', description: 'Python version', args: { name: 'version' } },
        { name: '--implementation', description: 'Python implementation', args: { name: 'impl', suggestions: [{ name: 'pp' }, { name: 'jy' }, { name: 'cp' }, { name: 'ip' }] } },
        { name: '--abi', description: 'ABI', args: { name: 'abi' } },
        { name: ['-U', '--upgrade'], description: 'Upgrade packages' },
        { name: '--upgrade-strategy', description: 'Upgrade strategy', args: { name: 'strategy', suggestions: [{ name: 'eager' }, { name: 'only-if-needed' }] } },
        { name: '--force-reinstall', description: 'Force reinstall' },
        { name: ['-I', '--ignore-installed'], description: 'Ignore installed packages' },
        { name: '--ignore-requires-python', description: 'Ignore Python version' },
        { name: '--no-build-isolation', description: 'Disable build isolation' },
        { name: '--use-pep517', description: 'Use PEP 517 build' },
        { name: '--no-use-pep517', description: 'Disable PEP 517' },
        { name: '--check-build-dependencies', description: 'Check build deps' },
        { name: '--config-settings', description: 'Build config', args: { name: 'settings' } },
        { name: '--global-option', description: 'Global setup.py option', args: { name: 'option' } },
        { name: '--compile', description: 'Compile Python files' },
        { name: '--no-compile', description: "Don't compile Python files" },
        { name: '--no-warn-script-location', description: "Don't warn about script location" },
        { name: '--no-warn-conflicts', description: "Don't warn about conflicts" },
        { name: '--no-binary', description: 'No binary for package', args: { name: 'format' } },
        { name: '--only-binary', description: 'Only binary for package', args: { name: 'format' } },
        { name: '--prefer-binary', description: 'Prefer binary packages' },
        { name: '--require-hashes', description: 'Require hashes' },
        { name: '--progress-bar', description: 'Progress bar', args: { name: 'type', suggestions: [{ name: 'on' }, { name: 'off' }, { name: 'ascii' }, { name: 'pretty' }, { name: 'emoji' }] } },
        { name: '--root-user-action', description: 'Root user action', args: { name: 'action', suggestions: [{ name: 'warn' }, { name: 'ignore' }] } },
        { name: '--report', description: 'JSON report file', args: { name: 'file', template: 'filepaths' } },
        { name: '--no-clean', description: "Don't clean build dirs" },
        { name: ['-i', '--index-url'], description: 'Base URL of index', args: { name: 'url' } },
        { name: '--extra-index-url', description: 'Extra index URL', args: { name: 'url' } },
        { name: '--no-index', description: 'Ignore package index' },
        { name: ['-f', '--find-links'], description: 'Find links URL', args: { name: 'url' } },
        { name: '--user', description: 'Install to user site' },
        { name: '--root', description: 'Install root', args: { name: 'dir', template: 'folders' } },
        { name: '--prefix', description: 'Install prefix', args: { name: 'dir', template: 'folders' } },
        { name: '--src', description: 'Source directory', args: { name: 'dir', template: 'folders' } },
        { name: ['-b', '--build'], description: 'Build directory', args: { name: 'dir', template: 'folders' } },
      ],
      args: { name: 'packages', description: 'Package to install', isVariadic: true },
    },
    {
      name: 'uninstall',
      description: 'Uninstall packages',
      options: [
        { name: ['-r', '--requirement'], description: 'Requirements file', args: { name: 'file', template: 'filepaths' } },
        { name: ['-y', '--yes'], description: 'No confirmation' },
        { name: '--root-user-action', description: 'Root user action', args: { name: 'action' } },
        { name: '--break-system-packages', description: 'Allow breaking system packages' },
      ],
      args: { name: 'packages', description: 'Package to uninstall', isVariadic: true },
    },
    {
      name: 'download',
      description: 'Download packages',
      options: [
        { name: ['-d', '--dest'], description: 'Download directory', args: { name: 'dir', template: 'folders' } },
        { name: ['-r', '--requirement'], description: 'Requirements file', args: { name: 'file', template: 'filepaths' } },
        { name: '--no-deps', description: "Don't download dependencies" },
        { name: '--platform', description: 'Platform', args: { name: 'platform' } },
        { name: '--python-version', description: 'Python version', args: { name: 'version' } },
        { name: '--no-binary', description: 'No binary', args: { name: 'format' } },
        { name: '--only-binary', description: 'Only binary', args: { name: 'format' } },
        { name: '--prefer-binary', description: 'Prefer binary' },
        { name: ['-i', '--index-url'], description: 'Index URL', args: { name: 'url' } },
      ],
      args: { name: 'packages', description: 'Package to download', isVariadic: true },
    },
    {
      name: 'list',
      description: 'List installed packages',
      options: [
        { name: ['-o', '--outdated'], description: 'List outdated' },
        { name: ['-u', '--uptodate'], description: 'List up-to-date' },
        { name: ['-e', '--editable'], description: 'List editable' },
        { name: ['-l', '--local'], description: 'List local only' },
        { name: '--user', description: 'List user packages' },
        { name: '--path', description: 'List from path', args: { name: 'path', template: 'folders' } },
        { name: '--pre', description: 'Include pre-releases' },
        { name: '--format', description: 'Output format', args: { name: 'format', suggestions: [{ name: 'columns' }, { name: 'freeze' }, { name: 'json' }] } },
        { name: '--not-required', description: 'List not required' },
        { name: '--exclude-editable', description: 'Exclude editable' },
        { name: '--include-editable', description: 'Include editable' },
        { name: '--exclude', description: 'Exclude package', args: { name: 'package' } },
      ],
    },
    {
      name: 'show',
      description: 'Show package info',
      options: [
        { name: ['-f', '--files'], description: 'Show files' },
      ],
      args: { name: 'packages', description: 'Package name', isVariadic: true },
    },
    { name: 'info', description: 'Alias for show', args: { name: 'packages', isVariadic: true } },
    {
      name: 'freeze',
      description: 'Output installed packages in requirements format',
      options: [
        { name: ['-r', '--requirement'], description: 'Requirements file', args: { name: 'file', template: 'filepaths' } },
        { name: ['-l', '--local'], description: 'Local only' },
        { name: '--user', description: 'User packages only' },
        { name: '--path', description: 'Path', args: { name: 'path', template: 'folders' } },
        { name: '--all', description: 'Include all packages' },
        { name: '--exclude-editable', description: 'Exclude editable' },
        { name: '--exclude', description: 'Exclude package', args: { name: 'package' } },
      ],
    },
    {
      name: 'check',
      description: 'Check installed packages compatibility',
    },
    {
      name: 'search',
      description: 'Search PyPI (deprecated)',
      args: { name: 'query', description: 'Search query' },
    },
    {
      name: 'wheel',
      description: 'Build wheels',
      options: [
        { name: ['-w', '--wheel-dir'], description: 'Wheel directory', args: { name: 'dir', template: 'folders' } },
        { name: '--no-binary', description: 'No binary', args: { name: 'format' } },
        { name: '--only-binary', description: 'Only binary', args: { name: 'format' } },
        { name: '--prefer-binary', description: 'Prefer binary' },
        { name: '--no-build-isolation', description: 'No build isolation' },
        { name: ['-r', '--requirement'], description: 'Requirements', args: { name: 'file', template: 'filepaths' } },
      ],
      args: { name: 'packages', description: 'Package', isVariadic: true },
    },
    {
      name: 'hash',
      description: 'Compute package hashes',
      options: [
        { name: ['-a', '--algorithm'], description: 'Algorithm', args: { name: 'algorithm', suggestions: [{ name: 'sha256' }, { name: 'sha384' }, { name: 'sha512' }] } },
      ],
      args: { name: 'files', description: 'Package files', template: 'filepaths', isVariadic: true },
    },
    {
      name: 'config',
      description: 'Manage configuration',
      subcommands: [
        { name: 'list', description: 'List config' },
        { name: 'edit', description: 'Edit config', options: [{ name: '--editor', args: { name: 'editor' } }] },
        { name: 'get', description: 'Get config value', args: { name: 'name' } },
        { name: 'set', description: 'Set config value', args: [{ name: 'name' }, { name: 'value' }] },
        { name: 'unset', description: 'Unset config value', args: { name: 'name' } },
        { name: 'debug', description: 'Show debug info' },
      ],
      options: [
        { name: '--user', description: 'User config' },
        { name: '--global', description: 'Global config' },
        { name: '--site', description: 'Site config' },
      ],
    },
    {
      name: 'cache',
      description: 'Manage pip cache',
      subcommands: [
        { name: 'dir', description: 'Show cache directory' },
        { name: 'info', description: 'Show cache info' },
        { name: 'list', description: 'List cached packages', args: { name: 'pattern', isOptional: true } },
        { name: 'remove', description: 'Remove cached packages', args: { name: 'pattern' } },
        { name: 'purge', description: 'Remove all cache' },
      ],
    },
    {
      name: 'index',
      description: 'Inspect package index',
      subcommands: [
        { name: 'versions', description: 'List available versions', args: { name: 'package' } },
      ],
    },
    {
      name: 'debug',
      description: 'Show debug information',
    },
    {
      name: 'inspect',
      description: 'Inspect Python environment',
      options: [
        { name: '--local', description: 'Local packages only' },
        { name: '--user', description: 'User packages only' },
        { name: '--path', description: 'Path', args: { name: 'path', template: 'folders' } },
      ],
    },
  ],
};

// Alias for pip
export const pipSpec = { ...pip3Spec, name: 'pip' };
