// pnpm - Fast, disk space efficient package manager
import { CompletionSpec } from '../types.js';

export const pnpmSpec: CompletionSpec = {
  name: 'pnpm',
  description: 'Fast, disk space efficient package manager',
  options: [
    { name: ['-r', '--recursive'], description: 'Run in all packages' },
    { name: '--filter', description: 'Filter packages', args: { name: 'pattern' } },
    { name: '--filter-prod', description: 'Filter production packages', args: { name: 'pattern' } },
    { name: ['-w', '--workspace-root'], description: 'Run at workspace root' },
    { name: '-C', description: 'Change directory', args: { name: 'dir', template: 'folders' } },
    { name: '--dir', description: 'Change directory', args: { name: 'dir', template: 'folders' } },
    { name: ['-h', '--help'], description: 'Show help' },
    { name: ['-v', '--version'], description: 'Show version' },
  ],
  subcommands: [
    {
      name: 'add',
      description: 'Install a package',
      options: [
        { name: ['-D', '--save-dev'], description: 'Save as devDependency' },
        { name: ['-O', '--save-optional'], description: 'Save as optionalDependency' },
        { name: ['-P', '--save-prod'], description: 'Save as dependency' },
        { name: ['-E', '--save-exact'], description: 'Save exact version' },
        { name: ['-g', '--global'], description: 'Install globally' },
        { name: '--save-peer', description: 'Save as peerDependency' },
        { name: ['-w', '--workspace'], description: 'Install in workspace root' },
        { name: '--filter', description: 'Filter packages', args: { name: 'pattern' } },
        { name: '--ignore-workspace-root-check', description: 'Allow in workspace root' },
      ],
      args: { name: 'package', description: 'Package to install', isVariadic: true },
    },
    {
      name: 'install',
      description: 'Install all dependencies',
      options: [
        { name: ['-P', '--prod', '--production'], description: 'Production only' },
        { name: ['-D', '--dev'], description: 'Dev dependencies only' },
        { name: '--no-optional', description: 'Skip optional dependencies' },
        { name: '--frozen-lockfile', description: 'Fail if lockfile needs update' },
        { name: '--lockfile-only', description: 'Update only lockfile' },
        { name: '--prefer-offline', description: 'Prefer cached packages' },
        { name: '--prefer-frozen-lockfile', description: 'Prefer frozen lockfile' },
        { name: '--fix-lockfile', description: 'Fix broken lockfile' },
        { name: '--ignore-scripts', description: 'Skip lifecycle scripts' },
        { name: '--force', description: 'Force reinstall' },
        { name: '--offline', description: 'Offline mode' },
        { name: '--shamefully-hoist', description: 'Hoist dependencies' },
        { name: '--strict-peer-dependencies', description: 'Fail on peer dependency issues' },
        { name: '--no-lockfile', description: 'Skip lockfile' },
        { name: '--reporter', description: 'Reporter', args: { name: 'reporter', suggestions: [{ name: 'default' }, { name: 'ndjson' }, { name: 'silent' }] } },
      ],
    },
    { name: 'i', description: 'Alias for install' },
    {
      name: 'remove',
      description: 'Remove packages',
      options: [
        { name: ['-D', '--save-dev'], description: 'Remove from devDependencies' },
        { name: ['-O', '--save-optional'], description: 'Remove from optionalDependencies' },
        { name: ['-P', '--save-prod'], description: 'Remove from dependencies' },
        { name: ['-g', '--global'], description: 'Remove global package' },
        { name: '--filter', description: 'Filter packages', args: { name: 'pattern' } },
      ],
      args: { name: 'package', description: 'Package to remove', isVariadic: true },
    },
    { name: 'rm', description: 'Alias for remove', args: { name: 'package', isVariadic: true } },
    { name: 'uninstall', description: 'Alias for remove', args: { name: 'package', isVariadic: true } },
    { name: 'un', description: 'Alias for remove', args: { name: 'package', isVariadic: true } },
    {
      name: 'update',
      description: 'Update packages',
      options: [
        { name: ['-g', '--global'], description: 'Update global packages' },
        { name: ['-D', '--dev'], description: 'Update dev dependencies' },
        { name: ['-P', '--prod'], description: 'Update production dependencies' },
        { name: '--no-optional', description: 'Skip optional dependencies' },
        { name: ['-i', '--interactive'], description: 'Interactive mode' },
        { name: ['-L', '--latest'], description: 'Update to latest' },
        { name: '--filter', description: 'Filter packages', args: { name: 'pattern' } },
        { name: ['-r', '--recursive'], description: 'Update recursively' },
      ],
      args: { name: 'package', description: 'Package to update', isOptional: true, isVariadic: true },
    },
    { name: 'up', description: 'Alias for update' },
    { name: 'upgrade', description: 'Alias for update' },
    {
      name: 'link',
      description: 'Link a package',
      options: [
        { name: ['-g', '--global'], description: 'Link globally' },
        { name: ['-C', '--dir'], description: 'Directory', args: { name: 'dir', template: 'folders' } },
      ],
      args: { name: 'package', description: 'Package to link', isOptional: true },
    },
    { name: 'ln', description: 'Alias for link' },
    { name: 'unlink', description: 'Unlink a package', args: { name: 'package', isOptional: true } },
    {
      name: 'run',
      description: 'Run a script',
      options: [
        { name: ['-r', '--recursive'], description: 'Run in all packages' },
        { name: '--parallel', description: 'Run in parallel' },
        { name: '--stream', description: 'Stream output' },
        { name: '--sequential', description: 'Run sequentially' },
        { name: '--filter', description: 'Filter packages', args: { name: 'pattern' } },
        { name: '--if-present', description: "Don't fail if script missing" },
        { name: '-C', description: 'Directory', args: { name: 'dir', template: 'folders' } },
      ],
      args: [
        { name: 'script', description: 'Script name' },
        { name: 'args', description: 'Script arguments', isOptional: true, isVariadic: true },
      ],
    },
    {
      name: 'exec',
      description: 'Execute a shell command',
      options: [
        { name: ['-r', '--recursive'], description: 'Run in all packages' },
        { name: '--parallel', description: 'Run in parallel' },
        { name: '--filter', description: 'Filter packages', args: { name: 'pattern' } },
        { name: '-C', description: 'Directory', args: { name: 'dir', template: 'folders' } },
      ],
      args: { name: 'command', description: 'Command to run', isVariadic: true },
    },
    {
      name: 'dlx',
      description: 'Run package without installing',
      options: [
        { name: ['-p', '--package'], description: 'Package to use', args: { name: 'package' } },
        { name: ['-c', '--shell-mode'], description: 'Run in shell' },
      ],
      args: { name: 'command', description: 'Command to run', isVariadic: true },
    },
    {
      name: 'create',
      description: 'Create a project from create-* starter kit',
      args: [
        { name: 'starter', description: 'Starter kit name' },
        { name: 'name', description: 'Project name', isOptional: true },
      ],
    },
    { name: 'init', description: 'Initialize package.json', options: [{ name: ['-y', '--yes'], description: 'Use defaults' }] },
    { name: 'publish', description: 'Publish a package', options: [{ name: '--tag', args: { name: 'tag' } }, { name: '--access', args: { name: 'access', suggestions: [{ name: 'public' }, { name: 'restricted' }] } }, { name: '--no-git-checks' }, { name: '--dry-run' }] },
    { name: 'pack', description: 'Create a tarball', options: [{ name: '--pack-destination', args: { name: 'dir', template: 'folders' } }] },
    { name: 'test', description: 'Run test script', options: [{ name: ['-r', '--recursive'] }] },
    { name: 't', description: 'Alias for test' },
    { name: 'start', description: 'Run start script' },
    { name: 'build', description: 'Run build script' },
    {
      name: 'list',
      description: 'List installed packages',
      options: [
        { name: '--depth', description: 'Depth', args: { name: 'depth' } },
        { name: ['-g', '--global'], description: 'List global packages' },
        { name: '--json', description: 'Output JSON' },
        { name: '--long', description: 'Show extended info' },
        { name: '--parseable', description: 'Parseable output' },
        { name: ['-D', '--dev'], description: 'Dev dependencies' },
        { name: ['-P', '--prod'], description: 'Production dependencies' },
      ],
      args: { name: 'package', description: 'Package filter', isOptional: true },
    },
    { name: 'ls', description: 'Alias for list' },
    { name: 'why', description: 'Show why package installed', args: { name: 'package' } },
    { name: 'outdated', description: 'List outdated packages', options: [{ name: '--long' }, { name: ['-g', '--global'] }, { name: ['-r', '--recursive'] }, { name: '--format', args: { name: 'format', suggestions: [{ name: 'table' }, { name: 'list' }, { name: 'json' }] } }] },
    { name: 'audit', description: 'Run security audit', options: [{ name: '--fix' }, { name: '--json' }, { name: '--production' }, { name: '--audit-level', args: { name: 'level', suggestions: [{ name: 'low' }, { name: 'moderate' }, { name: 'high' }, { name: 'critical' }] } }] },
    { name: 'licenses', description: 'List licenses', subcommands: [{ name: 'list', description: 'List all licenses' }] },
    { name: 'rebuild', description: 'Rebuild packages', args: { name: 'package', isOptional: true, isVariadic: true } },
    { name: 'prune', description: 'Remove extraneous packages', options: [{ name: '--prod' }, { name: '--no-optional' }] },
    { name: 'store', description: 'Manage pnpm store', subcommands: [
      { name: 'add', description: 'Add packages to store', args: { name: 'package', isVariadic: true } },
      { name: 'prune', description: 'Remove unreferenced packages' },
      { name: 'status', description: 'Show store status' },
      { name: 'path', description: 'Show store path' },
    ]},
    { name: 'root', description: 'Print node_modules path', options: [{ name: ['-g', '--global'] }] },
    { name: 'bin', description: 'Print bin folder path', options: [{ name: ['-g', '--global'] }] },
    { name: 'config', description: 'Manage configuration', subcommands: [
      { name: 'set', description: 'Set config value', args: [{ name: 'key' }, { name: 'value' }] },
      { name: 'get', description: 'Get config value', args: { name: 'key' } },
      { name: 'delete', description: 'Delete config key', args: { name: 'key' } },
      { name: 'list', description: 'List all config' },
    ]},
    { name: 'setup', description: 'Setup pnpm' },
    { name: 'env', description: 'Manage Node.js versions', subcommands: [
      { name: 'use', description: 'Use Node.js version', options: [{ name: ['-g', '--global'] }], args: { name: 'version' } },
      { name: 'remove', description: 'Remove Node.js version', options: [{ name: ['-g', '--global'] }], args: { name: 'version' } },
      { name: 'list', description: 'List installed versions', options: [{ name: '--remote' }] },
    ]},
    { name: 'server', description: 'Manage store server', subcommands: [
      { name: 'start', description: 'Start store server' },
      { name: 'stop', description: 'Stop store server' },
      { name: 'status', description: 'Show server status' },
    ]},
    { name: 'import', description: 'Import from package-lock.json' },
    { name: 'dedupe', description: 'Deduplicate dependencies', options: [{ name: '--check' }] },
    { name: 'fetch', description: 'Fetch packages to store' },
    { name: 'patch', description: 'Prepare package for patching', args: { name: 'package' } },
    { name: 'patch-commit', description: 'Commit package patch', args: { name: 'dir', template: 'folders' } },
  ],
};
