// Podman - Container management tool
import { CompletionSpec, Suggestion } from '../types.js';

export const podmanSpec: CompletionSpec = {
  name: 'podman',
  description: 'Manage pods, containers and images',
  options: [
    { name: '--cgroup-manager', description: 'Cgroup manager', args: { name: 'manager', suggestions: [{ name: 'cgroupfs' }, { name: 'systemd' }] } },
    { name: '--connection', description: 'Connection name', args: { name: 'name' } },
    { name: '-c', description: 'Connection name', args: { name: 'name' } },
    { name: '--conmon', description: 'Path to conmon', args: { name: 'path', template: 'filepaths' } },
    { name: '--events-backend', description: 'Events backend', args: { name: 'backend', suggestions: [{ name: 'file' }, { name: 'journald' }, { name: 'none' }] } },
    { name: '--help', description: 'Help' },
    { name: '-h', description: 'Help' },
    { name: '--hooks-dir', description: 'Hooks directory', args: { name: 'dir', template: 'folders' } },
    { name: '--identity', description: 'SSH identity file', args: { name: 'file', template: 'filepaths' } },
    { name: '--log-level', description: 'Log level', args: { name: 'level', suggestions: [{ name: 'trace' }, { name: 'debug' }, { name: 'info' }, { name: 'warn' }, { name: 'error' }, { name: 'fatal' }, { name: 'panic' }] } },
    { name: '--network-cmd-path', description: 'Network command path', args: { name: 'path', template: 'filepaths' } },
    { name: '--remote', description: 'Use remote connection' },
    { name: '-r', description: 'Use remote connection' },
    { name: '--root', description: 'Storage root directory', args: { name: 'dir', template: 'folders' } },
    { name: '--runroot', description: 'Storage run directory', args: { name: 'dir', template: 'folders' } },
    { name: '--runtime', description: 'OCI runtime', args: { name: 'runtime', suggestions: [{ name: 'crun' }, { name: 'runc' }] } },
    { name: '--storage-driver', description: 'Storage driver', args: { name: 'driver', suggestions: [{ name: 'overlay' }, { name: 'vfs' }] } },
    { name: '--storage-opt', description: 'Storage option', args: { name: 'opt' } },
    { name: '--syslog', description: 'Output to syslog' },
    { name: '--tmpdir', description: 'Temp directory', args: { name: 'dir', template: 'folders' } },
    { name: '--url', description: 'Remote URL', args: { name: 'url' } },
    { name: '--version', description: 'Version' },
    { name: '-v', description: 'Version' },
  ],
  subcommands: [
    // Container commands
    {
      name: 'run',
      description: 'Run a command in a new container',
      options: [
        { name: ['-d', '--detach'], description: 'Detached mode' },
        { name: ['-i', '--interactive'], description: 'Keep STDIN open' },
        { name: ['-t', '--tty'], description: 'Allocate TTY' },
        { name: '--rm', description: 'Remove after exit' },
        { name: '--name', description: 'Container name', args: { name: 'name' } },
        { name: ['-p', '--publish'], description: 'Publish ports', args: { name: 'port' } },
        { name: ['-P', '--publish-all'], description: 'Publish all ports' },
        { name: ['-v', '--volume'], description: 'Bind mount', args: { name: 'volume' } },
        { name: '--mount', description: 'Attach mount', args: { name: 'mount' } },
        { name: ['-e', '--env'], description: 'Set environment', args: { name: 'key=val' } },
        { name: '--env-file', description: 'Env file', args: { name: 'file', template: 'filepaths' } },
        { name: ['-w', '--workdir'], description: 'Working directory', args: { name: 'dir' } },
        { name: ['-u', '--user'], description: 'Username or UID', args: { name: 'user' } },
        { name: '--entrypoint', description: 'Override entrypoint', args: { name: 'cmd' } },
        { name: '--network', description: 'Network mode', args: { name: 'network', suggestions: [{ name: 'bridge' }, { name: 'host' }, { name: 'none' }, { name: 'slirp4netns' }] } },
        { name: '--hostname', description: 'Container hostname', args: { name: 'name' } },
        { name: '--cpus', description: 'Number of CPUs', args: { name: 'cpus' } },
        { name: ['-m', '--memory'], description: 'Memory limit', args: { name: 'bytes' } },
        { name: '--privileged', description: 'Privileged mode' },
        { name: '--cap-add', description: 'Add capability', args: { name: 'cap' } },
        { name: '--cap-drop', description: 'Drop capability', args: { name: 'cap' } },
        { name: '--security-opt', description: 'Security option', args: { name: 'opt' } },
        { name: ['-l', '--label'], description: 'Set label', args: { name: 'key=val' } },
        { name: '--restart', description: 'Restart policy', args: { name: 'policy', suggestions: [{ name: 'no' }, { name: 'always' }, { name: 'on-failure' }, { name: 'unless-stopped' }] } },
        { name: '--pod', description: 'Run in pod', args: { name: 'pod' } },
        { name: '--replace', description: 'Replace existing' },
        { name: '--pull', description: 'Pull policy', args: { name: 'policy', suggestions: [{ name: 'always' }, { name: 'missing' }, { name: 'never' }] } },
      ],
      args: [
        { name: 'image', description: 'Image name' },
        { name: 'command', description: 'Command', isOptional: true, isVariadic: true },
      ],
    },
    {
      name: 'exec',
      description: 'Execute command in container',
      options: [
        { name: ['-d', '--detach'], description: 'Detached' },
        { name: ['-i', '--interactive'], description: 'Keep STDIN open' },
        { name: ['-t', '--tty'], description: 'Allocate TTY' },
        { name: ['-u', '--user'], description: 'Username', args: { name: 'user' } },
        { name: ['-w', '--workdir'], description: 'Working dir', args: { name: 'dir' } },
        { name: ['-e', '--env'], description: 'Env var', args: { name: 'key=val' } },
        { name: '--privileged', description: 'Privileged' },
        { name: '-l', description: 'Latest container' },
        { name: '--latest', description: 'Latest container' },
      ],
      args: [
        { name: 'container', description: 'Container' },
        { name: 'command', description: 'Command', isVariadic: true },
      ],
    },
    {
      name: 'ps',
      description: 'List containers',
      options: [
        { name: ['-a', '--all'], description: 'Show all' },
        { name: ['-f', '--filter'], description: 'Filter', args: { name: 'filter' } },
        { name: '--format', description: 'Format', args: { name: 'format' } },
        { name: '-l', description: 'Latest' },
        { name: '--latest', description: 'Latest' },
        { name: '-n', description: 'Last n', args: { name: 'n' } },
        { name: '--last', description: 'Last n', args: { name: 'n' } },
        { name: '--no-trunc', description: 'No truncate' },
        { name: ['-q', '--quiet'], description: 'IDs only' },
        { name: ['-s', '--size'], description: 'Show sizes' },
        { name: '--sort', description: 'Sort by', args: { name: 'column' } },
        { name: '-p', description: 'Show pod name' },
        { name: '--pod', description: 'Show pod name' },
      ],
    },
    {
      name: 'logs',
      description: 'Fetch container logs',
      options: [
        { name: ['-f', '--follow'], description: 'Follow' },
        { name: '--since', description: 'Since', args: { name: 'time' } },
        { name: '--until', description: 'Until', args: { name: 'time' } },
        { name: ['-t', '--timestamps'], description: 'Timestamps' },
        { name: '--tail', description: 'Lines', args: { name: 'lines' } },
        { name: ['-n', '--names'], description: 'Print names' },
        { name: '-l', description: 'Latest' },
        { name: '--latest', description: 'Latest' },
      ],
      args: { name: 'container', isVariadic: true },
    },
    { name: 'start', description: 'Start containers', options: [{ name: ['-a', '--attach'] }, { name: ['-i', '--interactive'] }, { name: '-l' }, { name: '--latest' }], args: { name: 'container', isVariadic: true } },
    { name: 'stop', description: 'Stop containers', options: [{ name: ['-t', '--time'], args: { name: 'seconds' } }, { name: ['-a', '--all'] }, { name: '-l' }, { name: '--latest' }], args: { name: 'container', isOptional: true, isVariadic: true } },
    { name: 'restart', description: 'Restart containers', options: [{ name: ['-t', '--time'], args: { name: 'seconds' } }, { name: ['-a', '--all'] }, { name: '-l' }, { name: '--latest' }], args: { name: 'container', isOptional: true, isVariadic: true } },
    { name: 'rm', description: 'Remove containers', options: [{ name: ['-f', '--force'] }, { name: ['-v', '--volumes'] }, { name: ['-a', '--all'] }, { name: '-l' }, { name: '--latest' }], args: { name: 'container', isOptional: true, isVariadic: true } },
    { name: 'kill', description: 'Kill containers', options: [{ name: ['-s', '--signal'], args: { name: 'signal' } }, { name: ['-a', '--all'] }, { name: '-l' }], args: { name: 'container', isOptional: true, isVariadic: true } },
    { name: 'pause', description: 'Pause containers', options: [{ name: ['-a', '--all'] }], args: { name: 'container', isVariadic: true } },
    { name: 'unpause', description: 'Unpause containers', options: [{ name: ['-a', '--all'] }], args: { name: 'container', isVariadic: true } },
    { name: 'inspect', description: 'Inspect container', options: [{ name: ['-f', '--format'], args: { name: 'format' } }, { name: ['-s', '--size'] }, { name: '-l' }], args: { name: 'container', isVariadic: true } },
    { name: 'top', description: 'Display processes', options: [{ name: '-l' }], args: [{ name: 'container' }, { name: 'ps_options', isOptional: true, isVariadic: true }] },
    { name: 'stats', description: 'Display statistics', options: [{ name: ['-a', '--all'] }, { name: '--format', args: { name: 'format' } }, { name: '--no-stream' }], args: { name: 'container', isOptional: true, isVariadic: true } },
    { name: 'attach', description: 'Attach to container', options: [{ name: '--detach-keys', args: { name: 'keys' } }, { name: '--no-stdin' }, { name: '--sig-proxy' }, { name: '-l' }], args: { name: 'container' } },
    { name: 'port', description: 'List port mappings', options: [{ name: ['-a', '--all'] }, { name: '-l' }], args: [{ name: 'container' }, { name: 'port', isOptional: true }] },
    { name: 'rename', description: 'Rename container', args: [{ name: 'container' }, { name: 'new_name' }] },
    { name: 'wait', description: 'Wait for containers', options: [{ name: ['-i', '--interval'], args: { name: 'interval' } }, { name: '-l' }], args: { name: 'container', isVariadic: true } },
    { name: 'diff', description: 'Inspect changes', options: [{ name: '--format', args: { name: 'format' } }, { name: '-l' }], args: { name: 'container' } },
    { name: 'cp', description: 'Copy files', args: [{ name: 'source' }, { name: 'destination' }] },
    { name: 'export', description: 'Export container', options: [{ name: ['-o', '--output'], args: { name: 'file', template: 'filepaths' } }], args: { name: 'container' } },
    { name: 'commit', description: 'Create image from container', options: [{ name: ['-a', '--author'], args: { name: 'author' } }, { name: ['-c', '--change'], args: { name: 'instruction' } }, { name: ['-m', '--message'], args: { name: 'message' } }, { name: ['-p', '--pause'] }, { name: ['-q', '--quiet'] }], args: [{ name: 'container' }, { name: 'image', isOptional: true }] },
    // Image commands
    {
      name: 'images',
      description: 'List images',
      options: [
        { name: ['-a', '--all'], description: 'Show all' },
        { name: ['-f', '--filter'], description: 'Filter', args: { name: 'filter' } },
        { name: '--format', description: 'Format', args: { name: 'format' } },
        { name: '--no-trunc', description: 'No truncate' },
        { name: ['-q', '--quiet'], description: 'IDs only' },
        { name: '--digests', description: 'Show digests' },
      ],
      args: { name: 'repository', isOptional: true },
    },
    {
      name: 'pull',
      description: 'Pull image',
      options: [
        { name: ['-q', '--quiet'], description: 'Quiet' },
        { name: '--all-tags', description: 'All tags' },
        { name: '--arch', description: 'Architecture', args: { name: 'arch' } },
        { name: '--os', description: 'OS', args: { name: 'os' } },
        { name: '--platform', description: 'Platform', args: { name: 'platform' } },
        { name: '--tls-verify', description: 'TLS verify' },
      ],
      args: { name: 'image', description: 'Image name' },
    },
    {
      name: 'push',
      description: 'Push image',
      options: [
        { name: ['-q', '--quiet'], description: 'Quiet' },
        { name: '--all-tags', description: 'All tags' },
        { name: '--compress', description: 'Compress' },
        { name: '--digestfile', description: 'Digest file', args: { name: 'file', template: 'filepaths' } },
        { name: '--tls-verify', description: 'TLS verify' },
      ],
      args: { name: 'image', description: 'Image name' },
    },
    { name: 'rmi', description: 'Remove images', options: [{ name: ['-f', '--force'] }, { name: ['-a', '--all'] }], args: { name: 'image', isVariadic: true } },
    { name: 'tag', description: 'Tag image', args: [{ name: 'source_image' }, { name: 'target_image' }] },
    { name: 'save', description: 'Save image', options: [{ name: ['-o', '--output'], args: { name: 'file', template: 'filepaths' } }, { name: '--format', args: { name: 'format', suggestions: [{ name: 'oci-archive' }, { name: 'oci-dir' }, { name: 'docker-archive' }, { name: 'docker-dir' }] } }], args: { name: 'image', isVariadic: true } },
    { name: 'load', description: 'Load image', options: [{ name: ['-i', '--input'], args: { name: 'file', template: 'filepaths' } }, { name: ['-q', '--quiet'] }] },
    { name: 'history', description: 'Image history', options: [{ name: '--format', args: { name: 'format' } }, { name: ['-H', '--human'] }, { name: '--no-trunc' }, { name: ['-q', '--quiet'] }], args: { name: 'image' } },
    { name: 'search', description: 'Search images', options: [{ name: ['-f', '--filter'], args: { name: 'filter' } }, { name: '--format', args: { name: 'format' } }, { name: '--limit', args: { name: 'limit' } }, { name: '--no-trunc' }], args: { name: 'term' } },
    {
      name: 'build',
      description: 'Build image',
      options: [
        { name: ['-f', '--file'], description: 'Dockerfile', args: { name: 'file', template: 'filepaths' } },
        { name: ['-t', '--tag'], description: 'Tag', args: { name: 'tag' } },
        { name: '--build-arg', description: 'Build arg', args: { name: 'arg=val' } },
        { name: '--no-cache', description: 'No cache' },
        { name: '--pull', description: 'Always pull' },
        { name: ['-q', '--quiet'], description: 'Quiet' },
        { name: '--rm', description: 'Remove intermediate' },
        { name: '--target', description: 'Target stage', args: { name: 'stage' } },
        { name: '--platform', description: 'Platform', args: { name: 'platform' } },
        { name: '--format', description: 'Format', args: { name: 'format', suggestions: [{ name: 'oci' }, { name: 'docker' }] } },
      ],
      args: { name: 'context', template: 'folders', description: 'Build context' },
    },
    // Pod commands
    {
      name: 'pod',
      description: 'Manage pods',
      subcommands: [
        { name: 'create', description: 'Create pod', options: [{ name: '--name', args: { name: 'name' } }, { name: ['-p', '--publish'], args: { name: 'port' } }, { name: '--network', args: { name: 'network' } }, { name: '--infra' }, { name: '--share', args: { name: 'namespaces' } }] },
        { name: 'start', description: 'Start pods', options: [{ name: ['-a', '--all'] }, { name: '-l' }], args: { name: 'pod', isOptional: true, isVariadic: true } },
        { name: 'stop', description: 'Stop pods', options: [{ name: ['-a', '--all'] }, { name: ['-t', '--time'], args: { name: 'seconds' } }, { name: '-l' }], args: { name: 'pod', isOptional: true, isVariadic: true } },
        { name: 'restart', description: 'Restart pods', options: [{ name: ['-a', '--all'] }, { name: '-l' }], args: { name: 'pod', isOptional: true, isVariadic: true } },
        { name: 'rm', description: 'Remove pods', options: [{ name: ['-f', '--force'] }, { name: ['-a', '--all'] }, { name: '-l' }], args: { name: 'pod', isOptional: true, isVariadic: true } },
        { name: 'ps', description: 'List pods', options: [{ name: ['-f', '--filter'], args: { name: 'filter' } }, { name: '--format', args: { name: 'format' } }, { name: '--no-trunc' }, { name: ['-q', '--quiet'] }] },
        { name: 'inspect', description: 'Inspect pod', options: [{ name: ['-f', '--format'], args: { name: 'format' } }, { name: '-l' }], args: { name: 'pod', isVariadic: true } },
        { name: 'top', description: 'Display processes', options: [{ name: '-l' }], args: [{ name: 'pod' }, { name: 'ps_options', isOptional: true, isVariadic: true }] },
        { name: 'stats', description: 'Display statistics', options: [{ name: ['-a', '--all'] }, { name: '--format', args: { name: 'format' } }, { name: '--no-stream' }], args: { name: 'pod', isOptional: true, isVariadic: true } },
        { name: 'pause', description: 'Pause pods', options: [{ name: ['-a', '--all'] }, { name: '-l' }], args: { name: 'pod', isOptional: true, isVariadic: true } },
        { name: 'unpause', description: 'Unpause pods', options: [{ name: ['-a', '--all'] }, { name: '-l' }], args: { name: 'pod', isOptional: true, isVariadic: true } },
        { name: 'kill', description: 'Kill pods', options: [{ name: ['-s', '--signal'], args: { name: 'signal' } }, { name: ['-a', '--all'] }, { name: '-l' }], args: { name: 'pod', isOptional: true, isVariadic: true } },
        { name: 'logs', description: 'Pod logs', options: [{ name: ['-c', '--container'], args: { name: 'container' } }, { name: ['-f', '--follow'] }, { name: '--since', args: { name: 'time' } }, { name: '--tail', args: { name: 'lines' } }, { name: '-l' }], args: { name: 'pod' } },
        { name: 'prune', description: 'Remove stopped pods', options: [{ name: ['-f', '--force'] }] },
        { name: 'exists', description: 'Check if pod exists', args: { name: 'pod' } },
      ],
    },
    // Volume commands
    {
      name: 'volume',
      description: 'Manage volumes',
      subcommands: [
        { name: 'create', description: 'Create volume', options: [{ name: ['-d', '--driver'], args: { name: 'driver' } }, { name: ['-o', '--opt'], args: { name: 'opt' } }, { name: ['-l', '--label'], args: { name: 'label' } }], args: { name: 'name', isOptional: true } },
        { name: 'ls', description: 'List volumes', options: [{ name: ['-f', '--filter'], args: { name: 'filter' } }, { name: '--format', args: { name: 'format' } }, { name: ['-q', '--quiet'] }] },
        { name: 'rm', description: 'Remove volumes', options: [{ name: ['-f', '--force'] }, { name: ['-a', '--all'] }], args: { name: 'volume', isVariadic: true } },
        { name: 'inspect', description: 'Inspect volume', options: [{ name: ['-f', '--format'], args: { name: 'format' } }], args: { name: 'volume', isVariadic: true } },
        { name: 'prune', description: 'Remove unused volumes', options: [{ name: ['-f', '--force'] }] },
        { name: 'exists', description: 'Check if volume exists', args: { name: 'volume' } },
      ],
    },
    // Network commands
    {
      name: 'network',
      description: 'Manage networks',
      subcommands: [
        { name: 'create', description: 'Create network', options: [{ name: ['-d', '--driver'], args: { name: 'driver', suggestions: [{ name: 'bridge' }, { name: 'macvlan' }, { name: 'ipvlan' }] } }, { name: '--subnet', args: { name: 'subnet' } }, { name: '--gateway', args: { name: 'gateway' } }, { name: '--internal' }, { name: ['-l', '--label'], args: { name: 'label' } }], args: { name: 'name' } },
        { name: 'ls', description: 'List networks', options: [{ name: ['-f', '--filter'], args: { name: 'filter' } }, { name: '--format', args: { name: 'format' } }, { name: ['-q', '--quiet'] }] },
        { name: 'rm', description: 'Remove networks', options: [{ name: ['-f', '--force'] }], args: { name: 'network', isVariadic: true } },
        { name: 'inspect', description: 'Inspect network', options: [{ name: ['-f', '--format'], args: { name: 'format' } }], args: { name: 'network', isVariadic: true } },
        { name: 'connect', description: 'Connect container', options: [{ name: '--alias', args: { name: 'alias' } }, { name: '--ip', args: { name: 'ip' } }], args: [{ name: 'network' }, { name: 'container' }] },
        { name: 'disconnect', description: 'Disconnect container', options: [{ name: ['-f', '--force'] }], args: [{ name: 'network' }, { name: 'container' }] },
        { name: 'prune', description: 'Remove unused networks', options: [{ name: ['-f', '--force'] }] },
        { name: 'exists', description: 'Check if network exists', args: { name: 'network' } },
      ],
    },
    // System commands
    {
      name: 'system',
      description: 'Manage podman',
      subcommands: [
        { name: 'df', description: 'Disk usage', options: [{ name: '--format', args: { name: 'format' } }, { name: ['-v', '--verbose'] }] },
        { name: 'info', description: 'System info', options: [{ name: ['-f', '--format'], args: { name: 'format' } }] },
        { name: 'prune', description: 'Remove unused data', options: [{ name: ['-f', '--force'] }, { name: ['-a', '--all'] }, { name: '--volumes' }] },
        { name: 'reset', description: 'Reset storage', options: [{ name: ['-f', '--force'] }] },
        { name: 'connection', description: 'Manage connections', subcommands: [
          { name: 'add', description: 'Add connection', args: [{ name: 'name' }, { name: 'uri' }] },
          { name: 'default', description: 'Set default', args: { name: 'name' } },
          { name: 'list', description: 'List connections' },
          { name: 'remove', description: 'Remove connection', args: { name: 'name' } },
          { name: 'rename', description: 'Rename connection', args: [{ name: 'old' }, { name: 'new' }] },
        ]},
        { name: 'migrate', description: 'Migrate containers', options: [{ name: '--new-runtime', args: { name: 'runtime' } }] },
        { name: 'renumber', description: 'Renumber container locks' },
        { name: 'service', description: 'Run API service', options: [{ name: ['-t', '--time'], args: { name: 'seconds' } }], args: { name: 'uri', isOptional: true } },
      ],
    },
    // Other commands
    { name: 'login', description: 'Log in to registry', options: [{ name: ['-u', '--username'], args: { name: 'user' } }, { name: ['-p', '--password'], args: { name: 'password' } }, { name: '--password-stdin' }, { name: '--authfile', args: { name: 'file', template: 'filepaths' } }], args: { name: 'registry', isOptional: true } },
    { name: 'logout', description: 'Log out of registry', options: [{ name: ['-a', '--all'] }, { name: '--authfile', args: { name: 'file', template: 'filepaths' } }], args: { name: 'registry', isOptional: true } },
    { name: 'info', description: 'Display system info', options: [{ name: ['-f', '--format'], args: { name: 'format' } }] },
    { name: 'version', description: 'Display version', options: [{ name: ['-f', '--format'], args: { name: 'format' } }] },
    { name: 'events', description: 'Show events', options: [{ name: '--filter', args: { name: 'filter' } }, { name: '--format', args: { name: 'format' } }, { name: '--since', args: { name: 'time' } }, { name: '--until', args: { name: 'time' } }] },
    { name: 'generate', description: 'Generate files', subcommands: [
      { name: 'kube', description: 'Generate Kubernetes YAML', options: [{ name: ['-f', '--filename'], args: { name: 'file', template: 'filepaths' } }, { name: ['-s', '--service'] }], args: { name: 'container/pod', isVariadic: true } },
      { name: 'systemd', description: 'Generate systemd units', options: [{ name: ['-f', '--files'] }, { name: '--name', args: { name: 'name' } }, { name: '--new' }, { name: '--no-header' }, { name: '--restart-policy', args: { name: 'policy' } }, { name: ['-t', '--time'], args: { name: 'seconds' } }], args: { name: 'container/pod' } },
    ]},
    { name: 'play', description: 'Play pods', subcommands: [
      { name: 'kube', description: 'Play Kubernetes YAML', options: [{ name: '--authfile', args: { name: 'file', template: 'filepaths' } }, { name: '--cert-dir', args: { name: 'dir', template: 'folders' } }, { name: '--configmap', args: { name: 'file', template: 'filepaths' } }, { name: '--network', args: { name: 'network' } }, { name: ['-q', '--quiet'] }], args: { name: 'yaml', template: 'filepaths' } },
    ]},
    { name: 'compose', description: 'Run compose', subcommands: [
      { name: 'up', description: 'Create and start', options: [{ name: ['-d', '--detach'] }, { name: '--build' }] },
      { name: 'down', description: 'Stop and remove' },
      { name: 'ps', description: 'List containers' },
      { name: 'logs', description: 'View logs', options: [{ name: ['-f', '--follow'] }] },
    ]},
    { name: 'machine', description: 'Manage machines', subcommands: [
      { name: 'init', description: 'Initialize machine', options: [{ name: '--cpus', args: { name: 'cpus' } }, { name: '--disk-size', args: { name: 'gb' } }, { name: ['-m', '--memory'], args: { name: 'mb' } }, { name: '--now' }], args: { name: 'name', isOptional: true } },
      { name: 'start', description: 'Start machine', args: { name: 'name', isOptional: true } },
      { name: 'stop', description: 'Stop machine', args: { name: 'name', isOptional: true } },
      { name: 'rm', description: 'Remove machine', options: [{ name: ['-f', '--force'] }], args: { name: 'name', isOptional: true } },
      { name: 'ssh', description: 'SSH into machine', args: [{ name: 'name', isOptional: true }, { name: 'command', isOptional: true, isVariadic: true }] },
      { name: 'list', description: 'List machines', options: [{ name: '--format', args: { name: 'format' } }, { name: ['-q', '--quiet'] }] },
      { name: 'inspect', description: 'Inspect machine', options: [{ name: '--format', args: { name: 'format' } }], args: { name: 'name', isOptional: true, isVariadic: true } },
      { name: 'set', description: 'Set machine options', options: [{ name: '--cpus', args: { name: 'cpus' } }, { name: '--disk-size', args: { name: 'gb' } }, { name: ['-m', '--memory'], args: { name: 'mb' } }, { name: '--rootful' }], args: { name: 'name', isOptional: true } },
    ]},
    { name: 'manifest', description: 'Manage manifests', subcommands: [
      { name: 'create', description: 'Create manifest', args: [{ name: 'name' }, { name: 'image', isOptional: true, isVariadic: true }] },
      { name: 'add', description: 'Add to manifest', args: [{ name: 'manifest' }, { name: 'image' }] },
      { name: 'push', description: 'Push manifest', options: [{ name: '--all' }, { name: ['-q', '--quiet'] }], args: [{ name: 'manifest' }, { name: 'destination' }] },
      { name: 'inspect', description: 'Inspect manifest', args: { name: 'manifest' } },
      { name: 'rm', description: 'Remove manifest', args: { name: 'manifest', isVariadic: true } },
    ]},
    { name: 'secret', description: 'Manage secrets', subcommands: [
      { name: 'create', description: 'Create secret', options: [{ name: '--driver', args: { name: 'driver' } }], args: [{ name: 'name' }, { name: 'file', template: 'filepaths', isOptional: true }] },
      { name: 'ls', description: 'List secrets', options: [{ name: '--format', args: { name: 'format' } }, { name: ['-q', '--quiet'] }] },
      { name: 'rm', description: 'Remove secrets', options: [{ name: ['-a', '--all'] }], args: { name: 'secret', isVariadic: true } },
      { name: 'inspect', description: 'Inspect secret', options: [{ name: '--format', args: { name: 'format' } }], args: { name: 'secret', isVariadic: true } },
    ]},
    { name: 'healthcheck', description: 'Manage healthchecks', subcommands: [
      { name: 'run', description: 'Run healthcheck', args: { name: 'container' } },
    ]},
    { name: 'unshare', description: 'Run in user namespace', args: { name: 'command', isVariadic: true } },
    { name: 'container', description: 'Manage containers', subcommands: [
      { name: 'cleanup', description: 'Cleanup container storage', options: [{ name: ['-a', '--all'] }, { name: '--rm' }], args: { name: 'container', isOptional: true, isVariadic: true } },
      { name: 'exists', description: 'Check if container exists', args: { name: 'container' } },
      { name: 'prune', description: 'Remove stopped containers', options: [{ name: ['-f', '--force'] }] },
      { name: 'restore', description: 'Restore container', args: { name: 'container' } },
      { name: 'checkpoint', description: 'Checkpoint container', args: { name: 'container' } },
      { name: 'runlabel', description: 'Run label command', args: [{ name: 'label' }, { name: 'image' }] },
    ]},
    { name: 'image', description: 'Manage images', subcommands: [
      { name: 'build', description: 'Build image' },
      { name: 'diff', description: 'Inspect changes', args: { name: 'image' } },
      { name: 'exists', description: 'Check if image exists', args: { name: 'image' } },
      { name: 'history', description: 'Image history', args: { name: 'image' } },
      { name: 'import', description: 'Import image', args: [{ name: 'path' }, { name: 'reference', isOptional: true }] },
      { name: 'inspect', description: 'Inspect image', args: { name: 'image', isVariadic: true } },
      { name: 'list', description: 'List images' },
      { name: 'load', description: 'Load image' },
      { name: 'mount', description: 'Mount image' },
      { name: 'prune', description: 'Remove unused images', options: [{ name: ['-f', '--force'] }, { name: ['-a', '--all'] }] },
      { name: 'pull', description: 'Pull image', args: { name: 'image' } },
      { name: 'push', description: 'Push image', args: { name: 'image' } },
      { name: 'rm', description: 'Remove images', args: { name: 'image', isVariadic: true } },
      { name: 'save', description: 'Save image', args: { name: 'image', isVariadic: true } },
      { name: 'search', description: 'Search images', args: { name: 'term' } },
      { name: 'sign', description: 'Sign image', args: { name: 'image' } },
      { name: 'tag', description: 'Tag image', args: [{ name: 'source' }, { name: 'target' }] },
      { name: 'tree', description: 'Show image tree', args: { name: 'image' } },
      { name: 'trust', description: 'Manage trust policy' },
      { name: 'unmount', description: 'Unmount image', args: { name: 'image' } },
      { name: 'untag', description: 'Untag image', args: { name: 'image' } },
    ]},
  ],
};
