// Poetry - Python dependency management and packaging
import { CompletionSpec } from '../types.js';

export const poetrySpec: CompletionSpec = {
  name: 'poetry',
  description: 'Python packaging and dependency management made easy',
  options: [
    { name: ['-h', '--help'], description: 'Show help' },
    { name: ['-q', '--quiet'], description: 'Quiet output' },
    { name: ['-v', '--verbose'], description: 'Verbose (-vv more, -vvv debug)' },
    { name: ['-V', '--version'], description: 'Show version' },
    { name: '--ansi', description: 'Force ANSI output' },
    { name: '--no-ansi', description: 'Disable ANSI output' },
    { name: ['-n', '--no-interaction'], description: 'No interaction' },
    { name: '--no-plugins', description: 'Disable plugins' },
    { name: '--no-cache', description: 'Disable cache' },
    { name: ['-C', '--directory'], description: 'Working directory', args: { name: 'dir', template: 'folders' } },
  ],
  subcommands: [
    { name: 'about', description: 'Show information about Poetry' },
    {
      name: 'add',
      description: 'Add a dependency',
      options: [
        { name: ['-D', '--dev'], description: 'Add as development dependency' },
        { name: '--group', description: 'Add to group', args: { name: 'group' } },
        { name: ['-E', '--extras'], description: 'Extras to activate', args: { name: 'extras' } },
        { name: '--optional', description: 'Add as optional' },
        { name: '--python', description: 'Python version constraint', args: { name: 'version' } },
        { name: '--platform', description: 'Platform', args: { name: 'platform' } },
        { name: '--source', description: 'Source name', args: { name: 'source' } },
        { name: '--allow-prereleases', description: 'Allow prereleases' },
        { name: '--dry-run', description: 'Dry run' },
        { name: '--lock', description: 'Only update lock file' },
        { name: ['-e', '--editable'], description: 'Editable' },
      ],
      args: { name: 'packages', description: 'Packages to add', isVariadic: true },
    },
    {
      name: 'build',
      description: 'Build package',
      options: [
        { name: ['-f', '--format'], description: 'Format', args: { name: 'format', suggestions: [{ name: 'wheel' }, { name: 'sdist' }] } },
        { name: ['-o', '--output'], description: 'Output directory', args: { name: 'dir', template: 'folders' } },
      ],
    },
    {
      name: 'check',
      description: 'Check pyproject.toml',
      options: [
        { name: '--lock', description: 'Check lock file' },
      ],
    },
    {
      name: 'config',
      description: 'Manage configuration',
      options: [
        { name: '--list', description: 'List settings' },
        { name: '--unset', description: 'Unset setting' },
        { name: '--local', description: 'Local config only' },
      ],
      args: [
        { name: 'key', description: 'Setting key', isOptional: true },
        { name: 'value', description: 'Setting value', isOptional: true, isVariadic: true },
      ],
    },
    {
      name: 'export',
      description: 'Export lock file to requirements.txt',
      options: [
        { name: ['-f', '--format'], description: 'Format', args: { name: 'format', suggestions: [{ name: 'requirements.txt' }, { name: 'constraints.txt' }] } },
        { name: ['-o', '--output'], description: 'Output file', args: { name: 'file', template: 'filepaths' } },
        { name: '--without-hashes', description: 'Exclude hashes' },
        { name: '--without-urls', description: 'Exclude URLs' },
        { name: '--dev', description: 'Include dev dependencies' },
        { name: '--without', description: 'Exclude groups', args: { name: 'groups' } },
        { name: '--with', description: 'Include groups', args: { name: 'groups' } },
        { name: '--only', description: 'Only groups', args: { name: 'groups' } },
        { name: ['-E', '--extras'], description: 'Extras', args: { name: 'extras' } },
        { name: '--all-extras', description: 'All extras' },
        { name: '--with-credentials', description: 'Include credentials' },
      ],
    },
    {
      name: 'init',
      description: 'Initialize a pyproject.toml',
      options: [
        { name: '--name', description: 'Package name', args: { name: 'name' } },
        { name: '--description', description: 'Description', args: { name: 'description' } },
        { name: '--author', description: 'Author', args: { name: 'author' } },
        { name: '--python', description: 'Python version', args: { name: 'version' } },
        { name: '--dependency', description: 'Dependency', args: { name: 'dependency' } },
        { name: '--dev-dependency', description: 'Dev dependency', args: { name: 'dependency' } },
        { name: ['-l', '--license'], description: 'License', args: { name: 'license' } },
      ],
    },
    {
      name: 'install',
      description: 'Install dependencies',
      options: [
        { name: '--without', description: 'Exclude groups', args: { name: 'groups' } },
        { name: '--with', description: 'Include optional groups', args: { name: 'groups' } },
        { name: '--only', description: 'Only groups', args: { name: 'groups' } },
        { name: '--no-dev', description: 'Skip dev dependencies (deprecated)' },
        { name: '--no-root', description: 'Skip root package' },
        { name: '--no-directory', description: 'Skip directory dependencies' },
        { name: '--dry-run', description: 'Dry run' },
        { name: '--remove-untracked', description: 'Remove untracked packages' },
        { name: ['-E', '--extras'], description: 'Extras', args: { name: 'extras' } },
        { name: '--all-extras', description: 'All extras' },
        { name: '--only-root', description: 'Only root package' },
        { name: '--sync', description: 'Synchronize environment' },
        { name: '--compile', description: 'Compile Python files' },
      ],
    },
    {
      name: 'lock',
      description: 'Lock dependencies',
      options: [
        { name: '--no-update', description: "Don't update dependencies" },
        { name: '--check', description: 'Check if lock is fresh' },
      ],
    },
    {
      name: 'new',
      description: 'Create a new project',
      options: [
        { name: '--name', description: 'Package name', args: { name: 'name' } },
        { name: '--src', description: 'Use src layout' },
        { name: '--readme', description: 'Readme format', args: { name: 'format', suggestions: [{ name: 'md' }, { name: 'rst' }] } },
      ],
      args: { name: 'path', description: 'Project path', template: 'folders' },
    },
    {
      name: 'publish',
      description: 'Publish package to PyPI',
      options: [
        { name: ['-r', '--repository'], description: 'Repository', args: { name: 'repository' } },
        { name: ['-u', '--username'], description: 'Username', args: { name: 'username' } },
        { name: ['-p', '--password'], description: 'Password', args: { name: 'password' } },
        { name: '--cert', description: 'Certificate', args: { name: 'cert', template: 'filepaths' } },
        { name: '--client-cert', description: 'Client certificate', args: { name: 'cert', template: 'filepaths' } },
        { name: '--build', description: 'Build before publishing' },
        { name: '--dry-run', description: 'Dry run' },
        { name: '--skip-existing', description: 'Skip existing' },
      ],
    },
    {
      name: 'remove',
      description: 'Remove a dependency',
      options: [
        { name: ['-D', '--dev'], description: 'From dev dependencies' },
        { name: '--group', description: 'From group', args: { name: 'group' } },
        { name: '--dry-run', description: 'Dry run' },
        { name: '--lock', description: 'Only update lock file' },
      ],
      args: { name: 'packages', description: 'Packages to remove', isVariadic: true },
    },
    {
      name: 'run',
      description: 'Run a command in the virtual environment',
      args: { name: 'command', description: 'Command to run', isVariadic: true },
    },
    {
      name: 'search',
      description: 'Search for packages',
      args: { name: 'tokens', description: 'Search tokens', isVariadic: true },
    },
    {
      name: 'shell',
      description: 'Spawn a shell in the virtual environment',
    },
    {
      name: 'show',
      description: 'Show package info',
      options: [
        { name: '--without', description: 'Exclude groups', args: { name: 'groups' } },
        { name: '--with', description: 'Include groups', args: { name: 'groups' } },
        { name: '--only', description: 'Only groups', args: { name: 'groups' } },
        { name: '--no-dev', description: 'Skip dev (deprecated)' },
        { name: ['-t', '--tree'], description: 'Show as tree' },
        { name: ['-l', '--latest'], description: 'Show latest' },
        { name: ['-o', '--outdated'], description: 'Show outdated' },
        { name: ['-a', '--all'], description: 'Show all packages' },
        { name: '--top-level', description: 'Top level only' },
        { name: '--why', description: 'Show why installed' },
      ],
      args: { name: 'package', description: 'Package name', isOptional: true },
    },
    {
      name: 'update',
      description: 'Update dependencies',
      options: [
        { name: '--without', description: 'Exclude groups', args: { name: 'groups' } },
        { name: '--with', description: 'Include groups', args: { name: 'groups' } },
        { name: '--only', description: 'Only groups', args: { name: 'groups' } },
        { name: '--no-dev', description: 'Skip dev (deprecated)' },
        { name: '--dry-run', description: 'Dry run' },
        { name: '--lock', description: 'Only update lock file' },
      ],
      args: { name: 'packages', description: 'Packages to update', isOptional: true, isVariadic: true },
    },
    {
      name: 'version',
      description: 'Show/bump version',
      options: [
        { name: ['-s', '--short'], description: 'Short output' },
        { name: '--dry-run', description: 'Dry run' },
      ],
      args: { name: 'version', description: 'Version to set', isOptional: true, suggestions: [{ name: 'patch' }, { name: 'minor' }, { name: 'major' }, { name: 'prepatch' }, { name: 'preminor' }, { name: 'premajor' }, { name: 'prerelease' }] },
    },
    {
      name: 'env',
      description: 'Manage virtual environments',
      subcommands: [
        { name: 'info', description: 'Show environment info', options: [{ name: ['-p', '--path'], description: 'Only path' }, { name: ['-e', '--executable'], description: 'Only executable' }] },
        { name: 'list', description: 'List environments', options: [{ name: '--full-path', description: 'Show full paths' }] },
        { name: 'remove', description: 'Remove environment', options: [{ name: '--all', description: 'Remove all' }], args: { name: 'python', description: 'Python version', isOptional: true, isVariadic: true } },
        { name: 'use', description: 'Use Python version', args: { name: 'python', description: 'Python version' } },
      ],
    },
    {
      name: 'cache',
      description: 'Manage cache',
      subcommands: [
        { name: 'clear', description: 'Clear cache', options: [{ name: '--all', description: 'Clear all' }], args: { name: 'cache', description: 'Cache to clear', isOptional: true, isVariadic: true } },
        { name: 'list', description: 'List cache' },
      ],
    },
    {
      name: 'source',
      description: 'Manage sources',
      subcommands: [
        { name: 'add', description: 'Add source', options: [{ name: '--default', description: 'Make default' }, { name: '--secondary', description: 'Make secondary' }, { name: '--priority', description: 'Priority', args: { name: 'priority', suggestions: [{ name: 'default' }, { name: 'primary' }, { name: 'secondary' }, { name: 'supplemental' }, { name: 'explicit' }] } }], args: [{ name: 'name' }, { name: 'url' }] },
        { name: 'remove', description: 'Remove source', args: { name: 'name' } },
        { name: 'show', description: 'Show sources', args: { name: 'name', isOptional: true } },
      ],
    },
    {
      name: 'self',
      description: 'Manage Poetry itself',
      subcommands: [
        { name: 'add', description: 'Add plugin', options: [{ name: '--dry-run' }, { name: '--allow-prereleases' }], args: { name: 'plugins', isVariadic: true } },
        { name: 'install', description: 'Install Poetry', options: [{ name: '--sync' }, { name: '--dry-run' }] },
        { name: 'lock', description: 'Lock Poetry dependencies', options: [{ name: '--no-update' }, { name: '--check' }] },
        { name: 'remove', description: 'Remove plugin', options: [{ name: '--dry-run' }], args: { name: 'plugins', isVariadic: true } },
        { name: 'show', description: 'Show plugins', options: [{ name: '--addons' }, { name: ['-t', '--tree'] }] },
        { name: 'update', description: 'Update Poetry', options: [{ name: '--dry-run' }] },
      ],
    },
  ],
};
