// Python interpreter
import { CompletionSpec, Suggestion } from '../types.js';

export const pythonSpec: CompletionSpec = {
  name: 'python',
  description: 'Python interpreter',
  options: [
    { name: '-c', description: 'Execute Python code', args: { name: 'command', description: 'Python code to execute' } },
    { name: '-m', description: 'Run library module as a script', args: { 
      name: 'module', 
      description: 'Module name',
      suggestions: [
        { name: 'pip', description: 'Package installer' },
        { name: 'venv', description: 'Create virtual environment' },
        { name: 'http.server', description: 'Simple HTTP server' },
        { name: 'json.tool', description: 'JSON formatter' },
        { name: 'pdb', description: 'Python debugger' },
        { name: 'unittest', description: 'Run unit tests' },
        { name: 'pytest', description: 'Run pytest tests' },
        { name: 'timeit', description: 'Time small code snippets' },
        { name: 'cProfile', description: 'Profile Python code' },
        { name: 'pydoc', description: 'Documentation browser' },
        { name: 'ensurepip', description: 'Bootstrap pip' },
        { name: 'compileall', description: 'Compile Python files' },
        { name: 'zipfile', description: 'Zip file utility' },
        { name: 'tarfile', description: 'Tar file utility' },
        { name: 'base64', description: 'Base64 encode/decode' },
        { name: 'gzip', description: 'Gzip utility' },
        { name: 'webbrowser', description: 'Open URL in browser' },
        { name: 'calendar', description: 'Print calendar' },
        { name: 'doctest', description: 'Run doctests' },
        { name: 'site', description: 'Site configuration' },
        { name: 'sysconfig', description: 'Python configuration' },
        { name: 'asyncio', description: 'Asyncio utilities' },
        { name: 'tokenize', description: 'Tokenize Python code' },
        { name: 'trace', description: 'Trace program execution' },
        { name: 'dis', description: 'Disassembler' },
        { name: 'pickletools', description: 'Pickle utilities' },
        { name: 'platform', description: 'Platform info' },
        { name: 'idlelib', description: 'IDLE IDE' },
        { name: 'turtle', description: 'Turtle graphics' },
        { name: 'this', description: 'The Zen of Python' },
        { name: 'antigravity', description: 'Easter egg' },
      ],
    }},
    { name: '-i', description: 'Inspect interactively after running script' },
    { name: '-O', description: 'Optimize bytecode' },
    { name: '-OO', description: 'Remove docstrings and optimize' },
    { name: '-B', description: 'Dont write .pyc files' },
    { name: '-b', description: 'Issue warnings about bytes/str comparisons' },
    { name: '-bb', description: 'Issue errors about bytes/str comparisons' },
    { name: '-d', description: 'Debug output from parser' },
    { name: '-E', description: 'Ignore environment variables' },
    { name: '-h', description: 'Print help message' },
    { name: '--help', description: 'Print help message' },
    { name: '-I', description: 'Isolated mode' },
    { name: '-q', description: 'Quiet mode (no copyright and version)' },
    { name: '-s', description: 'Dont add user site-packages to sys.path' },
    { name: '-S', description: 'Dont imply import site' },
    { name: '-u', description: 'Unbuffered stdout and stderr' },
    { name: '-v', description: 'Verbose mode' },
    { name: '-V', description: 'Print version' },
    { name: '--version', description: 'Print version' },
    { name: '-W', description: 'Warning control', args: { 
      name: 'action',
      suggestions: [
        { name: 'default', description: 'Print warning once' },
        { name: 'error', description: 'Treat as exception' },
        { name: 'ignore', description: 'Never print warning' },
        { name: 'always', description: 'Always print warning' },
        { name: 'module', description: 'Print once per module' },
        { name: 'once', description: 'Print only first occurrence' },
      ],
    }},
    { name: '-x', description: 'Skip first line of source' },
    { name: '-X', description: 'Set implementation-specific option', args: { 
      name: 'option',
      suggestions: [
        { name: 'faulthandler', description: 'Enable faulthandler' },
        { name: 'showrefcount', description: 'Show reference count' },
        { name: 'tracemalloc', description: 'Enable tracemalloc' },
        { name: 'showalloccount', description: 'Show allocation count' },
        { name: 'importtime', description: 'Show import time' },
        { name: 'dev', description: 'Development mode' },
        { name: 'utf8', description: 'Enable UTF-8 mode' },
        { name: 'pycache_prefix', description: 'Pycache prefix path' },
        { name: 'warn_default_encoding', description: 'Warn about encoding' },
        { name: 'no_debug_ranges', description: 'No debug ranges' },
        { name: 'frozen_modules', description: 'Frozen modules' },
      ],
    }},
    { name: '--check-hash-based-pycs', description: 'Hash-based .pyc validation', args: {
      name: 'mode',
      suggestions: [
        { name: 'default', description: 'Use default behavior' },
        { name: 'always', description: 'Always validate hash' },
        { name: 'never', description: 'Never validate hash' },
      ],
    }},
  ],
  args: {
    name: 'script',
    description: 'Python script to run',
    template: 'filepaths',
    isOptional: true,
    isVariadic: true,
  },
};

// Also export as python3 alias
export const python3Spec = { ...pythonSpec, name: 'python3' };
