// rsync - Fast, versatile, remote (and local) file-copying tool
import { CompletionSpec, Suggestion } from '../types.js';

export const rsyncSpec: CompletionSpec = {
  name: 'rsync',
  description: 'A fast, versatile, remote (and local) file-copying tool',
  options: [
    // Common options
    { name: ['-v', '--verbose'], description: 'Increase verbosity' },
    { name: ['-q', '--quiet'], description: 'Suppress non-error messages' },
    { name: '--info', description: 'Fine-grained info control', args: { name: 'FLAGS', suggestions: [
      { name: 'progress2', description: 'Progress bar' },
      { name: 'stats2', description: 'File statistics' },
      { name: 'name', description: 'File names' },
      { name: 'flist', description: 'File list info' },
    ] } },
    { name: '--debug', description: 'Fine-grained debug control', args: { name: 'FLAGS' } },
    { name: '--msgs2stderr', description: 'Send all output to stderr' },
    { name: ['-a', '--archive'], description: 'Archive mode (equals -rlptgoD)' },
    { name: ['-r', '--recursive'], description: 'Recurse into directories' },
    { name: ['-R', '--relative'], description: 'Use relative path names' },
    { name: '--no-implied-dirs', description: "Don't send implied dirs with --relative" },
    { name: ['-b', '--backup'], description: 'Make backups' },
    { name: '--backup-dir', description: 'Backup directory', args: { name: 'DIR', template: 'folders' } },
    { name: '--suffix', description: 'Backup suffix', args: { name: 'SUFFIX' } },
    { name: ['-u', '--update'], description: 'Skip files newer on receiver' },
    { name: '--inplace', description: 'Update destination files in-place' },
    { name: '--append', description: 'Append data onto shorter files' },
    { name: '--append-verify', description: 'Append with checksum verification' },
    { name: ['-d', '--dirs'], description: 'Transfer directories without recursing' },
    { name: ['-l', '--links'], description: 'Copy symlinks as symlinks' },
    { name: ['-L', '--copy-links'], description: 'Transform symlinks into referent files' },
    { name: '--copy-unsafe-links', description: 'Only unsafe symlinks are transformed' },
    { name: '--safe-links', description: 'Ignore symlinks outside source tree' },
    { name: '--munge-links', description: 'Munge symlinks to make safer' },
    { name: ['-k', '--copy-dirlinks'], description: 'Transform symlink dirs into referent' },
    { name: ['-K', '--keep-dirlinks'], description: 'Treat symlinked dirs on receiver as dirs' },
    { name: ['-H', '--hard-links'], description: 'Preserve hard links' },
    { name: ['-p', '--perms'], description: 'Preserve permissions' },
    { name: ['-E', '--executability'], description: 'Preserve executability' },
    { name: '--chmod', description: 'Affect file permissions', args: { name: 'CHMOD' } },
    { name: ['-A', '--acls'], description: 'Preserve ACLs' },
    { name: ['-X', '--xattrs'], description: 'Preserve extended attributes' },
    { name: ['-o', '--owner'], description: 'Preserve owner' },
    { name: ['-g', '--group'], description: 'Preserve group' },
    { name: '--devices', description: 'Preserve device files' },
    { name: '--specials', description: 'Preserve special files' },
    { name: ['-D'], description: 'Same as --devices --specials' },
    { name: ['-t', '--times'], description: 'Preserve modification times' },
    { name: ['-U', '--atimes'], description: 'Preserve access times' },
    { name: '--open-noatime', description: "Avoid changing atime on source" },
    { name: ['-N', '--crtimes'], description: 'Preserve create times (newness)' },
    { name: '--omit-dir-times', description: 'Omit directories from --times' },
    { name: ['-J', '--omit-link-times'], description: 'Omit symlinks from --times' },
    { name: '--super', description: 'Store special files as super-user' },
    { name: '--fake-super', description: 'Store special attrs in xattrs' },
    { name: ['-S', '--sparse'], description: 'Handle sparse files efficiently' },
    { name: '--preallocate', description: 'Allocate dest files before writing' },
    { name: ['-n', '--dry-run'], description: 'Perform trial run (no changes)' },
    { name: ['-W', '--whole-file'], description: 'Copy files whole (no delta-transfer)' },
    { name: ['-x', '--one-file-system'], description: "Don't cross filesystem boundaries" },
    { name: ['-B', '--block-size'], description: 'Force checksum block size', args: { name: 'SIZE' } },
    { name: ['-e', '--rsh'], description: 'Remote shell', args: { name: 'COMMAND', suggestions: [
      { name: 'ssh' },
      { name: 'ssh -p 22' },
      { name: 'ssh -i ~/.ssh/id_rsa' },
    ] } },
    { name: '--rsync-path', description: 'Path to rsync on remote', args: { name: 'PROGRAM' } },
    { name: '--existing', description: 'Skip creating new files on receiver' },
    { name: '--ignore-non-existing', description: 'Skip creating new files on receiver' },
    { name: '--ignore-existing', description: 'Skip updating files on receiver' },
    { name: '--remove-source-files', description: 'Remove source files after transfer' },
    { name: '--del', description: 'Alias for --delete-during' },
    { name: '--delete', description: 'Delete extraneous files from dest' },
    { name: '--delete-before', description: 'Delete before transfer' },
    { name: '--delete-during', description: 'Delete during transfer' },
    { name: '--delete-delay', description: 'Delete after transfer' },
    { name: '--delete-after', description: 'Delete after transfer' },
    { name: '--delete-excluded', description: 'Also delete excluded files' },
    { name: '--ignore-missing-args', description: 'Ignore missing source args' },
    { name: '--delete-missing-args', description: 'Delete missing source args' },
    { name: '--ignore-errors', description: 'Delete even with I/O errors' },
    { name: '--force', description: 'Force deletion of dirs even if not empty' },
    { name: '--max-delete', description: 'Max file deletions', args: { name: 'NUM' } },
    { name: '--max-size', description: 'Max file size to transfer', args: { name: 'SIZE' } },
    { name: '--min-size', description: 'Min file size to transfer', args: { name: 'SIZE' } },
    { name: '--partial', description: 'Keep partially transferred files' },
    { name: '--partial-dir', description: 'Put partial files in DIR', args: { name: 'DIR', template: 'folders' } },
    { name: '--delay-updates', description: 'Put all updated files in place at end' },
    { name: ['-m', '--prune-empty-dirs'], description: 'Prune empty directory chains' },
    { name: '--numeric-ids', description: "Don't map uid/gid by name" },
    { name: '--usermap', description: 'Custom username mapping', args: { name: 'STRING' } },
    { name: '--groupmap', description: 'Custom groupname mapping', args: { name: 'STRING' } },
    { name: '--chown', description: 'Set ownership', args: { name: 'USER:GROUP' } },
    { name: '--timeout', description: 'Set I/O timeout', args: { name: 'SECONDS' } },
    { name: '--contimeout', description: 'Set connect timeout', args: { name: 'SECONDS' } },
    { name: ['-I', '--ignore-times'], description: "Don't skip files matching size and time" },
    { name: '--size-only', description: 'Skip files that match in size' },
    { name: '--modify-window', description: 'Compare mod times with accuracy', args: { name: 'NUM' } },
    { name: ['-T', '--temp-dir'], description: 'Create temp files in DIR', args: { name: 'DIR', template: 'folders' } },
    { name: ['-y', '--fuzzy'], description: 'Find similar file for basis' },
    { name: '--compare-dest', description: 'Compare against files in DIR', args: { name: 'DIR', template: 'folders' } },
    { name: '--copy-dest', description: 'Copy from unchanged files in DIR', args: { name: 'DIR', template: 'folders' } },
    { name: '--link-dest', description: 'Hardlink to files in DIR', args: { name: 'DIR', template: 'folders' } },
    { name: ['-z', '--compress'], description: 'Compress file data during transfer' },
    { name: '--compress-level', description: 'Compression level', args: { name: 'NUM' } },
    { name: '--skip-compress', description: 'Skip compress files with suffix in LIST', args: { name: 'LIST' } },
    { name: ['-C', '--cvs-exclude'], description: 'Auto-ignore CVS files' },
    { name: ['-f', '--filter'], description: 'Add filter rule', args: { name: 'RULE' } },
    { name: ['-F'], description: 'Same as --filter="dir-merge /.rsync-filter"' },
    { name: '--exclude', description: 'Exclude pattern', args: { name: 'PATTERN' } },
    { name: '--exclude-from', description: 'Read exclude patterns from FILE', args: { name: 'FILE', template: 'filepaths' } },
    { name: '--include', description: 'Include pattern', args: { name: 'PATTERN' } },
    { name: '--include-from', description: 'Read include patterns from FILE', args: { name: 'FILE', template: 'filepaths' } },
    { name: '--files-from', description: 'Read source files from FILE', args: { name: 'FILE', template: 'filepaths' } },
    { name: ['-0', '--from0'], description: 'Input items are separated by null' },
    { name: ['-s', '--protect-args'], description: 'No space-splitting; wildcard chars only' },
    { name: '--copy-as', description: 'Copy as USER and GROUP', args: { name: 'USER[:GROUP]' } },
    { name: '--address', description: 'Bind address', args: { name: 'ADDRESS' } },
    { name: '--port', description: 'Remote port', args: { name: 'PORT' } },
    { name: '--sockopts', description: 'Socket options', args: { name: 'OPTIONS' } },
    { name: '--blocking-io', description: 'Use blocking I/O' },
    { name: '--outbuf', description: 'Output buffering', args: { name: 'MODE', suggestions: [
      { name: 'N', description: 'None' },
      { name: 'L', description: 'Line' },
      { name: 'B', description: 'Block' },
    ] } },
    { name: '--stats', description: 'Output file transfer stats' },
    { name: ['-8', '--8-bit-output'], description: 'Allow high-bit chars in output' },
    { name: ['-h', '--human-readable'], description: 'Human-readable numbers' },
    { name: '--progress', description: 'Show progress during transfer' },
    { name: ['-P'], description: 'Same as --partial --progress' },
    { name: ['-i', '--itemize-changes'], description: 'Output change summary' },
    { name: '--out-format', description: 'Output format for updates', args: { name: 'FORMAT' } },
    { name: '--log-file', description: 'Log to FILE', args: { name: 'FILE', template: 'filepaths' } },
    { name: '--log-file-format', description: 'Log updates using FORMAT', args: { name: 'FORMAT' } },
    { name: '--password-file', description: 'Read daemon password from FILE', args: { name: 'FILE', template: 'filepaths' } },
    { name: '--list-only', description: 'List files only' },
    { name: '--bwlimit', description: 'Limit bandwidth', args: { name: 'RATE' } },
    { name: '--write-batch', description: 'Write batch to FILE', args: { name: 'FILE', template: 'filepaths' } },
    { name: '--only-write-batch', description: 'Like --write-batch but no transfer', args: { name: 'FILE', template: 'filepaths' } },
    { name: '--read-batch', description: 'Read batch from FILE', args: { name: 'FILE', template: 'filepaths' } },
    { name: '--protocol', description: 'Force older protocol', args: { name: 'NUM' } },
    { name: '--iconv', description: 'Charset conversion', args: { name: 'CONVERT_SPEC' } },
    { name: '--checksum-seed', description: 'Set block checksum seed', args: { name: 'NUM' } },
    { name: ['-4', '--ipv4'], description: 'Prefer IPv4' },
    { name: ['-6', '--ipv6'], description: 'Prefer IPv6' },
    { name: ['-c', '--checksum'], description: 'Skip based on checksum, not time' },
    { name: '--version', description: 'Print version number' },
    { name: ['-h', '--help'], description: 'Show help' },
  ],
  args: [
    { name: 'source', description: 'Source path(s)', template: 'filepaths', isVariadic: true },
    { name: 'destination', description: 'Destination path', template: 'filepaths' },
  ],
};
