// SSH - Secure Shell client
import { CompletionSpec, Suggestion } from '../types.js';

export const sshSpec: CompletionSpec = {
  name: 'ssh',
  description: 'OpenSSH remote login client',
  options: [
    { name: '-1', description: 'Force protocol version 1' },
    { name: '-2', description: 'Force protocol version 2' },
    { name: '-4', description: 'Use IPv4 only' },
    { name: '-6', description: 'Use IPv6 only' },
    { name: '-A', description: 'Enable agent forwarding' },
    { name: '-a', description: 'Disable agent forwarding' },
    { name: '-B', description: 'Bind interface', args: { name: 'interface' } },
    { name: '-b', description: 'Bind address', args: { name: 'bind_address' } },
    { name: '-C', description: 'Enable compression' },
    { name: '-c', description: 'Cipher spec', args: { name: 'cipher', suggestions: [
      { name: 'aes128-ctr' }, { name: 'aes192-ctr' }, { name: 'aes256-ctr' },
      { name: 'aes128-gcm@openssh.com' }, { name: 'aes256-gcm@openssh.com' },
      { name: 'chacha20-poly1305@openssh.com' },
    ] } },
    { name: '-D', description: 'Dynamic SOCKS proxy', args: { name: '[bind_address:]port' } },
    { name: '-E', description: 'Log file', args: { name: 'log_file', template: 'filepaths' } },
    { name: '-e', description: 'Escape character', args: { name: 'char' } },
    { name: '-F', description: 'Config file', args: { name: 'configfile', template: 'filepaths' } },
    { name: '-f', description: 'Go to background' },
    { name: '-G', description: 'Print configuration' },
    { name: '-g', description: 'Allow remote port forwarding' },
    { name: '-I', description: 'PKCS#11 provider', args: { name: 'pkcs11' } },
    { name: '-i', description: 'Identity file', args: { name: 'identity_file', template: 'filepaths' } },
    { name: '-J', description: 'Jump host', args: { name: '[user@]host[:port]' } },
    { name: '-K', description: 'Enable GSSAPI auth' },
    { name: '-k', description: 'Disable GSSAPI auth' },
    { name: '-L', description: 'Local port forward', args: { name: '[bind:]port:host:hostport' } },
    { name: '-l', description: 'Login name', args: { name: 'login_name' } },
    { name: '-M', description: 'Master mode for connection sharing' },
    { name: '-m', description: 'MAC algorithms', args: { name: 'mac_spec' } },
    { name: '-N', description: 'No remote command' },
    { name: '-n', description: 'Redirect stdin from /dev/null' },
    { name: '-O', description: 'Control command', args: { name: 'ctl_cmd', suggestions: [
      { name: 'check', description: 'Check master process' },
      { name: 'forward', description: 'Request forwardings' },
      { name: 'cancel', description: 'Cancel forwardings' },
      { name: 'exit', description: 'Request master exit' },
      { name: 'stop', description: 'No more multiplexing' },
    ] } },
    { name: '-o', description: 'Configuration option', args: { name: 'option', suggestions: [
      { name: 'AddKeysToAgent=yes' }, { name: 'AddKeysToAgent=no' },
      { name: 'AddressFamily=inet' }, { name: 'AddressFamily=inet6' }, { name: 'AddressFamily=any' },
      { name: 'BatchMode=yes' }, { name: 'BatchMode=no' },
      { name: 'Compression=yes' }, { name: 'Compression=no' },
      { name: 'ConnectionAttempts=' }, { name: 'ConnectTimeout=' },
      { name: 'ControlMaster=auto' }, { name: 'ControlMaster=yes' }, { name: 'ControlMaster=no' },
      { name: 'ControlPath=' }, { name: 'ControlPersist=' },
      { name: 'ForwardAgent=yes' }, { name: 'ForwardAgent=no' },
      { name: 'ForwardX11=yes' }, { name: 'ForwardX11=no' },
      { name: 'HashKnownHosts=yes' }, { name: 'HashKnownHosts=no' },
      { name: 'HostKeyAlgorithms=' },
      { name: 'IdentityFile=' }, { name: 'IdentitiesOnly=yes' }, { name: 'IdentitiesOnly=no' },
      { name: 'LocalForward=' }, { name: 'RemoteForward=' },
      { name: 'LogLevel=QUIET' }, { name: 'LogLevel=FATAL' }, { name: 'LogLevel=ERROR' },
      { name: 'LogLevel=INFO' }, { name: 'LogLevel=VERBOSE' }, { name: 'LogLevel=DEBUG' },
      { name: 'Port=' }, { name: 'PreferredAuthentications=' },
      { name: 'ProxyCommand=' }, { name: 'ProxyJump=' },
      { name: 'PubkeyAuthentication=yes' }, { name: 'PubkeyAuthentication=no' },
      { name: 'ServerAliveInterval=' }, { name: 'ServerAliveCountMax=' },
      { name: 'StrictHostKeyChecking=yes' }, { name: 'StrictHostKeyChecking=no' }, { name: 'StrictHostKeyChecking=ask' },
      { name: 'TCPKeepAlive=yes' }, { name: 'TCPKeepAlive=no' },
      { name: 'User=' }, { name: 'UserKnownHostsFile=' },
      { name: 'VisualHostKey=yes' }, { name: 'VisualHostKey=no' },
    ] } },
    { name: '-p', description: 'Port', args: { name: 'port' } },
    { name: '-Q', description: 'Query supported algorithms', args: { name: 'query', suggestions: [
      { name: 'cipher' }, { name: 'cipher-auth' }, { name: 'help' },
      { name: 'mac' }, { name: 'kex' }, { name: 'key' }, { name: 'key-cert' },
      { name: 'key-plain' }, { name: 'key-sig' }, { name: 'protocol-version' },
      { name: 'sig' },
    ] } },
    { name: '-q', description: 'Quiet mode' },
    { name: '-R', description: 'Remote port forward', args: { name: '[bind:]port:host:hostport' } },
    { name: '-S', description: 'Control socket', args: { name: 'ctl_path', template: 'filepaths' } },
    { name: '-s', description: 'Invoke subsystem' },
    { name: '-T', description: 'Disable pseudo-tty' },
    { name: '-t', description: 'Force pseudo-tty' },
    { name: '-V', description: 'Display version' },
    { name: '-v', description: 'Verbose mode' },
    { name: '-W', description: 'Forward I/O', args: { name: 'host:port' } },
    { name: '-w', description: 'Tunnel device', args: { name: 'local_tun[:remote_tun]' } },
    { name: '-X', description: 'Enable X11 forwarding' },
    { name: '-x', description: 'Disable X11 forwarding' },
    { name: '-Y', description: 'Enable trusted X11 forwarding' },
    { name: '-y', description: 'Send logs to syslog' },
  ],
  args: [
    { name: 'destination', description: '[user@]hostname' },
    { name: 'command', description: 'Remote command', isOptional: true, isVariadic: true },
  ],
};
