// tmux - Terminal multiplexer
import { CompletionSpec, Suggestion } from '../types.js';

export const tmuxSpec: CompletionSpec = {
  name: 'tmux',
  description: 'Terminal multiplexer',
  options: [
    { name: '-2', description: 'Force 256 colors' },
    { name: '-C', description: 'Start in control mode' },
    { name: '-CC', description: 'Start in control mode with echo disabled' },
    { name: '-c', description: 'Execute shell command', args: { name: 'shell-command' } },
    { name: '-D', description: 'Do not start the server as a daemon' },
    { name: '-f', description: 'Specify configuration file', args: { name: 'file', template: 'filepaths' } },
    { name: '-L', description: 'Socket name', args: { name: 'socket-name' } },
    { name: '-l', description: 'Behave as a login shell' },
    { name: '-N', description: 'Do not start server even if command requires it' },
    { name: '-S', description: 'Socket path', args: { name: 'socket-path', template: 'filepaths' } },
    { name: '-T', description: 'Set terminal features', args: { name: 'features' } },
    { name: '-u', description: 'UTF-8 mode' },
    { name: '-v', description: 'Verbose logging' },
    { name: '-V', description: 'Report version' },
  ],
  subcommands: [
    // Session commands
    {
      name: 'new-session',
      description: 'Create a new session',
      options: [
        { name: '-A', description: 'Attach to existing session if exists' },
        { name: '-c', description: 'Start directory', args: { name: 'dir', template: 'folders' } },
        { name: '-d', description: 'Do not attach to new session' },
        { name: '-D', description: 'Detach other clients attached to session' },
        { name: '-E', description: 'Do not apply update-environment option' },
        { name: '-e', description: 'Set environment variable', args: { name: 'KEY=VALUE' } },
        { name: '-f', description: 'Set client flags', args: { name: 'flags' } },
        { name: '-F', description: 'Format for output', args: { name: 'format' } },
        { name: '-n', description: 'Window name', args: { name: 'window-name' } },
        { name: '-P', description: 'Print info about new session' },
        { name: '-s', description: 'Session name', args: { name: 'session-name' } },
        { name: '-t', description: 'Group with target session', args: { name: 'target-session' } },
        { name: '-x', description: 'Width', args: { name: 'width' } },
        { name: '-X', description: 'Detach other clients on attach' },
        { name: '-y', description: 'Height', args: { name: 'height' } },
      ],
      args: { name: 'shell-command', isOptional: true },
    },
    {
      name: 'new',
      description: 'Alias for new-session',
    },
    {
      name: 'attach-session',
      description: 'Attach to an existing session',
      options: [
        { name: '-c', description: 'Working directory', args: { name: 'dir', template: 'folders' } },
        { name: '-d', description: 'Detach other clients' },
        { name: '-E', description: 'Do not apply update-environment' },
        { name: '-f', description: 'Set client flags', args: { name: 'flags' } },
        { name: '-r', description: 'Attach in read-only mode' },
        { name: '-t', description: 'Target session', args: { name: 'target-session' } },
        { name: '-x', description: 'Width', args: { name: 'width' } },
        { name: '-y', description: 'Height', args: { name: 'height' } },
      ],
    },
    {
      name: 'attach',
      description: 'Alias for attach-session',
      options: [
        { name: '-d', description: 'Detach other clients' },
        { name: '-r', description: 'Read-only mode' },
        { name: '-t', description: 'Target session', args: { name: 'target-session' } },
      ],
    },
    {
      name: 'a',
      description: 'Alias for attach-session',
    },
    {
      name: 'detach-client',
      description: 'Detach a client from the server',
      options: [
        { name: '-a', description: 'Kill all but target client' },
        { name: '-E', description: 'Run shell command' },
        { name: '-P', description: 'Detach using SIGHUP' },
        { name: '-s', description: 'Target session', args: { name: 'target-session' } },
        { name: '-t', description: 'Target client', args: { name: 'target-client' } },
      ],
    },
    {
      name: 'detach',
      description: 'Alias for detach-client',
    },
    {
      name: 'kill-session',
      description: 'Destroy a session',
      options: [
        { name: '-a', description: 'Kill all sessions except target' },
        { name: '-C', description: 'Clear alerts in session' },
        { name: '-t', description: 'Target session', args: { name: 'target-session' } },
      ],
    },
    {
      name: 'kill-server',
      description: 'Kill the tmux server',
    },
    {
      name: 'list-sessions',
      description: 'List sessions',
      options: [
        { name: '-F', description: 'Format output', args: { name: 'format' } },
        { name: '-f', description: 'Filter sessions', args: { name: 'filter' } },
      ],
    },
    {
      name: 'ls',
      description: 'Alias for list-sessions',
    },
    {
      name: 'rename-session',
      description: 'Rename a session',
      options: [
        { name: '-t', description: 'Target session', args: { name: 'target-session' } },
      ],
      args: { name: 'new-name' },
    },
    {
      name: 'rename',
      description: 'Alias for rename-session',
    },
    {
      name: 'has-session',
      description: 'Check if a session exists',
      options: [
        { name: '-t', description: 'Target session', args: { name: 'target-session' } },
      ],
    },
    {
      name: 'has',
      description: 'Alias for has-session',
    },
    // Window commands
    {
      name: 'new-window',
      description: 'Create a new window',
      options: [
        { name: '-a', description: 'Insert after target window' },
        { name: '-b', description: 'Insert before target window' },
        { name: '-c', description: 'Start directory', args: { name: 'dir', template: 'folders' } },
        { name: '-d', description: 'Do not make new window active' },
        { name: '-e', description: 'Set environment variable', args: { name: 'KEY=VALUE' } },
        { name: '-F', description: 'Format output', args: { name: 'format' } },
        { name: '-k', description: 'Destroy if window already exists' },
        { name: '-n', description: 'Window name', args: { name: 'window-name' } },
        { name: '-P', description: 'Print info about new window' },
        { name: '-S', description: 'Suppress switching to window' },
        { name: '-t', description: 'Target window', args: { name: 'target-window' } },
      ],
      args: { name: 'shell-command', isOptional: true },
    },
    {
      name: 'neww',
      description: 'Alias for new-window',
    },
    {
      name: 'kill-window',
      description: 'Destroy a window',
      options: [
        { name: '-a', description: 'Kill all windows except target' },
        { name: '-t', description: 'Target window', args: { name: 'target-window' } },
      ],
    },
    {
      name: 'killw',
      description: 'Alias for kill-window',
    },
    {
      name: 'list-windows',
      description: 'List windows',
      options: [
        { name: '-a', description: 'List all windows' },
        { name: '-F', description: 'Format output', args: { name: 'format' } },
        { name: '-f', description: 'Filter', args: { name: 'filter' } },
        { name: '-t', description: 'Target session', args: { name: 'target-session' } },
      ],
    },
    {
      name: 'lsw',
      description: 'Alias for list-windows',
    },
    {
      name: 'rename-window',
      description: 'Rename a window',
      options: [
        { name: '-t', description: 'Target window', args: { name: 'target-window' } },
      ],
      args: { name: 'new-name' },
    },
    {
      name: 'renamew',
      description: 'Alias for rename-window',
    },
    {
      name: 'select-window',
      description: 'Select a window',
      options: [
        { name: '-l', description: 'Select last window' },
        { name: '-n', description: 'Select next window' },
        { name: '-p', description: 'Select previous window' },
        { name: '-t', description: 'Target window', args: { name: 'target-window' } },
        { name: '-T', description: 'Toggle if already selected' },
      ],
    },
    {
      name: 'selectw',
      description: 'Alias for select-window',
    },
    {
      name: 'next-window',
      description: 'Move to the next window',
      options: [
        { name: '-a', description: 'Move to next window with alert' },
        { name: '-t', description: 'Target session', args: { name: 'target-session' } },
      ],
    },
    {
      name: 'next',
      description: 'Alias for next-window',
    },
    {
      name: 'previous-window',
      description: 'Move to the previous window',
      options: [
        { name: '-a', description: 'Move to previous window with alert' },
        { name: '-t', description: 'Target session', args: { name: 'target-session' } },
      ],
    },
    {
      name: 'prev',
      description: 'Alias for previous-window',
    },
    {
      name: 'last-window',
      description: 'Select the last window',
      options: [
        { name: '-t', description: 'Target session', args: { name: 'target-session' } },
      ],
    },
    {
      name: 'last',
      description: 'Alias for last-window',
    },
    // Pane commands
    {
      name: 'split-window',
      description: 'Split a window into panes',
      options: [
        { name: '-b', description: 'Create left/above' },
        { name: '-c', description: 'Start directory', args: { name: 'dir', template: 'folders' } },
        { name: '-d', description: 'Do not make new pane active' },
        { name: '-e', description: 'Set environment variable', args: { name: 'KEY=VALUE' } },
        { name: '-f', description: 'Create spanning full height/width' },
        { name: '-F', description: 'Format output', args: { name: 'format' } },
        { name: '-h', description: 'Split horizontally' },
        { name: '-I', description: 'Create empty pane' },
        { name: '-l', description: 'Size in lines/columns', args: { name: 'size' } },
        { name: '-p', description: 'Size in percent', args: { name: 'percentage' } },
        { name: '-P', description: 'Print info about new pane' },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
        { name: '-v', description: 'Split vertically (default)' },
        { name: '-Z', description: 'Zoom if pane is active' },
      ],
      args: { name: 'shell-command', isOptional: true },
    },
    {
      name: 'splitw',
      description: 'Alias for split-window',
    },
    {
      name: 'kill-pane',
      description: 'Destroy a pane',
      options: [
        { name: '-a', description: 'Kill all panes except target' },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
      ],
    },
    {
      name: 'killp',
      description: 'Alias for kill-pane',
    },
    {
      name: 'list-panes',
      description: 'List panes',
      options: [
        { name: '-a', description: 'List all panes' },
        { name: '-F', description: 'Format output', args: { name: 'format' } },
        { name: '-f', description: 'Filter', args: { name: 'filter' } },
        { name: '-s', description: 'List panes in session' },
        { name: '-t', description: 'Target', args: { name: 'target' } },
      ],
    },
    {
      name: 'lsp',
      description: 'Alias for list-panes',
    },
    {
      name: 'select-pane',
      description: 'Select a pane',
      options: [
        { name: '-D', description: 'Select pane below' },
        { name: '-d', description: 'Disable input' },
        { name: '-e', description: 'Enable input' },
        { name: '-g', description: 'Show style' },
        { name: '-L', description: 'Select pane left' },
        { name: '-l', description: 'Select last pane' },
        { name: '-M', description: 'Clear marked pane' },
        { name: '-m', description: 'Set marked pane' },
        { name: '-P', description: 'Set style', args: { name: 'style' } },
        { name: '-R', description: 'Select pane right' },
        { name: '-T', description: 'Set title', args: { name: 'title' } },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
        { name: '-U', description: 'Select pane above' },
        { name: '-Z', description: 'Keep zoomed if zoomed' },
      ],
    },
    {
      name: 'selectp',
      description: 'Alias for select-pane',
    },
    {
      name: 'resize-pane',
      description: 'Resize a pane',
      options: [
        { name: '-D', description: 'Resize down', args: { name: 'amount', isOptional: true } },
        { name: '-L', description: 'Resize left', args: { name: 'amount', isOptional: true } },
        { name: '-M', description: 'Begin mouse resize' },
        { name: '-R', description: 'Resize right', args: { name: 'amount', isOptional: true } },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
        { name: '-U', description: 'Resize up', args: { name: 'amount', isOptional: true } },
        { name: '-x', description: 'Set width', args: { name: 'width' } },
        { name: '-y', description: 'Set height', args: { name: 'height' } },
        { name: '-Z', description: 'Toggle zoom' },
      ],
    },
    {
      name: 'resizep',
      description: 'Alias for resize-pane',
    },
    {
      name: 'swap-pane',
      description: 'Swap two panes',
      options: [
        { name: '-d', description: 'Do not change active pane' },
        { name: '-D', description: 'Swap with next pane' },
        { name: '-s', description: 'Source pane', args: { name: 'src-pane' } },
        { name: '-t', description: 'Destination pane', args: { name: 'dst-pane' } },
        { name: '-U', description: 'Swap with previous pane' },
        { name: '-Z', description: 'Keep zoomed' },
      ],
    },
    {
      name: 'swapp',
      description: 'Alias for swap-pane',
    },
    // Copy mode
    {
      name: 'copy-mode',
      description: 'Enter copy mode',
      options: [
        { name: '-e', description: 'Scroll to bottom on output' },
        { name: '-H', description: 'Hide position indicator' },
        { name: '-M', description: 'Begin mouse drag' },
        { name: '-q', description: 'Cancel copy mode if active' },
        { name: '-s', description: 'Source pane', args: { name: 'src-pane' } },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
        { name: '-u', description: 'Scroll up one page' },
      ],
    },
    // Misc commands
    {
      name: 'source-file',
      description: 'Execute commands from a file',
      options: [
        { name: '-F', description: 'Expand formats in file' },
        { name: '-n', description: 'Report parsing errors' },
        { name: '-q', description: 'Suppress errors if file missing' },
        { name: '-v', description: 'Show parsed commands' },
      ],
      args: { name: 'path', template: 'filepaths', isVariadic: true },
    },
    {
      name: 'source',
      description: 'Alias for source-file',
    },
    {
      name: 'set-option',
      description: 'Set a session option',
      options: [
        { name: '-a', description: 'Append to string option' },
        { name: '-F', description: 'Expand formats' },
        { name: '-g', description: 'Set global option' },
        { name: '-o', description: 'Prevent override' },
        { name: '-p', description: 'Set pane option' },
        { name: '-q', description: 'Suppress errors' },
        { name: '-s', description: 'Set server option' },
        { name: '-t', description: 'Target', args: { name: 'target' } },
        { name: '-u', description: 'Unset option' },
        { name: '-U', description: 'Unset option and inherit' },
        { name: '-w', description: 'Set window option' },
      ],
      args: [
        { name: 'option', description: 'Option name' },
        { name: 'value', description: 'Option value', isOptional: true },
      ],
    },
    {
      name: 'set',
      description: 'Alias for set-option',
    },
    {
      name: 'set-window-option',
      description: 'Set a window option',
      options: [
        { name: '-a', description: 'Append to string' },
        { name: '-F', description: 'Expand formats' },
        { name: '-g', description: 'Global option' },
        { name: '-o', description: 'Prevent override' },
        { name: '-q', description: 'Suppress errors' },
        { name: '-t', description: 'Target window', args: { name: 'target-window' } },
        { name: '-u', description: 'Unset option' },
      ],
      args: [
        { name: 'option', description: 'Option name' },
        { name: 'value', description: 'Option value', isOptional: true },
      ],
    },
    {
      name: 'setw',
      description: 'Alias for set-window-option',
    },
    {
      name: 'show-options',
      description: 'Show session options',
      options: [
        { name: '-A', description: 'Include inherited options' },
        { name: '-g', description: 'Show global options' },
        { name: '-H', description: 'Include hidden options' },
        { name: '-p', description: 'Show pane options' },
        { name: '-q', description: 'Suppress errors' },
        { name: '-s', description: 'Show server options' },
        { name: '-t', description: 'Target', args: { name: 'target' } },
        { name: '-v', description: 'Show only values' },
        { name: '-w', description: 'Show window options' },
      ],
      args: { name: 'option', isOptional: true },
    },
    {
      name: 'show',
      description: 'Alias for show-options',
    },
    {
      name: 'bind-key',
      description: 'Bind a key to a command',
      options: [
        { name: '-n', description: 'No prefix key needed' },
        { name: '-N', description: 'Add note', args: { name: 'note' } },
        { name: '-r', description: 'Key may repeat' },
        { name: '-T', description: 'Key table', args: { name: 'key-table' } },
      ],
      args: [
        { name: 'key', description: 'Key to bind' },
        { name: 'command', description: 'Command to run', isVariadic: true },
      ],
    },
    {
      name: 'bind',
      description: 'Alias for bind-key',
    },
    {
      name: 'unbind-key',
      description: 'Unbind a key',
      options: [
        { name: '-a', description: 'Remove all bindings' },
        { name: '-n', description: 'Unbind without prefix' },
        { name: '-q', description: 'Suppress errors' },
        { name: '-T', description: 'Key table', args: { name: 'key-table' } },
      ],
      args: { name: 'key', isOptional: true },
    },
    {
      name: 'unbind',
      description: 'Alias for unbind-key',
    },
    {
      name: 'list-keys',
      description: 'List key bindings',
      options: [
        { name: '-1', description: 'One line per key' },
        { name: '-a', description: 'List with all notes' },
        { name: '-N', description: 'List only with notes' },
        { name: '-P', description: 'Format prefix', args: { name: 'prefix' } },
        { name: '-T', description: 'Key table', args: { name: 'key-table' } },
      ],
      args: { name: 'key', isOptional: true },
    },
    {
      name: 'lsk',
      description: 'Alias for list-keys',
    },
    {
      name: 'list-commands',
      description: 'List tmux commands',
      options: [
        { name: '-F', description: 'Format output', args: { name: 'format' } },
      ],
      args: { name: 'command', isOptional: true },
    },
    {
      name: 'lscm',
      description: 'Alias for list-commands',
    },
    {
      name: 'info',
      description: 'Show server information',
    },
    {
      name: 'display-message',
      description: 'Display a message',
      options: [
        { name: '-a', description: 'List alerts' },
        { name: '-c', description: 'Target client', args: { name: 'target-client' } },
        { name: '-d', description: 'Delay', args: { name: 'delay' } },
        { name: '-I', description: 'Do not wait for input' },
        { name: '-l', description: 'Disable format escapes' },
        { name: '-N', description: 'Ignore style' },
        { name: '-p', description: 'Print to stdout' },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
        { name: '-v', description: 'Verbose output' },
      ],
      args: { name: 'message', isOptional: true },
    },
    {
      name: 'display',
      description: 'Alias for display-message',
    },
    {
      name: 'send-keys',
      description: 'Send key strokes to a window',
      options: [
        { name: '-F', description: 'Expand formats' },
        { name: '-H', description: 'Expect hex' },
        { name: '-K', description: 'Treat keys as key names' },
        { name: '-l', description: 'Disable lookup' },
        { name: '-M', description: 'Pass through mouse event' },
        { name: '-N', description: 'Repeat count', args: { name: 'count' } },
        { name: '-R', description: 'Reset terminal state' },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
        { name: '-X', description: 'Send to copy mode' },
      ],
      args: { name: 'key', isVariadic: true, isOptional: true },
    },
    {
      name: 'send',
      description: 'Alias for send-keys',
    },
    {
      name: 'run-shell',
      description: 'Execute a command in a shell',
      options: [
        { name: '-b', description: 'Run in background' },
        { name: '-C', description: 'Run tmux command' },
        { name: '-d', description: 'Delay', args: { name: 'delay' } },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
      ],
      args: { name: 'shell-command', isOptional: true },
    },
    {
      name: 'run',
      description: 'Alias for run-shell',
    },
    {
      name: 'pipe-pane',
      description: 'Pipe pane output to a shell command',
      options: [
        { name: '-I', description: 'Pipe stdout to pane' },
        { name: '-O', description: 'Pipe pane to stdin' },
        { name: '-o', description: 'Only open pipe if not open' },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
      ],
      args: { name: 'shell-command', isOptional: true },
    },
    {
      name: 'pipep',
      description: 'Alias for pipe-pane',
    },
    {
      name: 'capture-pane',
      description: 'Capture the contents of a pane',
      options: [
        { name: '-a', description: 'Use alternate screen' },
        { name: '-b', description: 'Buffer name', args: { name: 'buffer-name' } },
        { name: '-C', description: 'Escape non-printable' },
        { name: '-e', description: 'Include escape sequences' },
        { name: '-E', description: 'End line', args: { name: 'end-line' } },
        { name: '-J', description: 'Join wrapped lines' },
        { name: '-N', description: 'Preserve trailing spaces' },
        { name: '-p', description: 'Print to stdout' },
        { name: '-P', description: 'Escape for paste' },
        { name: '-q', description: 'Suppress errors' },
        { name: '-S', description: 'Start line', args: { name: 'start-line' } },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
      ],
    },
    {
      name: 'capturep',
      description: 'Alias for capture-pane',
    },
    {
      name: 'save-buffer',
      description: 'Save a paste buffer to a file',
      options: [
        { name: '-a', description: 'Append to file' },
        { name: '-b', description: 'Buffer name', args: { name: 'buffer-name' } },
      ],
      args: { name: 'path', template: 'filepaths' },
    },
    {
      name: 'saveb',
      description: 'Alias for save-buffer',
    },
    {
      name: 'load-buffer',
      description: 'Load a paste buffer from a file',
      options: [
        { name: '-b', description: 'Buffer name', args: { name: 'buffer-name' } },
        { name: '-t', description: 'Target client', args: { name: 'target-client' } },
        { name: '-w', description: 'Send to clipboard' },
      ],
      args: { name: 'path', template: 'filepaths' },
    },
    {
      name: 'loadb',
      description: 'Alias for load-buffer',
    },
    {
      name: 'list-buffers',
      description: 'List paste buffers',
      options: [
        { name: '-F', description: 'Format output', args: { name: 'format' } },
        { name: '-f', description: 'Filter', args: { name: 'filter' } },
      ],
    },
    {
      name: 'lsb',
      description: 'Alias for list-buffers',
    },
    {
      name: 'delete-buffer',
      description: 'Delete a paste buffer',
      options: [
        { name: '-b', description: 'Buffer name', args: { name: 'buffer-name' } },
      ],
    },
    {
      name: 'deleteb',
      description: 'Alias for delete-buffer',
    },
    {
      name: 'choose-buffer',
      description: 'Put a buffer in paste mode',
      options: [
        { name: '-F', description: 'Format output', args: { name: 'format' } },
        { name: '-f', description: 'Filter', args: { name: 'filter' } },
        { name: '-K', description: 'Initial key', args: { name: 'key-format' } },
        { name: '-N', description: 'Start scrolled down' },
        { name: '-O', description: 'Sort order', args: { name: 'sort-order' } },
        { name: '-r', description: 'Reverse sort' },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
        { name: '-Z', description: 'Zoom pane' },
      ],
      args: { name: 'template', isOptional: true },
    },
    {
      name: 'paste-buffer',
      description: 'Insert a paste buffer into the window',
      options: [
        { name: '-b', description: 'Buffer name', args: { name: 'buffer-name' } },
        { name: '-d', description: 'Delete buffer after pasting' },
        { name: '-p', description: 'Bracket paste' },
        { name: '-r', description: 'Do not replace escape codes' },
        { name: '-s', description: 'Separator', args: { name: 'separator' } },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
      ],
    },
    {
      name: 'pasteb',
      description: 'Alias for paste-buffer',
    },
    {
      name: 'set-buffer',
      description: 'Set contents of a paste buffer',
      options: [
        { name: '-a', description: 'Append to buffer' },
        { name: '-b', description: 'Buffer name', args: { name: 'buffer-name' } },
        { name: '-n', description: 'New buffer name', args: { name: 'new-buffer-name' } },
        { name: '-t', description: 'Target client', args: { name: 'target-client' } },
        { name: '-w', description: 'Send to clipboard' },
      ],
      args: { name: 'data' },
    },
    {
      name: 'setb',
      description: 'Alias for set-buffer',
    },
    {
      name: 'show-buffer',
      description: 'Display the contents of a paste buffer',
      options: [
        { name: '-b', description: 'Buffer name', args: { name: 'buffer-name' } },
      ],
    },
    {
      name: 'showb',
      description: 'Alias for show-buffer',
    },
    {
      name: 'list-clients',
      description: 'List clients attached to server',
      options: [
        { name: '-F', description: 'Format output', args: { name: 'format' } },
        { name: '-f', description: 'Filter', args: { name: 'filter' } },
        { name: '-t', description: 'Target session', args: { name: 'target-session' } },
      ],
    },
    {
      name: 'lsc',
      description: 'Alias for list-clients',
    },
    {
      name: 'switch-client',
      description: 'Switch the client to another session',
      options: [
        { name: '-c', description: 'Target client', args: { name: 'target-client' } },
        { name: '-E', description: 'Do not apply update-environment' },
        { name: '-l', description: 'Go to last session' },
        { name: '-n', description: 'Go to next session' },
        { name: '-p', description: 'Go to previous session' },
        { name: '-r', description: 'Toggle read-only mode' },
        { name: '-t', description: 'Target session', args: { name: 'target-session' } },
        { name: '-T', description: 'Key table', args: { name: 'key-table' } },
        { name: '-Z', description: 'Keep zoomed' },
      ],
    },
    {
      name: 'switchc',
      description: 'Alias for switch-client',
    },
    {
      name: 'refresh-client',
      description: 'Refresh a client',
      options: [
        { name: '-A', description: 'Allow control mode actions', args: { name: 'pane:state' } },
        { name: '-B', description: 'Set subscription', args: { name: 'name:what:format' } },
        { name: '-c', description: 'Target pane', args: { name: 'target-pane' } },
        { name: '-C', description: 'Set size', args: { name: 'XxY' } },
        { name: '-D', description: 'Move visible position' },
        { name: '-f', description: 'Set client flags', args: { name: 'flags' } },
        { name: '-F', description: 'Expand formats' },
        { name: '-l', description: 'Request clipboard' },
        { name: '-L', description: 'Move visible left' },
        { name: '-R', description: 'Move visible right' },
        { name: '-S', description: 'Only update status line' },
        { name: '-t', description: 'Target client', args: { name: 'target-client' } },
        { name: '-U', description: 'Move visible up' },
      ],
    },
    {
      name: 'refresh',
      description: 'Alias for refresh-client',
    },
    {
      name: 'suspend-client',
      description: 'Suspend a client',
      options: [
        { name: '-t', description: 'Target client', args: { name: 'target-client' } },
      ],
    },
    {
      name: 'suspendc',
      description: 'Alias for suspend-client',
    },
    {
      name: 'clock-mode',
      description: 'Enter clock mode',
      options: [
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
      ],
    },
    {
      name: 'move-window',
      description: 'Move a window to another index',
      options: [
        { name: '-a', description: 'Insert after target' },
        { name: '-b', description: 'Insert before target' },
        { name: '-d', description: 'Do not select new window' },
        { name: '-k', description: 'Kill window if exists' },
        { name: '-r', description: 'Renumber other windows' },
        { name: '-s', description: 'Source window', args: { name: 'src-window' } },
        { name: '-t', description: 'Target window', args: { name: 'dst-window' } },
      ],
    },
    {
      name: 'movew',
      description: 'Alias for move-window',
    },
    {
      name: 'move-pane',
      description: 'Move a pane into a new window',
      options: [
        { name: '-b', description: 'Insert left/above' },
        { name: '-d', description: 'Do not make pane active' },
        { name: '-f', description: 'Create full-width/height pane' },
        { name: '-h', description: 'Split horizontally' },
        { name: '-l', description: 'Size', args: { name: 'size' } },
        { name: '-p', description: 'Percentage', args: { name: 'percentage' } },
        { name: '-s', description: 'Source pane', args: { name: 'src-pane' } },
        { name: '-t', description: 'Target pane', args: { name: 'dst-pane' } },
        { name: '-v', description: 'Split vertically' },
      ],
    },
    {
      name: 'movep',
      description: 'Alias for move-pane',
    },
    {
      name: 'link-window',
      description: 'Link a window to another session',
      options: [
        { name: '-a', description: 'Insert after target' },
        { name: '-b', description: 'Insert before target' },
        { name: '-d', description: 'Do not make window current' },
        { name: '-k', description: 'Kill existing window' },
        { name: '-s', description: 'Source window', args: { name: 'src-window' } },
        { name: '-t', description: 'Target window', args: { name: 'dst-window' } },
      ],
    },
    {
      name: 'linkw',
      description: 'Alias for link-window',
    },
    {
      name: 'unlink-window',
      description: 'Unlink a window',
      options: [
        { name: '-k', description: 'Kill window if only link' },
        { name: '-t', description: 'Target window', args: { name: 'target-window' } },
      ],
    },
    {
      name: 'unlinkw',
      description: 'Alias for unlink-window',
    },
    {
      name: 'break-pane',
      description: 'Break a pane out to a new window',
      options: [
        { name: '-a', description: 'Insert after target' },
        { name: '-b', description: 'Insert before target' },
        { name: '-d', description: 'Do not make window current' },
        { name: '-F', description: 'Format output', args: { name: 'format' } },
        { name: '-n', description: 'Window name', args: { name: 'window-name' } },
        { name: '-P', description: 'Print info about new window' },
        { name: '-s', description: 'Source pane', args: { name: 'src-pane' } },
        { name: '-t', description: 'Target window', args: { name: 'dst-window' } },
      ],
    },
    {
      name: 'breakp',
      description: 'Alias for break-pane',
    },
    {
      name: 'join-pane',
      description: 'Split a pane and move a target into it',
      options: [
        { name: '-b', description: 'Insert left/above' },
        { name: '-d', description: 'Do not make pane active' },
        { name: '-f', description: 'Create full-width/height pane' },
        { name: '-h', description: 'Split horizontally' },
        { name: '-l', description: 'Size', args: { name: 'size' } },
        { name: '-p', description: 'Percentage', args: { name: 'percentage' } },
        { name: '-s', description: 'Source pane', args: { name: 'src-pane' } },
        { name: '-t', description: 'Target pane', args: { name: 'dst-pane' } },
        { name: '-v', description: 'Split vertically' },
      ],
    },
    {
      name: 'joinp',
      description: 'Alias for join-pane',
    },
    {
      name: 'swap-window',
      description: 'Swap two windows',
      options: [
        { name: '-d', description: 'Do not change active window' },
        { name: '-s', description: 'Source window', args: { name: 'src-window' } },
        { name: '-t', description: 'Target window', args: { name: 'dst-window' } },
      ],
    },
    {
      name: 'swapw',
      description: 'Alias for swap-window',
    },
    {
      name: 'rotate-window',
      description: 'Rotate positions of panes in a window',
      options: [
        { name: '-D', description: 'Rotate down' },
        { name: '-t', description: 'Target window', args: { name: 'target-window' } },
        { name: '-U', description: 'Rotate up' },
        { name: '-Z', description: 'Keep zoomed' },
      ],
    },
    {
      name: 'rotatew',
      description: 'Alias for rotate-window',
    },
    {
      name: 'find-window',
      description: 'Search for a pattern in windows',
      options: [
        { name: '-C', description: 'Match visible contents' },
        { name: '-i', description: 'Case insensitive' },
        { name: '-N', description: 'Match window name' },
        { name: '-r', description: 'Use regex' },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
        { name: '-T', description: 'Match window title' },
        { name: '-Z', description: 'Zoom pane' },
      ],
      args: { name: 'match-string' },
    },
    {
      name: 'findw',
      description: 'Alias for find-window',
    },
    {
      name: 'choose-tree',
      description: 'Put a pane into tree mode',
      options: [
        { name: '-F', description: 'Format output', args: { name: 'format' } },
        { name: '-f', description: 'Filter', args: { name: 'filter' } },
        { name: '-G', description: 'Include preview' },
        { name: '-K', description: 'Initial key', args: { name: 'key-format' } },
        { name: '-N', description: 'Start scrolled down' },
        { name: '-O', description: 'Sort order', args: { name: 'sort-order' } },
        { name: '-r', description: 'Reverse sort' },
        { name: '-s', description: 'Collapse sessions' },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
        { name: '-w', description: 'Collapse windows' },
        { name: '-Z', description: 'Zoom pane' },
      ],
      args: { name: 'template', isOptional: true },
    },
    {
      name: 'choose-session',
      description: 'Put a pane into session mode',
      options: [
        { name: '-F', description: 'Format output', args: { name: 'format' } },
        { name: '-f', description: 'Filter', args: { name: 'filter' } },
        { name: '-K', description: 'Initial key', args: { name: 'key-format' } },
        { name: '-N', description: 'Start scrolled down' },
        { name: '-O', description: 'Sort order', args: { name: 'sort-order' } },
        { name: '-r', description: 'Reverse sort' },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
        { name: '-Z', description: 'Zoom pane' },
      ],
      args: { name: 'template', isOptional: true },
    },
    {
      name: 'choose-window',
      description: 'Put a pane into window mode',
      options: [
        { name: '-F', description: 'Format output', args: { name: 'format' } },
        { name: '-f', description: 'Filter', args: { name: 'filter' } },
        { name: '-K', description: 'Initial key', args: { name: 'key-format' } },
        { name: '-N', description: 'Start scrolled down' },
        { name: '-O', description: 'Sort order', args: { name: 'sort-order' } },
        { name: '-r', description: 'Reverse sort' },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
        { name: '-Z', description: 'Zoom pane' },
      ],
      args: { name: 'template', isOptional: true },
    },
    {
      name: 'choose-client',
      description: 'Put a pane into client mode',
      options: [
        { name: '-F', description: 'Format output', args: { name: 'format' } },
        { name: '-f', description: 'Filter', args: { name: 'filter' } },
        { name: '-K', description: 'Initial key', args: { name: 'key-format' } },
        { name: '-N', description: 'Start scrolled down' },
        { name: '-O', description: 'Sort order', args: { name: 'sort-order' } },
        { name: '-r', description: 'Reverse sort' },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
        { name: '-Z', description: 'Zoom pane' },
      ],
      args: { name: 'template', isOptional: true },
    },
    {
      name: 'display-panes',
      description: 'Display pane numbers',
      options: [
        { name: '-b', description: 'Do not block' },
        { name: '-d', description: 'Duration', args: { name: 'duration' } },
        { name: '-N', description: 'Ignore keys' },
        { name: '-t', description: 'Target client', args: { name: 'target-client' } },
      ],
      args: { name: 'template', isOptional: true },
    },
    {
      name: 'displayp',
      description: 'Alias for display-panes',
    },
    {
      name: 'respawn-pane',
      description: 'Reactivate a pane with a dead process',
      options: [
        { name: '-c', description: 'Start directory', args: { name: 'dir', template: 'folders' } },
        { name: '-e', description: 'Set environment variable', args: { name: 'KEY=VALUE' } },
        { name: '-k', description: 'Kill active process' },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
      ],
      args: { name: 'shell-command', isOptional: true },
    },
    {
      name: 'respawnp',
      description: 'Alias for respawn-pane',
    },
    {
      name: 'respawn-window',
      description: 'Reactivate a window with a dead process',
      options: [
        { name: '-c', description: 'Start directory', args: { name: 'dir', template: 'folders' } },
        { name: '-e', description: 'Set environment variable', args: { name: 'KEY=VALUE' } },
        { name: '-k', description: 'Kill active process' },
        { name: '-t', description: 'Target window', args: { name: 'target-window' } },
      ],
      args: { name: 'shell-command', isOptional: true },
    },
    {
      name: 'respawnw',
      description: 'Alias for respawn-window',
    },
    {
      name: 'select-layout',
      description: 'Choose a specific layout for a window',
      options: [
        { name: '-E', description: 'Spread panes evenly' },
        { name: '-n', description: 'Next layout' },
        { name: '-o', description: 'Last layout' },
        { name: '-p', description: 'Previous layout' },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
      ],
      args: {
        name: 'layout-name',
        isOptional: true,
        suggestions: [
          { name: 'even-horizontal', description: 'Spread panes horizontally' },
          { name: 'even-vertical', description: 'Spread panes vertically' },
          { name: 'main-horizontal', description: 'Main pane on top' },
          { name: 'main-vertical', description: 'Main pane on left' },
          { name: 'tiled', description: 'Tiled layout' },
        ],
      },
    },
    {
      name: 'selectl',
      description: 'Alias for select-layout',
    },
    {
      name: 'next-layout',
      description: 'Move to the next layout',
      options: [
        { name: '-t', description: 'Target window', args: { name: 'target-window' } },
      ],
    },
    {
      name: 'nextl',
      description: 'Alias for next-layout',
    },
    {
      name: 'previous-layout',
      description: 'Move to the previous layout',
      options: [
        { name: '-t', description: 'Target window', args: { name: 'target-window' } },
      ],
    },
    {
      name: 'prevl',
      description: 'Alias for previous-layout',
    },
    {
      name: 'lock-server',
      description: 'Lock all clients',
    },
    {
      name: 'lock-session',
      description: 'Lock all clients attached to a session',
      options: [
        { name: '-t', description: 'Target session', args: { name: 'target-session' } },
      ],
    },
    {
      name: 'locks',
      description: 'Alias for lock-session',
    },
    {
      name: 'lock-client',
      description: 'Lock a single client',
      options: [
        { name: '-t', description: 'Target client', args: { name: 'target-client' } },
      ],
    },
    {
      name: 'lockc',
      description: 'Alias for lock-client',
    },
    {
      name: 'wait-for',
      description: 'Wait for an event or a signal from another client',
      options: [
        { name: '-L', description: 'Lock the channel' },
        { name: '-S', description: 'Send/signal the channel' },
        { name: '-U', description: 'Unlock the channel' },
      ],
      args: { name: 'channel' },
    },
    {
      name: 'wait',
      description: 'Alias for wait-for',
    },
    {
      name: 'confirm-before',
      description: 'Run a command after user confirmation',
      options: [
        { name: '-b', description: 'Do not block' },
        { name: '-p', description: 'Prompt', args: { name: 'prompt' } },
        { name: '-t', description: 'Target client', args: { name: 'target-client' } },
      ],
      args: { name: 'command' },
    },
    {
      name: 'confirm',
      description: 'Alias for confirm-before',
    },
    {
      name: 'command-prompt',
      description: 'Open the command prompt in a client',
      options: [
        { name: '-1', description: 'Only first key counts' },
        { name: '-b', description: 'Do not block' },
        { name: '-F', description: 'Expand formats' },
        { name: '-i', description: 'Execute on key', args: { name: 'inputs' } },
        { name: '-I', description: 'Initial text', args: { name: 'inputs' } },
        { name: '-k', description: 'Accept key' },
        { name: '-N', description: 'Count', args: { name: 'count' } },
        { name: '-p', description: 'Prompts', args: { name: 'prompts' } },
        { name: '-t', description: 'Target client', args: { name: 'target-client' } },
        { name: '-T', description: 'Prompt type', args: { name: 'prompt-type' } },
        { name: '-W', description: 'Do not complete' },
      ],
      args: { name: 'template', isOptional: true },
    },
    {
      name: 'if-shell',
      description: 'Execute a command if a shell command succeeds',
      options: [
        { name: '-b', description: 'Run in background' },
        { name: '-F', description: 'Expand formats' },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
      ],
      args: [
        { name: 'shell-command', description: 'Shell command to test' },
        { name: 'command', description: 'Command if true' },
        { name: 'command', description: 'Command if false', isOptional: true },
      ],
    },
    {
      name: 'if',
      description: 'Alias for if-shell',
    },
    {
      name: 'display-menu',
      description: 'Display a menu',
      options: [
        { name: '-b', description: 'Do not block' },
        { name: '-c', description: 'Target client', args: { name: 'target-client' } },
        { name: '-C', description: 'Close selected item' },
        { name: '-O', description: 'Do not close on exit' },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
        { name: '-T', description: 'Title', args: { name: 'title' } },
        { name: '-x', description: 'X position', args: { name: 'position' } },
        { name: '-y', description: 'Y position', args: { name: 'position' } },
      ],
      args: { name: 'menu-item', isVariadic: true },
    },
    {
      name: 'menu',
      description: 'Alias for display-menu',
    },
    {
      name: 'display-popup',
      description: 'Display a popup',
      options: [
        { name: '-b', description: 'Border style', args: { name: 'border-lines' } },
        { name: '-B', description: 'Do not draw border' },
        { name: '-c', description: 'Target pane', args: { name: 'target-pane' } },
        { name: '-C', description: 'Close on exit' },
        { name: '-d', description: 'Start directory', args: { name: 'dir', template: 'folders' } },
        { name: '-e', description: 'Set environment variable', args: { name: 'KEY=VALUE' } },
        { name: '-E', description: 'Close on any key' },
        { name: '-h', description: 'Height', args: { name: 'height' } },
        { name: '-s', description: 'Style', args: { name: 'style' } },
        { name: '-S', description: 'Border style', args: { name: 'border-style' } },
        { name: '-t', description: 'Target client', args: { name: 'target-client' } },
        { name: '-T', description: 'Title', args: { name: 'title' } },
        { name: '-w', description: 'Width', args: { name: 'width' } },
        { name: '-x', description: 'X position', args: { name: 'position' } },
        { name: '-y', description: 'Y position', args: { name: 'position' } },
      ],
      args: { name: 'shell-command', isOptional: true },
    },
    {
      name: 'popup',
      description: 'Alias for display-popup',
    },
    {
      name: 'clear-history',
      description: 'Remove and clear history for a pane',
      options: [
        { name: '-H', description: 'Clear only history' },
        { name: '-t', description: 'Target pane', args: { name: 'target-pane' } },
      ],
    },
    {
      name: 'clearhist',
      description: 'Alias for clear-history',
    },
  ],
};
