// uv - Ultra-fast Python package installer and resolver
import { CompletionSpec } from '../types.js';

export const uvSpec: CompletionSpec = {
  name: 'uv',
  description: 'An extremely fast Python package installer and resolver',
  options: [
    { name: ['-q', '--quiet'], description: 'Quiet output' },
    { name: ['-v', '--verbose'], description: 'Verbose output' },
    { name: '--color', description: 'Color output', args: { name: 'when', suggestions: [{ name: 'auto' }, { name: 'always' }, { name: 'never' }] } },
    { name: '--native-tls', description: 'Use native TLS' },
    { name: '--offline', description: 'Offline mode' },
    { name: '--no-progress', description: 'Hide progress' },
    { name: '--config-file', description: 'Config file', args: { name: 'file', template: 'filepaths' } },
    { name: '--no-config', description: 'Ignore config file' },
    { name: ['-h', '--help'], description: 'Print help' },
    { name: ['-V', '--version'], description: 'Print version' },
  ],
  subcommands: [
    {
      name: 'pip',
      description: 'Manage Python packages with a pip-compatible interface',
      subcommands: [
        {
          name: 'install',
          description: 'Install packages',
          options: [
            { name: ['-r', '--requirement'], description: 'Requirements file', args: { name: 'file', template: 'filepaths' } },
            { name: ['-c', '--constraint'], description: 'Constraints file', args: { name: 'file', template: 'filepaths' } },
            { name: '--override', description: 'Override file', args: { name: 'file', template: 'filepaths' } },
            { name: ['-e', '--editable'], description: 'Editable install', args: { name: 'path', template: 'folders' } },
            { name: '--extra', description: 'Extra to install', args: { name: 'extra' } },
            { name: '--all-extras', description: 'Install all extras' },
            { name: '--no-deps', description: 'No dependencies' },
            { name: ['-U', '--upgrade'], description: 'Upgrade packages' },
            { name: '--upgrade-package', description: 'Upgrade specific package', args: { name: 'package' } },
            { name: '--reinstall', description: 'Reinstall packages' },
            { name: '--reinstall-package', description: 'Reinstall specific package', args: { name: 'package' } },
            { name: ['-i', '--index-url'], description: 'Index URL', args: { name: 'url' } },
            { name: '--extra-index-url', description: 'Extra index URL', args: { name: 'url' } },
            { name: ['-f', '--find-links'], description: 'Find links', args: { name: 'url' } },
            { name: '--no-index', description: 'No index' },
            { name: '--index-strategy', description: 'Index strategy', args: { name: 'strategy', suggestions: [{ name: 'first-index' }, { name: 'unsafe-first-match' }, { name: 'unsafe-best-match' }] } },
            { name: '--keyring-provider', description: 'Keyring provider', args: { name: 'provider', suggestions: [{ name: 'disabled' }, { name: 'subprocess' }] } },
            { name: '--python', description: 'Python interpreter', args: { name: 'python', template: 'filepaths' } },
            { name: '--system', description: 'Install in system Python' },
            { name: '--break-system-packages', description: 'Allow breaking system packages' },
            { name: '--target', description: 'Install to target directory', args: { name: 'dir', template: 'folders' } },
            { name: '--prefix', description: 'Install prefix', args: { name: 'prefix', template: 'folders' } },
            { name: '--no-build-isolation', description: 'No build isolation' },
            { name: '--build-isolation', description: 'Use build isolation' },
            { name: '--exclude-newer', description: 'Exclude packages newer than', args: { name: 'date' } },
            { name: '--link-mode', description: 'Link mode', args: { name: 'mode', suggestions: [{ name: 'clone' }, { name: 'copy' }, { name: 'hardlink' }, { name: 'symlink' }] } },
            { name: '--compile-bytecode', description: 'Compile bytecode' },
            { name: '--no-compile-bytecode', description: 'No bytecode compilation' },
            { name: '--no-sources', description: 'Ignore pyproject.toml sources' },
            { name: '--resolution', description: 'Resolution strategy', args: { name: 'strategy', suggestions: [{ name: 'highest' }, { name: 'lowest' }, { name: 'lowest-direct' }] } },
            { name: '--prerelease', description: 'Prerelease mode', args: { name: 'mode', suggestions: [{ name: 'disallow' }, { name: 'allow' }, { name: 'if-necessary' }, { name: 'explicit' }, { name: 'if-necessary-or-explicit' }] } },
            { name: '--pre', description: 'Allow prereleases' },
            { name: '--cache-dir', description: 'Cache directory', args: { name: 'dir', template: 'folders' } },
            { name: ['-n', '--no-cache'], description: 'No cache' },
            { name: '--refresh', description: 'Refresh cache' },
            { name: '--refresh-package', description: 'Refresh specific package', args: { name: 'package' } },
            { name: '--dry-run', description: 'Dry run' },
            { name: '--strict', description: 'Strict mode' },
          ],
          args: { name: 'packages', description: 'Packages to install', isVariadic: true },
        },
        {
          name: 'uninstall',
          description: 'Uninstall packages',
          options: [
            { name: ['-r', '--requirement'], description: 'Requirements file', args: { name: 'file', template: 'filepaths' } },
            { name: '--python', description: 'Python interpreter', args: { name: 'python', template: 'filepaths' } },
            { name: '--system', description: 'System Python' },
            { name: '--break-system-packages', description: 'Allow breaking system packages' },
            { name: '--target', description: 'Target directory', args: { name: 'dir', template: 'folders' } },
            { name: '--prefix', description: 'Prefix', args: { name: 'prefix', template: 'folders' } },
            { name: '--cache-dir', description: 'Cache directory', args: { name: 'dir', template: 'folders' } },
            { name: ['-n', '--no-cache'], description: 'No cache' },
          ],
          args: { name: 'packages', description: 'Packages to uninstall', isVariadic: true },
        },
        { name: 'list', description: 'List installed packages', options: [{ name: ['-e', '--editable'] }, { name: '--exclude-editable' }, { name: '--strict' }, { name: '--python', args: { name: 'python', template: 'filepaths' } }, { name: '--system' }, { name: '--format', args: { name: 'format', suggestions: [{ name: 'columns' }, { name: 'freeze' }, { name: 'json' }] } }] },
        { name: 'show', description: 'Show package information', options: [{ name: '--python', args: { name: 'python', template: 'filepaths' } }, { name: '--system' }, { name: '--files' }], args: { name: 'package', isVariadic: true } },
        { name: 'freeze', description: 'List installed packages in requirements format', options: [{ name: '--python', args: { name: 'python', template: 'filepaths' } }, { name: '--system' }, { name: '--strict' }, { name: '--exclude-editable' }] },
        { name: 'check', description: 'Verify installed packages', options: [{ name: '--python', args: { name: 'python', template: 'filepaths' } }, { name: '--system' }] },
        { name: 'tree', description: 'Display dependency tree', options: [{ name: '--python', args: { name: 'python', template: 'filepaths' } }, { name: '--system' }, { name: '--depth', args: { name: 'depth' } }, { name: '--prune' }, { name: '--no-dedupe' }, { name: '--package', args: { name: 'package' } }, { name: '--invert' }] },
        { name: 'compile', description: 'Compile requirements', options: [{ name: ['-o', '--output-file'], args: { name: 'file', template: 'filepaths' } }, { name: ['-c', '--constraint'], args: { name: 'file', template: 'filepaths' } }, { name: '--override', args: { name: 'file', template: 'filepaths' } }, { name: '--extra', args: { name: 'extra' } }, { name: '--all-extras' }, { name: '--no-deps' }, { name: '--resolution', args: { name: 'strategy' } }, { name: '--prerelease', args: { name: 'mode' } }, { name: '--pre' }, { name: ['-U', '--upgrade'] }, { name: '--upgrade-package', args: { name: 'package' } }, { name: '--generate-hashes' }, { name: '--no-emit-package', args: { name: 'package' } }, { name: '--emit-index-url' }, { name: '--emit-find-links' }, { name: '--emit-build-options' }, { name: '--emit-marker-expression' }, { name: '--emit-index-annotation' }, { name: '--annotation-style', args: { name: 'style', suggestions: [{ name: 'line' }, { name: 'split' }] } }, { name: '--no-strip-extras' }, { name: '--no-strip-markers' }, { name: '--no-annotate' }, { name: '--no-header' }, { name: '--custom-compile-command', args: { name: 'command' } }, { name: '--python', args: { name: 'python', template: 'filepaths' } }, { name: '--python-version', args: { name: 'version' } }, { name: '--python-platform', args: { name: 'platform' } }, { name: '--universal' }], args: { name: 'files', template: 'filepaths', isOptional: true, isVariadic: true } },
        { name: 'sync', description: 'Sync an environment', options: [{ name: '--reinstall' }, { name: '--reinstall-package', args: { name: 'package' } }, { name: '--python', args: { name: 'python', template: 'filepaths' } }, { name: '--system' }, { name: '--break-system-packages' }, { name: '--no-build-isolation' }, { name: '--allow-empty-requirements' }, { name: '--strict' }], args: { name: 'files', template: 'filepaths', isOptional: true, isVariadic: true } },
      ],
    },
    {
      name: 'venv',
      description: 'Create a virtual environment',
      options: [
        { name: ['-p', '--python'], description: 'Python interpreter', args: { name: 'python', template: 'filepaths' } },
        { name: '--system-site-packages', description: 'Include system site-packages' },
        { name: '--relocatable', description: 'Make relocatable' },
        { name: '--seed', description: 'Install seed packages' },
        { name: '--allow-existing', description: 'Allow existing directory' },
        { name: '--prompt', description: 'Environment prompt', args: { name: 'prompt' } },
        { name: '--index-url', description: 'Index URL', args: { name: 'url' } },
        { name: '--extra-index-url', description: 'Extra index URL', args: { name: 'url' } },
        { name: '--link-mode', description: 'Link mode', args: { name: 'mode', suggestions: [{ name: 'clone' }, { name: 'copy' }, { name: 'hardlink' }, { name: 'symlink' }] } },
        { name: '--exclude-newer', description: 'Exclude packages newer than', args: { name: 'date' } },
        { name: '--cache-dir', description: 'Cache directory', args: { name: 'dir', template: 'folders' } },
        { name: ['-n', '--no-cache'], description: 'No cache' },
      ],
      args: { name: 'path', description: 'Virtual environment path', template: 'folders', isOptional: true },
    },
    {
      name: 'run',
      description: 'Run a command in a project environment',
      options: [
        { name: '--extra', description: 'Extra to install', args: { name: 'extra' } },
        { name: '--all-extras', description: 'Install all extras' },
        { name: '--dev', description: 'Include dev dependencies' },
        { name: '--no-dev', description: 'Exclude dev dependencies' },
        { name: '--only-dev', description: 'Only dev dependencies' },
        { name: '--group', description: 'Include group', args: { name: 'group' } },
        { name: '--no-group', description: 'Exclude group', args: { name: 'group' } },
        { name: '--only-group', description: 'Only group', args: { name: 'group' } },
        { name: '--all-groups', description: 'Include all groups' },
        { name: '--locked', description: 'Use locked dependencies' },
        { name: '--frozen', description: 'Don\'t update lockfile' },
        { name: '--isolated', description: 'Isolated run' },
        { name: '--with', description: 'Run with package', args: { name: 'package' } },
        { name: '--with-requirements', description: 'Run with requirements', args: { name: 'file', template: 'filepaths' } },
        { name: '--python', description: 'Python interpreter', args: { name: 'python', template: 'filepaths' } },
        { name: '--module', description: 'Run as module' },
        { name: '--no-sync', description: 'Don\'t sync before running' },
        { name: '--package', description: 'Package name', args: { name: 'package' } },
        { name: '--no-project', description: 'Ignore project' },
        { name: ['-i', '--index-url'], description: 'Index URL', args: { name: 'url' } },
        { name: '--extra-index-url', description: 'Extra index URL', args: { name: 'url' } },
        { name: ['-f', '--find-links'], description: 'Find links', args: { name: 'url' } },
        { name: '--no-index', description: 'No index' },
        { name: '--script', description: 'Run script', args: { name: 'script', template: 'filepaths' } },
        { name: '--env-file', description: 'Env file', args: { name: 'file', template: 'filepaths' } },
        { name: '--show', description: 'Show command to run' },
      ],
      args: { name: 'command', description: 'Command to run', isVariadic: true },
    },
    {
      name: 'sync',
      description: 'Update the project environment',
      options: [
        { name: '--extra', description: 'Extra to install', args: { name: 'extra' } },
        { name: '--all-extras', description: 'Install all extras' },
        { name: '--dev', description: 'Include dev dependencies' },
        { name: '--no-dev', description: 'Exclude dev dependencies' },
        { name: '--only-dev', description: 'Only dev dependencies' },
        { name: '--group', description: 'Include group', args: { name: 'group' } },
        { name: '--no-group', description: 'Exclude group', args: { name: 'group' } },
        { name: '--only-group', description: 'Only group', args: { name: 'group' } },
        { name: '--all-groups', description: 'Include all groups' },
        { name: '--locked', description: 'Use locked dependencies' },
        { name: '--frozen', description: 'Don\'t update lockfile' },
        { name: ['-U', '--upgrade'], description: 'Upgrade packages' },
        { name: '--upgrade-package', description: 'Upgrade specific package', args: { name: 'package' } },
        { name: '--reinstall', description: 'Reinstall packages' },
        { name: '--reinstall-package', description: 'Reinstall specific package', args: { name: 'package' } },
        { name: '--python', description: 'Python interpreter', args: { name: 'python', template: 'filepaths' } },
        { name: '--inexact', description: 'Allow inexact sync' },
        { name: '--no-install-project', description: 'Don\'t install project' },
        { name: '--no-install-workspace', description: 'Don\'t install workspace' },
        { name: '--no-install-package', description: 'Don\'t install package', args: { name: 'package' } },
        { name: '--package', description: 'Package name', args: { name: 'package' } },
        { name: '--dry-run', description: 'Dry run' },
      ],
    },
    {
      name: 'lock',
      description: 'Update the project lockfile',
      options: [
        { name: ['-U', '--upgrade'], description: 'Upgrade packages' },
        { name: '--upgrade-package', description: 'Upgrade specific package', args: { name: 'package' } },
        { name: '--python', description: 'Python interpreter', args: { name: 'python', template: 'filepaths' } },
        { name: '--dry-run', description: 'Dry run' },
      ],
    },
    {
      name: 'add',
      description: 'Add dependencies to the project',
      options: [
        { name: ['-r', '--requirement'], description: 'Requirements file', args: { name: 'file', template: 'filepaths' } },
        { name: '--dev', description: 'Add as dev dependency' },
        { name: '--optional', description: 'Add as optional', args: { name: 'extra' } },
        { name: '--group', description: 'Add to group', args: { name: 'group' } },
        { name: '--editable', description: 'Editable install' },
        { name: '--extra', description: 'Extra to install', args: { name: 'extra' } },
        { name: '--tag', description: 'Git tag', args: { name: 'tag' } },
        { name: '--branch', description: 'Git branch', args: { name: 'branch' } },
        { name: '--rev', description: 'Git revision', args: { name: 'rev' } },
        { name: '--raw-sources', description: 'Add raw source' },
        { name: '--no-sync', description: 'Don\'t sync after adding' },
        { name: '--locked', description: 'Use locked dependencies' },
        { name: '--frozen', description: 'Don\'t update lockfile' },
        { name: '--python', description: 'Python interpreter', args: { name: 'python', template: 'filepaths' } },
        { name: '--package', description: 'Package name', args: { name: 'package' } },
        { name: '--script', description: 'Add to script', args: { name: 'script', template: 'filepaths' } },
      ],
      args: { name: 'packages', description: 'Packages to add', isVariadic: true },
    },
    {
      name: 'remove',
      description: 'Remove dependencies from the project',
      options: [
        { name: '--dev', description: 'Remove from dev dependencies' },
        { name: '--optional', description: 'Remove from optional', args: { name: 'extra' } },
        { name: '--group', description: 'Remove from group', args: { name: 'group' } },
        { name: '--no-sync', description: 'Don\'t sync after removing' },
        { name: '--locked', description: 'Use locked dependencies' },
        { name: '--frozen', description: 'Don\'t update lockfile' },
        { name: '--python', description: 'Python interpreter', args: { name: 'python', template: 'filepaths' } },
        { name: '--package', description: 'Package name', args: { name: 'package' } },
        { name: '--script', description: 'Remove from script', args: { name: 'script', template: 'filepaths' } },
      ],
      args: { name: 'packages', description: 'Packages to remove', isVariadic: true },
    },
    {
      name: 'tree',
      description: 'Display the project\'s dependency tree',
      options: [
        { name: '--universal', description: 'Universal mode' },
        { name: '--depth', description: 'Maximum depth', args: { name: 'depth' } },
        { name: '--prune', description: 'Prune duplicates' },
        { name: '--no-dedupe', description: 'Don\'t dedupe' },
        { name: '--package', description: 'Show package', args: { name: 'package' } },
        { name: '--invert', description: 'Invert tree' },
        { name: '--outdated', description: 'Show outdated' },
        { name: '--locked', description: 'Use locked dependencies' },
        { name: '--frozen', description: 'Don\'t update lockfile' },
        { name: '--python', description: 'Python interpreter', args: { name: 'python', template: 'filepaths' } },
      ],
    },
    {
      name: 'tool',
      description: 'Run and install commands provided by Python packages',
      subcommands: [
        { name: 'run', description: 'Run a tool', options: [{ name: '--from', description: 'Package source', args: { name: 'package' } }, { name: '--with', description: 'Run with package', args: { name: 'package' } }, { name: '--with-requirements', description: 'Run with requirements', args: { name: 'file', template: 'filepaths' } }, { name: ['-i', '--index-url'], description: 'Index URL', args: { name: 'url' } }, { name: '--extra-index-url', description: 'Extra index URL', args: { name: 'url' } }, { name: ['-f', '--find-links'], description: 'Find links', args: { name: 'url' } }, { name: '--no-index', description: 'No index' }, { name: '--python', description: 'Python interpreter', args: { name: 'python', template: 'filepaths' } }, { name: '--isolated', description: 'Isolated run' }], args: { name: 'command', isVariadic: true } },
        { name: 'install', description: 'Install a tool', options: [{ name: '--editable', description: 'Editable install' }, { name: '--from', description: 'Package source', args: { name: 'package' } }, { name: '--with', description: 'Install with package', args: { name: 'package' } }, { name: '--with-requirements', description: 'Install with requirements', args: { name: 'file', template: 'filepaths' } }, { name: ['-i', '--index-url'], description: 'Index URL', args: { name: 'url' } }, { name: '--extra-index-url', description: 'Extra index URL', args: { name: 'url' } }, { name: ['-f', '--find-links'], description: 'Find links', args: { name: 'url' } }, { name: '--no-index', description: 'No index' }, { name: '--python', description: 'Python interpreter', args: { name: 'python', template: 'filepaths' } }, { name: '--force', description: 'Force reinstall' }], args: { name: 'package' } },
        { name: 'upgrade', description: 'Upgrade a tool', options: [{ name: '--all', description: 'Upgrade all' }], args: { name: 'packages', isOptional: true, isVariadic: true } },
        { name: 'uninstall', description: 'Uninstall a tool', args: { name: 'packages', isVariadic: true } },
        { name: 'list', description: 'List installed tools', options: [{ name: '--show-paths' }] },
        { name: 'update-shell', description: 'Update shell configuration' },
        { name: 'dir', description: 'Show tool directory', options: [{ name: '--bin' }] },
      ],
    },
    {
      name: 'python',
      description: 'Manage Python versions',
      subcommands: [
        { name: 'list', description: 'List available Python versions', options: [{ name: '--all-versions', description: 'Show all versions' }, { name: '--all-platforms', description: 'Show all platforms' }, { name: '--only-installed', description: 'Only installed' }] },
        { name: 'install', description: 'Download and install Python', options: [{ name: ['-r', '--reinstall'], description: 'Reinstall' }], args: { name: 'versions', description: 'Versions to install', isVariadic: true } },
        { name: 'find', description: 'Search for a Python installation', args: { name: 'request', isOptional: true } },
        { name: 'pin', description: 'Pin to a Python version', options: [{ name: '--resolved' }], args: { name: 'version', isOptional: true } },
        { name: 'uninstall', description: 'Uninstall Python versions', options: [{ name: '--all' }], args: { name: 'versions', isVariadic: true } },
        { name: 'dir', description: 'Show the uv Python installation directory' },
      ],
    },
    { name: 'init', description: 'Create a new Python project', options: [{ name: '--name', args: { name: 'name' } }, { name: '--virtual' }, { name: '--no-readme' }, { name: '--no-pin-python' }, { name: '--no-workspace' }, { name: '--lib' }, { name: '--app' }, { name: '--script', args: { name: 'script' } }, { name: '--package' }, { name: '--no-package' }, { name: ['-p', '--python'], args: { name: 'python' } }, { name: '--build-backend', args: { name: 'backend', suggestions: [{ name: 'hatch' }, { name: 'flit' }, { name: 'pdm' }, { name: 'setuptools' }, { name: 'maturin' }, { name: 'scikit-build' }] } }], args: { name: 'path', template: 'folders', isOptional: true } },
    { name: 'build', description: 'Build the project', options: [{ name: '--sdist' }, { name: '--wheel' }, { name: '--out-dir', args: { name: 'dir', template: 'folders' } }, { name: '--build-constraint', args: { name: 'file', template: 'filepaths' } }], args: { name: 'src', template: 'folders', isOptional: true } },
    { name: 'publish', description: 'Upload distributions to an index', options: [{ name: '--publish-url', args: { name: 'url' } }, { name: ['-u', '--username'], args: { name: 'username' } }, { name: ['-p', '--password'], args: { name: 'password' } }, { name: ['-t', '--token'], args: { name: 'token' } }, { name: '--trusted-publishing', args: { name: 'mode', suggestions: [{ name: 'automatic' }, { name: 'always' }, { name: 'never' }] } }, { name: '--keyring-provider', args: { name: 'provider' } }, { name: '--check-url', args: { name: 'url' } }], args: { name: 'files', template: 'filepaths', isOptional: true, isVariadic: true } },
    { name: 'cache', description: 'Manage the uv cache', subcommands: [
      { name: 'clean', description: 'Clear the cache', args: { name: 'package', isOptional: true, isVariadic: true } },
      { name: 'prune', description: 'Prune unused cache entries', options: [{ name: '--ci' }] },
      { name: 'dir', description: 'Show the cache directory' },
    ]},
    { name: 'self', description: 'Manage the uv executable', subcommands: [
      { name: 'update', description: 'Update uv to the latest version', options: [{ name: '--token', args: { name: 'token' } }] },
    ]},
    { name: 'version', description: 'Display uv version', options: [{ name: '--output-format', args: { name: 'format', suggestions: [{ name: 'text' }, { name: 'json' }] } }] },
    { name: 'export', description: 'Export the project lockfile', options: [{ name: '--format', args: { name: 'format', suggestions: [{ name: 'requirements-txt' }] } }, { name: ['-o', '--output-file'], args: { name: 'file', template: 'filepaths' } }, { name: '--no-hashes' }, { name: '--no-emit-project' }, { name: '--no-emit-workspace' }, { name: '--no-emit-package', args: { name: 'package' } }, { name: '--extra', args: { name: 'extra' } }, { name: '--all-extras' }, { name: '--dev' }, { name: '--no-dev' }, { name: '--only-dev' }, { name: '--group', args: { name: 'group' } }, { name: '--no-group', args: { name: 'group' } }, { name: '--only-group', args: { name: 'group' } }, { name: '--all-groups' }, { name: '--locked' }, { name: '--frozen' }] },
    { name: 'help', description: 'Display documentation for a command', args: { name: 'command', isOptional: true, isVariadic: true } },
  ],
};
